### ISSUE TITLE
Remove all XML based config

### ISSUE THREAD

**Issue by timja** [jenkinsci/helm-charts#10]
Use JCasC config instead

Currently the chart has two configuration options:

via XML configuration files, which basically renders XML documents
via Configuration as Code plugins
The second one is preferred as it allows updating the configuration. With XML that's impossible as users could have changed settings via the Jenkins UI.

As the chart support JCasC configuration I suggest to get rid of all XML configuration options. This hopefully also makes it easier for users of the chart as they don't have to worry about if a configuration is done via XML or JCasC and be surprised if their setting is not applied.

**Comment by torstenwalter** [comment]
With #34 I created a draft which removes all XML configuration options.
Would appreciate any help in reviewing it. I tried to remove things from inner blocks to outer ones to not to forget removing  values from `values.yaml` which are no longer used.

These are quite some changes after all...

**Comment by torstenwalter** [comment]
Closed with #34 and #153
