### ISSUE TITLE
Renovate doesn't pick up GH action updates

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/helm-charts#1005]
`helm/kind-action@v1.9.0` released earlier the day. I see renovate actions running, but no PR is created to update
https://github.com/jenkinsci/helm-charts/blob/2e461a611cb00dca24dd44cb30e65e592cc65f06/.github/workflows/lint-test.yaml#L66
to v1.9.0

Am I missing something?

**Comment by timja** [comment]
in the logs you can see:

```
"message": "To [https://github.com/jenkinsci/helm-charts.git\n!\trefs/heads/renovate/helm-kind-action-1.x:refs/heads/renovate/helm-kind-action-1.x\t[remote](https://github.com/jenkinsci/helm-charts.git/n!/trefs/heads/renovate/helm-kind-action-1.x:refs/heads/renovate/helm-kind-action-1.x/t[remote) rejected] (refusing to allow a GitHub App to create or update workflow `.github/workflows/lint-test.yaml` without `workflows` permission)\nDone\nPushing to [https://github.com/jenkinsci/helm-charts.git\nPOST](https://github.com/jenkinsci/helm-charts.git/nPOST) git-receive-pack (684 bytes)\nerror: failed to push some refs to 'https://github.com/jenkinsci/helm-charts.git'\n",
         "stack": "Error: To https://**redacted**@3.22.0/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/usr/local/renovate/node_modules/.pnpm/simple-git@3.22.0/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /usr/local/renovate/node_modules/.pnpm/simple-git@3.22.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/local/renovate/node_modules/.pnpm/simple-git@3.22.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/usr/local/renovate/node_modules/.pnpm/simple-git@3.22.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/local/renovate/node_modules/.pnpm/simple-git@3.22.0/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
```

**Comment by timja** [comment]
I enabled it which created a couple of PRs

**Comment by timja** [comment]
> DEBUG: Reached branch limit - skipping branch creation (repository=jenkinsci/helm-charts, branch=renovate/helm-kind-action-1.x)

**Comment by timja** [comment]
Not sure why it's not doing it now =/

**Comment by NotMyFault** [comment]
I've approved the permission request, but https://docs.renovatebot.com/configuration-options/#branchconcurrentlimit isn't set at all 🤔

**Comment by kvanzuijlen** [comment]
PR has been opened via #1009. It indeed required workflows write permissions and only opens 2 PRs per hour.

**Comment by kvanzuijlen** [comment]
There are a couple of limits that can be configured:
- `branchConcurrentLimit`: the number of branches that can exist simultaneously, defaults to `prConcurrentLimit`
- `prConcurrentLimit`: the number of PRs that can exist simultaneously, defaults to 10
- `prHourlyLimit`: the number of PRs that can be created per hour, defaults to 2

This last limit was the limit Renovate was running into earlier today.
