### ISSUE TITLE
Mistake in CHANGELOG.md?

### ISSUE THREAD

**Issue by matandomuertos** [jenkinsci/helm-charts#1021]
### Describe the bug

Maybe it's a irrelevant and stupid question, but is it intended that, since the helm chart `5.0.10` the changelog has lines like:
> Update `jenkins/inbound-agent` to version `jenkins/inbound-agent`

> Update `docker.io/kiwigrid/k8s-sidecar` to version `docker.io/kiwigrid/k8s-sidecar`

> Update `jenkins/jenkins` to version `jenkins/jenkins`

instead of:

> Update `jenkins/jenkins` to version `2.440.1`

It changes nothing, with a few clicks you can see the new version. But was that intended or it's a mistake? I can fix it if it was a mistake but I'm just wondering if there is a reason behind.

### Chart version

>5.0.10

**Comment by kvanzuijlen** [comment]
No, not intended! Looks like an error I made with the automation. I'll look into it. Thanks for noticing!
