### ISSUE TITLE
Renovate doesn't update CHANGELOG correctly

### ISSUE THREAD

**Issue by kvanzuijlen** [jenkinsci/helm-charts#1028]
### Describe the bug

Renovate doesn't update the CHANGELOG correctly. Instead of inserting the version number it includes the dependency name twice.

### Chart version

5.0.16

### What happened?

```bash
The post-upgrade script is called with the following arguments: `.github/renovate-postupgrade.sh docker.io/kiwigrid/k8s-sidecar docker.io/kiwigrid/k8s-sidecar 1.25.6`.
```

**Comment by lemeurherve** [comment]
FTR, we don't usually assign issues in jenkins repositories.
