### ISSUE TITLE
Building docker image

### ISSUE THREAD

**Issue by parikmaan** [jenkinsci/helm-charts#103]
Hi

I have been trying to set up jenkinsci/helm-chart to build docker images.

My setup:

- Minikube
- jenkinsci/helm-charts deployed to minikube

All other features are working fine. But when I try to build a docker image, it complains docker not found.

If I install docker from archive file (link to download not working, maybe docker download link is broken), I am getting following error:

> docker: not found

I tried using following example:

[dind.groovy - jenkinsci/kubernetes-plugin](https://github.com/jenkinsci/kubernetes-plugin/blob/master/examples/dind.groovy)

But not able to build image because it's building multiple stages and copying files from one stage to another.

Is there a simple example for building docker image out of box like we get on Jenkins installed directly on host machine instead of container installation.

Thanks

**Comment by rafaeltokyo** [comment]
i have same error

**Comment by sadaiyer** [comment]
Same issue

**Comment by torstenwalter** [comment]
> If I install docker from archive file (link to download not working, maybe docker download link is broken), I am getting following error:

@parikmaan Why are you trying to install docker?

The example https://github.com/jenkinsci/kubernetes-plugin/blob/master/examples/dind.groovy starts a new pod which contains a docker container https://github.com/jenkinsci/kubernetes-plugin/blob/master/examples/dind.groovy#L17-L18.

As it's executing the docker command in that container that should be sufficient.
https://github.com/jenkinsci/kubernetes-plugin/blob/master/examples/dind.groovy#L36-L38

**Comment by sadaiyer** [comment]
Got it to work, had to use a different image (joao29a/jnlp-slave-alpine-docker:latest) for agent.  Why need docker:  trying to build image and push, and the Default image throws an error - docker not found

**Comment by torstenwalter** [comment]
The image you are using combines two things:
- jnlp agent which is responsible to connect the agent with the Jenkins controller (it needs a JVM)
- docker - the tool you actually want

One great flexibility the Kubernetes plugin provides is that you can use different things for these purposes. To you can use a jnlp container which cares about connectivity with the Jenkins controller and use any other image which contain the tools you really need.

That decoupling brings quite some benefits and it's nearly free as the jnlp container is automatically injected in case you don't specify one.

**Comment by parikmaan** [comment]
> > If I install docker from archive file (link to download not working, maybe docker download link is broken), I am getting following error:
> 
> @parikmaan Why are you trying to install docker?
> 
> The example https://github.com/jenkinsci/kubernetes-plugin/blob/master/examples/dind.groovy starts a new pod which contains a docker container https://github.com/jenkinsci/kubernetes-plugin/blob/master/examples/dind.groovy#L17-L18.
> 
> As it's executing the docker command in that container that should be sufficient.
> https://github.com/jenkinsci/kubernetes-plugin/blob/master/examples/dind.groovy#L36-L38

@torstenwalter Thanks for your reply. I followed the example from the link. During docker build, process try to copy artifacts from one step in Dockerfile to another step in docker file. It fails with message that directory not found.

`# Stage 1
FROM node:10-alpine as build-step`

`# Stage 2
FROM nginx:1.17.1-alpine
COPY --from=build-step /app/docs /usr/share/nginx/html`

If I build this on my local machine this works fine. But not on the Jenkinsci helm chart. Wanted to check if there is something that is out there that works out of the box. Or some documentation for this to follow. Thanks

**Comment by jiayiwang7** [comment]
> > > If I install docker from archive file (link to download not working, maybe docker download link is broken), I am getting following error:
> > 
> > 
> > @parikmaan Why are you trying to install docker?
> > The example https://github.com/jenkinsci/kubernetes-plugin/blob/master/examples/dind.groovy starts a new pod which contains a docker container https://github.com/jenkinsci/kubernetes-plugin/blob/master/examples/dind.groovy#L17-L18.
> > As it's executing the docker command in that container that should be sufficient.
> > https://github.com/jenkinsci/kubernetes-plugin/blob/master/examples/dind.groovy#L36-L38
> 
> @torstenwalter Thanks for your reply. I followed the example from the link. During docker build, process try to copy artifacts from one step in Dockerfile to another step in docker file. It fails with message that directory not found.
> 
> `# Stage 1 FROM node:10-alpine as build-step`
> 
> `# Stage 2 FROM nginx:1.17.1-alpine COPY --from=build-step /app/docs /usr/share/nginx/html`
> 
> If I build this on my local machine this works fine. But not on the Jenkinsci helm chart. Wanted to check if there is something that is out there that works out of the box. Or some documentation for this to follow. Thanks

did you find a solution yet?

**Comment by torstenwalter** [comment]
The README now contains instructions how to build a Jenkins image with pre-installed plugins.

**Comment by jiayiwang7** [comment]
I setup Kubernetes Plugin and followed this example: https://github.com/jenkinsci/kubernetes-plugin/blob/master/examples/dind.groovy

Somehow this task got stuck at branch indexing step. The agent pod keeps failing and creating new pods.

My ENV
- K8S 1.18, Amazon EKS
- Jenkins Chart:  jenkins-2.17.1 APP VERSION: lts

```
$ kubectl get pods -n jenkins
NAME                                                 READY   STATUS        RESTARTS   AGE
h1-jenkins-67c7dbb658-zw8b6                          2/2     Running       0          34h
yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-0nm21   2/3     Terminating   0          9s
yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-drpcw   2/3     Terminating   0          19s
yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-gq3bv   0/3     Terminating   0          49s
yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-s9k32   2/3     Terminating   0          29s
```

```
Branch indexing
Started by user Joey
15:38:02 Connecting to https://api.github.com using joey/****** (GitHub Access Token)
Obtained Jenkinsfile from c55aeb52dc49b0fb3f10faf29410233fe39103e5
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Created Pod: jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-gfrc0
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-gfrc0][Scheduled] Successfully assigned jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-gfrc0 to *************.us-west-2.compute.internal
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-gfrc0][Pulled] Container image "docker:19.03.1-dind" already present on machine
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-gfrc0][Created] Created container docker-daemon
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-gfrc0][Started] Started container docker-daemon
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-gfrc0][Pulled] Container image "docker:19.03.1" already present on machine
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-gfrc0][Created] Created container docker
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-gfrc0][Started] Started container docker
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-gfrc0][Pulled] Container image "jenkins/inbound-agent:4.3-4" already present on machine
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-gfrc0][Created] Created container jnlp
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-gfrc0][Started] Started container jnlp
Still waiting to schedule task
‘Jenkins’ doesn’t have label ‘yeti_feature_2Fjenkins-fix-jw_13-sxjx4’
Created Pod: jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-sg4cq
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-sg4cq][Scheduled] Successfully assigned jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-sg4cq to *********.us-west-2.compute.internal
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-sg4cq][Pulled] Container image "docker:19.03.1-dind" already present on machine
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-sg4cq][Created] Created container docker-daemon
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-sg4cq][Started] Started container docker-daemon
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-sg4cq][Pulled] Container image "docker:19.03.1" already present on machine
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-sg4cq][Created] Created container docker
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-sg4cq][Started] Started container docker
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-sg4cq][Pulled] Container image "jenkins/inbound-agent:4.3-4" already present on machine
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-sg4cq][Created] Created container jnlp
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-sg4cq][Started] Started container jnlp
Created Pod: jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-f8l6q
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-f8l6q][Scheduled] Successfully assigned jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-f8l6q to **********.us-west-2.compute.internal
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-f8l6q][Pulled] Container image "docker:19.03.1-dind" already present on machine
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-f8l6q][Created] Created container docker-daemon
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-f8l6q][Started] Started container docker-daemon
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-f8l6q][Pulled] Container image "docker:19.03.1" already present on machine
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-f8l6q][Created] Created container docker
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-f8l6q][Started] Started container docker
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-f8l6q][Pulled] Container image "jenkins/inbound-agent:4.3-4" already present on machine
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-f8l6q][Created] Created container jnlp
[Normal][jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-f8l6q][Started] Started container jnlp
Created Pod: jenkins/yeti-feature-2fjenkins-fix-jw-13-sxjx4-ss21k-nk0d1
...
```

**Comment by parikmaan** [comment]
@jiayiwang7 It was an issue with the base image I was using. So not a chart issue.

This chart works as expected from this repository.
