### ISSUE TITLE
4.12.1 -> default installPlugins are causing versioning issues

### ISSUE THREAD

**Issue by sevifives** [jenkinsci/helm-charts#1051]
### Describe the bug

My install was humming along on 4.11.x and then crapped out with plugins. I upgraded to 4.12.1 but the same issue is happening. I'm guessing there's some issue with plugin deps that are auto fetching higher versions than they should with >=?

`installPlugins:
    - kubernetes:4174.v4230d0ccd951
    - workflow-aggregator:596.v8c21c963d92d
    - git:5.1.0
    - configuration-as-code:1670.v564dc8b_982d0`

Link: https://github.com/jenkinsci/helm-charts/blob/jenkins-4.12.1/charts/jenkins/values.yaml#L249

However - this is causing massive issues with plugin deps:
`Multiple plugin prerequisites not met:
Plugin kubernetes:4174.v4230d0ccd951 (via credentials:1337.v60b_d7b_c7b_c9f) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1670.v564dc8b_982d0,
Plugin workflow-aggregator:596.v8c21c963d92d (via pipeline-input-step:477.v339683a_8d55e->credentials:1337.v60b_d7b_c7b_c9f) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1670.v564dc8b_982d0,
Plugin workflow-aggregator:596.v8c21c963d92d (via pipeline-model-definition:2.2184.v0b_358b_953e69->git-client:4.7.0) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1670.v564dc8b_982d0,
Plugin git:4.14.3 (via credentials:1337.v60b_d7b_c7b_c9f) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1670.v564dc8b_982d0,
Plugin git:4.14.3 (via git-client:4.7.0) depends on configuration-as-code:1775.v810dc950b_514, but there is an older version defined on the top level - configuration-as-code:1670.v564dc8b_982d0`

Even doing a new install results in the same issue.

### Version of Helm and Kubernetes

```markdown
- Helm: 3.12.3
- Kubernetes: v1.27.11
```

### Chart version

jenkinsci/jenkins:4.12.1

### What happened?

```bash
1. helm install jenkinstest jenkins jenkinsci/jenkins --version 4.12.1
2.
3.
...
```

### What you expected to happen?

... things to work

**Comment by timja** [comment]
Please upgrade to the latest version where this is working fine
