### ISSUE TITLE
Jenkins wont start after 5.1 upgrade

### ISSUE THREAD

**Issue by schmittvictor** [jenkinsci/helm-charts#1053]
### Describe the bug

My Jenkins instance wont start after trying to upgrade to chart 5.1. I am getting the error message :
`Update required: Configuration as Code Plugin (configuration-as-code 1763.vb_fe9c1b_83f7b) to be updated to 1775.v810dc950b_514 or higher`

I am not able to start my Jenkins instance with an older version of the chart and using differents version of the CasC plugin.

### Version of Helm and Kubernetes

```markdown
- Helm: version.BuildInfo{Version:"v3.12.3-rancher1", GitCommit:"f49ff1f7f47379f48b98ba1bb24362904179153e", GitTreeState:"clean", GoVersion:"go1.20.9"}
- Kubernetes: Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.9", GitCommit:"d1483fdf7a0578c83523bc1e2212a606a44fd71d", GitTreeState:"clean", BuildDate:"2023-09-13T11:32:41Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9+rke2r1", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T19:05:26Z", GoVersion:"go1.19.8 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

### Chart version

5.1.1

**Comment by timja** [comment]
I assume you've changed the `installPlugins` key as it is using `1775`:
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml#L395-L399

**Comment by schmittvictor** [comment]
> I assume you've changed the `installPlugins` key as it is using `1775`: https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml#L395-L399

Yes:

```
  installPlugins:
    - kubernetes:4199.va_1647c280eb_2
    - workflow-aggregator:596.v8c21c963d92d
    - git:5.2.1
    - configuration-as-code:1775.v810dc950b_514
 ```

**Comment by timja** [comment]
That looks to match the current version, is that definitely what's in your values.yaml?

**Comment by schmittvictor** [comment]
> That looks to match the current version, is that definitely what's in your values.yaml?

Yes it is

**Comment by brandonp42** [comment]
For what it's worth, I had what appears to be the same issue. To get my Jenkins instance running again I opened a shell in the container and manually copied /usr/share/jenkins/ref/plugins/configuration-as-code.jpi to /var/jenkins_home/plugins. I also copied the ssh-credentials plugin but I think that only the CasC plugin was strictly necessary.

**Comment by brandonp42** [comment]
Oh, not sure if relevant but I also deleted configuration-as-code.pinned and configuration-as-code.version_from_image

**Comment by schmittvictor** [comment]
> For what it's worth, I had what appears to be the same issue. To get my Jenkins instance running again I opened a shell in the container and manually copied /usr/share/jenkins/ref/plugins/configuration-as-code.jpi to /var/jenkins_home/plugins. I also copied the ssh-credentials plugin but I think that only the CasC plugin was strictly necessary.

Thank you that helped !
