### ISSUE TITLE
Add supplementalGroups field to pod securityContext

### ISSUE THREAD

**Issue by henrytran026** [jenkinsci/helm-charts#110]
Hello,

Would it be possible to add `supplementalGroups` to  the deployment template? We have a large PVC and every time  the pod is recreated, it takes 45-60 minutes to be reattached due to the usage of `fsGroup`. There are many issues about this problem, for example this one https://github.com/kubernetes/kubernetes/issues/67014

Up until kubernetes 1.17, specifying `supplementalGroups` instead of `fsGroup` is an  ok  workaround for this.

As of 1.18, an alpha feature has been added to specifically address this problem: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods. But it is still an alpha feature and is not likely to be enabled/permitted on multi-tenant production clusters. Therefore, allowing users of this helm chart to specify `supplementalGroups` would still be very helpful.

**Comment by torstenwalter** [comment]
@henrytran026 I overlooked this issue. Feel free to create a PR, which adds support for this.
