### ISSUE TITLE
Can't disable Jenkins login page

### ISSUE THREAD

**Issue by abdmabrouk** [jenkinsci/helm-charts#1107]
### Describe the bug

I am trying to disable the login page of Jenkins, i did the configurations as below, but it's not working, Jenkins keep showing the login page,

jenkins:
  controller:
    JCasC:
      securityRealm: |-
        local:
          allowsSignup: false
          enableCaptcha: false
      authorizationStrategy: |-
        loggedInUsersCanDoAnything:
          allowAnonymousRead: true

 when I check jenkins-jenkins-jcasc-config config map, the configuration is the same, and the changes I have made on the helm values, not getting affect on the config map configurations.

### Version of Helm and Kubernetes

```markdown
- Helm: v3.14.3
- Kubernetes: EKS 1.27
```

### Chart version

latest

### What happened?

```bash
1.
2.
3.
...
```

### What you expected to happen?

When i apply above mentioned configuration, i can reach Jenkins home page without login

**Comment by jesrig** [comment]
@abdmabrouk 
Do you have securityRealm defined in controller.JCasC.configscripts as well? The comments above controller.JCasC.security Realm state:

> Ignored if securityRealm is defined in controller.JCasC.configScripts

**Comment by abdmabrouk** [comment]
I have solved the issue using this helm values,
`controller:
  JCasC:
    configScripts:
      disable-security: |
        jenkins:
          authorizationStrategy:
            unsecured: {}
          securityRealm:
            none: {}`

**Comment by jesrig** [comment]
@abdmabrouk Can this be closed?
