### ISSUE TITLE
Tiltfile contains deprecated usage of controller.adminPassword

### ISSUE THREAD

**Issue by ml-software-services** [jenkinsci/helm-charts#1126]
### Describe the bug

If you attempt a `tilt up` inside of `charts/jenkins`, you receive this error:

Error: execution error at (jenkins/templates/deprecation.yaml:133:6): `controller.adminPassword` no longer exists. It has been renamed to `controller.admin.password`

The fix here would be update the Tiltfile to use `controller.admin.password` instead.

### Version of Helm and Kubernetes

```markdown
- Helm: 
- Kubernetes:
```

### Chart version

jenkins-5.1.30

### What happened?

```bash
1.
2.
3.
...
```

**Comment by timja** [comment]
did you want to send a pull request to fix it?
