### ISSUE TITLE
Installing dependencies of plugins in installPlugins and additionalPlugins

### ISSUE THREAD

**Issue by krystian-kulgawczuk** [jenkinsci/helm-charts#113]
Right now when plugins from `installPlugin` and `additionalPlugin`  have dependencies, they are not installed and we're getting errors. This causes major issues as plugins can have a lot of dependencies and additionaly plugins that are dependencies have also dependencies of their own. From root to leafs in dependency tree it can result in a list of hundreds of plugins.

It would be nice if this was resolved automatically as it is done when you install plugins through interface.

**Comment by torstenwalter** [comment]
Can't reproduce this. Plugin cli which is used to download plugins also downloads dependencies.
