### ISSUE TITLE
To run Jenkins on HA in Kubernetes cluster (EKS)

### ISSUE THREAD

**Issue by shudhanshuthakur1811** [jenkinsci/helm-charts#1149]
### Is your feature request related to a problem? Please describe

I want to deploy a highly-available Jenkins instance will multiple masters using AWS EFS as the backend, however, I see that in the jenkins-controller-statefulset.yaml, the value of spec.replicas is hardcoded as 1. My attempt to do a Github issues/internet search yielded no results (which sounds to me that no one tried, or wanted to try it), so I figured that I will raise a feature request here. If there is a reason why it is hardcoded (e.g. ease of maintenance) or if I should try other methods, I am happy to be educated on the topic.

### Describe the solution you'd like

make the spec.replicas value configurable in the values yaml. Some additional logic changes around the persistence block as well (e.g. accessMode).

### Describe alternatives you've considered

 I will prefer  running master on EC2 and deploying jobs on EKS Agent

### Additional context

N/A

**Comment by timja** [comment]
see https://github.com/jenkinsci/helm-charts/issues/313#issuecomment-813885573

other issue: https://github.com/jenkinsci/helm-charts/issues/718

Jenkins controller doesn't have built in support for HA, (the commercial product CloudBees CI does though)
