### ISSUE TITLE
Expose garbageCollection setting in kubernetes variable as a helm value

### ISSUE THREAD

**Issue by ben-dov** [jenkinsci/helm-charts#1173]
### Is your feature request related to a problem? Please describe

I find that if jenkins controller pod restarts when a worker pod is still `Pending`, then the resulting worker cannot connect to the controller.
It seems the worker is stuck in a loop where it tries to connect and must be terminated.

### Describe the solution you'd like

The kubernetes plugin allows configuring a garbage collection that seems to delete these pods, but there is no way to configure it from the helm values when setting `controller.JCasC.defaultConfig` to `true`. In that case, attempting to use `controller.JCasC.defaultConfig` just creates another cloud.

I would like to to be able to configure the functionality without  setting `controller.JCasC.defaultConfig` to `false`.

### Describe alternatives you've considered

I can set `controller.JCasC.defaultConfig` to `false`, but it will be a non trivial refactor.

### Additional context

the change it self should be pretty small, just adding the following lines to the the helm values
```
controller:
  garbageCollection:
    enabled: false
    namespaces: ""
    timeout: 300
```
And relevant condition in the `_helpers.tpl` that sets `jenkins.casc.defaults`

**Comment by timja** [comment]
A pull request would be welcome

**Comment by ben-dov** [comment]
@timja created :smiley:
