### ISSUE TITLE
Add OpenShift Security Context Constraints to RBAC

### ISSUE THREAD

**Issue by adambkaplan** [jenkinsci/helm-charts#1207]
### Is your feature request related to a problem? Please describe

When deploying Jenkins via the helm chart on OpenShift, the StatefulSet pods are not created because they do not meet the `restricted` or `restricted-v2` [Security Context Constraint](https://docs.okd.io/latest/authentication/managing-security-context-constraints.html) (SCC) criteria.

### Describe the solution you'd like

Add option to create additional `Role`/`RoleBinding` that grants the generated service account permission to use the `nonroot` or `nonroot-v2` SCC. Description of these SCCs is [here](https://docs.okd.io/latest/authentication/managing-security-context-constraints.html#default-sccs_configuring-internal-oauth).

### Describe alternatives you've considered

Update the helm chart - or provide a sample `values.yaml` - such that it satisfies the `restricted` or `restricted-v2` SCC. This is challenging for multiple reasons:

- The community Jenkins container images (controller and agent) expect to run as a specific non-root user.
- The default helm chart otherwise comes close to meeting the Kubernetes "restricted" [Pod Security Standard](https://kubernetes.io/docs/concepts/security/pod-security-standards/). OpenShift's `restricted` SCCs go beyond the community's standard in some respects, and relies on a separate admission controller to inject the container UID/GID which has not been adopted in the wider Kubernetes project.

**Comment by timja** [comment]
Why does it need to run with a different UID / GID?

If you can send a pull request I can take a look at it, on the surface it seems ok.

**Comment by adambkaplan** [comment]
OpenShift has an admission controller where the Pod or Container has its UID/GID injected if it is not specified in the respective security context. The value is arbitrarily high, and selected from a range defined by the `restricted-v2` SecurityContextConstraint. More info on how this works can be found [here](https://docs.openshift.com/container-platform/4.16/authentication/managing-security-context-constraints.html#security-context-constraints-pre-allocated-values).

This behavior been around for nearly a decade, predating the current [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/). It's a common pain point for developers who start with a "vanilla" Kubernetes distribution and then migrate to OpenShift, especially as more communities adopt the "restricted" Pod Security Standard. If the pod template explicitly sets a nonroot UID/GID, OpenShift will deny admission.

I'm working on a PR that grants Jenkins permission to use the appropriate SCCs.
