### ISSUE TITLE
how to upgrade jenkins helmchart from 2.6.4 to 5.7.2

### ISSUE THREAD

**Issue by amitkbaid** [jenkinsci/helm-charts#1248]
I am running Jenkins 2.401.3, helm chart 2.6.4 in GKE. The chart was deployed in 2022 and we are planning to upgrade it to latest version 5.7.2. Since this is a major version change I am being cautious to know the steps to follow when migrating from 2.6.4 to 5.7.2. 

I went through the documentation where I could find list of changes in the newer version, however I do not see any documentation to upgrade from an older version to newer version. 

I would like to know if the upgrade process only requires me to modify the values.yaml and running `helm upgrade --install` command to install the new chart ?

Note: We have upgraded Jenkins, so the current Jenkins version is 2.401.3 instead of the one bundled with the chart.

**Comment by timja** [comment]
Here's the upgrade guide:
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/UPGRADING.md

Potentially best to just start from scratch though, i.e. get the current values.yaml and work from there
