### ISSUE TITLE
Automatic release action fails at creating an index for Github pages

### ISSUE THREAD

**Issue by wzur-r3** [jenkinsci/helm-charts#126]
**Describe the bug**

Chart releaser is failing in Release Github action. See https://github.com/jenkinsci/helm-charts/runs/1362773543

**Which version of the chart**:

2.6.0

**What happened**:

Github action fails to generate index for Helm repository hosted by this project:

```
Releasing charts...
+ cr index -o jenkinsci -r helm-charts -c https://jenkinsci.github.io/helm-charts
Updating charts repo index...
====> Using existing index at .cr-index/index.yaml
Error: GET https://api.github.com/repos/jenkinsci/helm-charts/releases/tags/jenkins-2.16.0: 404 Not Found []
Usage:
  cr index [flags]

Flags:
  -c, --charts-repo string      The URL to the charts repository
  -b, --git-base-url string     GitHub Base URL (only needed for private GitHub) (default "https://api.github.com/")
  -r, --git-repo string         GitHub repository
  -u, --git-upload-url string   GitHub Upload URL (only needed for private GitHub) (default "https://uploads.github.com/")
  -h, --help                    help for index
  -i, --index-path string       Path to index file (default ".cr-index/index.yaml")
  -o, --owner string            GitHub username or organization
  -p, --package-path string     Path to directory with chart packages (default ".cr-release-packages")
  -t, --token string            GitHub Auth Token (only needed for private repos)

Global Flags:
      --config string   Config file (default is $HOME/.cr.yaml)
```

A new release has been created and a new tag is present. The URL is valid.

**What you expected to happen**:

`index.yaml` should have been generated and upload.

**Comment by wzur-r3** [comment]
very likely @torstenwalter should take a look into this issue

**Comment by torstenwalter** [comment]
@wzur-r3 Thanks for bringing this to my attention!

**Comment by torstenwalter** [comment]
This is fixed now. I think your PR #125 fixed the issue. In addition to that something went wrong while releasing 2.16.0. GitHub tag and release was created, but index not updated. As it was never published to the helm index I removed the tag and GitHub release and re-ran https://github.com/jenkinsci/helm-charts/runs/1363497288?check_suite_focus=true, which create a new release.

@timja FYI ^^^

**Comment by wzur-r3** [comment]
Hi @torstenwalter - it is worth investigating why there was a problem in the first place:

```
Error: GET https://api.github.com/repos/jenkinsci/helm-charts/releases/tags/jenkins-2.16.0: 404 Not Found []
```

That URL is valid, so either an HTTP request was done too soon, ie Github hasn't created a new release properly after the previous command finished, or perhaps that request hasn't been authenticated and it hit some rate limit quota.

**Comment by torstenwalter** [comment]
At that time GitHub had an issue. I have even seen an Nginx error message when visiting Nginx earlier.

I doubt that it's possible to hit a rate limit with the token used for the workflows in this repo. For that we would need more traffic.

**Comment by wzur-r3** [comment]
> At that time GitHub had an issue. I have even seen an Nginx error message when visiting Nginx earlier.

In that case that would explain the problem. Many thanks for your work on these Helm charts!
