### ISSUE TITLE
The latest(2.17.0) version of the chart uses install-plugins.sh instead of plugin-installation-manager-tool

### ISSUE THREAD

**Issue by dnskr** [jenkinsci/helm-charts#128]
**Describe the bug**
Current chart version uses **install-plugins.sh** by default to download plugins.
I am pretty sure it is not expected behaviour.

**Which version of the chart**:
2.17.0

**Which version of the docker image**:
jenkins/jenkins:2.249.3-lts

**What happened**:
When I deploy jenkins using chart version _2.17.0_ and docker image _jenkins/jenkins:2.249.3-lts_ init container COPY-DEFAULT-CONFIG still uses install-plugins.sh script.
I see the following logs:
```
applying Jenkins configuration
disable Setup Wizard
download plugins
WARN: install-plugins.sh is deprecated, please switch to jenkins-plugin-cli
Creating initial locks...
Analyzing war /usr/share/jenkins/jenkins.war...
Registering preinstalled plugins...
```

**What you expected to happen**:
jenkins-plugin-cli should be used by default

**Anything else we need to know**:
The root cause of the problem is in config.yaml:
```
    if [ -f "{{ .Values.master.jenkinsRef }}/jenkins.war" ] && [ -n "$(command -v jenkins-plugin-cli)" 2>/dev/null ] && [ $(version $(jenkins-plugin-cli --version)) -ge $(version "2.1.1") ]; then
      jenkins-plugin-cli --war {{ .Values.master.jenkinsRef }}/jenkins.war --plugin-file {{ .Values.master.jenkinsHome }}/plugins.txt;
    elif [ -f "{{ .Values.master.jenkinsHome }}/jenkins.war" ] && [ -n "$(command -v jenkins-plugin-cli)" 2>/dev/null ] && [ $(version $(jenkins-plugin-cli --version)) -ge $(version "2.1.1") ]; then
      jenkins-plugin-cli --war {{ .Values.master.jenkinsHome }}/jenkins.war --plugin-file {{ .Values.master.jenkinsHome }}/plugins.txt;
    else
      /usr/local/bin/install-plugins.sh `echo $(cat {{ .Values.master.jenkinsHome }}/plugins.txt)`;
    fi
```
Container has no **jenkins.war** file in default {{ .Values.master.jenkinsRef }} and {{ .Values.master.jenkinsHome }} directories
```console
$ ls /usr/share/jenkins/ref/
init.groovy.d  plugins
$ ls /var/jenkins_home/
caches									    jenkins.install.UpgradeWizard.state						   plugins.txt
casc_configs								    jenkins.model.JenkinsLocationConfiguration.xml				   proxy.xml
com.cloudbees.hudson.plugins.folder.config.AbstractFolderConfiguration.xml  jenkins.security.QueueItemAuthenticatorConfiguration.xml			   queue.xml
config.xml								    jenkins.telemetry.Correlator.xml						   secret.key
copy_reference_file.log							    jobs									   secret.key.not-so-secret
fingerprints								    logs									   secrets
hudson.model.UpdateCenter.xml						    nodeMonitors.xml								   updates
hudson.plugins.git.GitTool.xml						    nodes									   userContent
identity.key.enc							    org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.xml  users
javaposse.jobdsl.plugin.ExecuteDslScripts.xml				    org.jenkinsci.plugins.workflow.flow.FlowExecutionList.xml			   war
javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration.xml		    org.jenkinsci.plugins.workflow.libs.GlobalLibraries.xml			   workflow-libs
jenkins.install.InstallUtil.lastExecVersion				    plugins									   workspace
```

But **jenkins.war** is located in /usr/share/jenkins/ which is used by default by plugin-installation-manager-tool if --war option is not specified
```console
$ ls /usr/share/jenkins/
jenkins.war  ref
```

**Comment by torstenwalter** [comment]
Would you create a PR to fix this?

**Comment by dnskr** [comment]
I am not sure I know how to fix it in a right way because of a little knowledge about backward compatibility.
It is related to @halkeye PR. Could you please clarify if it is a bug or not, @halkeye?

**Comment by halkeye** [comment]
is there another variable pointing to that directory? It shouldn't just use the default values because everything is configurable
maybe its worth adding a check for {{ jenkinsRef }}/../

**Comment by dnskr** [comment]
Possible fix:

- switch first and second conditions
- remove ```[ -f "{{ .Values.master.jenkinsRef }}/jenkins.war" ]``` check
- remove ```--war {{ .Values.master.jenkinsRef }}/jenkins.war```

```
    if [ -f "{{ .Values.master.jenkinsHome }}/jenkins.war" ] && [ -n "$(command -v jenkins-plugin-cli)" 2>/dev/null ] && [ $(version $(jenkins-plugin-cli --version)) -ge $(version "2.1.1") ]; then
      jenkins-plugin-cli --war {{ .Values.master.jenkinsHome }}/jenkins.war --plugin-file {{ .Values.master.jenkinsHome }}/plugins.txt;
    elif [ -n "$(command -v jenkins-plugin-cli)" 2>/dev/null ] && [ $(version $(jenkins-plugin-cli --version)) -ge $(version "2.1.1") ]; then
      jenkins-plugin-cli --plugin-file {{ .Values.master.jenkinsHome }}/plugins.txt;
    else
      /usr/local/bin/install-plugins.sh `echo $(cat {{ .Values.master.jenkinsHome }}/plugins.txt)`;
    fi
```

I don't see another variable for ```/usr/share/jenkins/``` but ```{{ jenkinsRef }}/../``` should work

**Comment by halkeye** [comment]
I don't think the configurable path should be removed. Its totally up to a PR author and the chart owners to decide.

**Comment by dnskr** [comment]
Got it, thanks!
I'll make a PR for this.

**Comment by torstenwalter** [comment]
@halkeye @dnskr I checked the both `jenkinsHome` and `jenkinsRef` locations:in `jenkins/jenkins:lts` image.

jenkinsRef: "/usr/share/jenkins/ref"

```console
$ ls /usr/share/jenkins/ref
init.groovy.d
```

jenkinsHome: "/var/jenkins_home"

```console
$ ls /var/jenkins_home/
copy_reference_file.log  tini_pub.gpg
```

None of the above mentioned locations contains a `jenkins.war` file. Looks like I was relying to much on ci. I should have checked it before approving and merging the PR.

Path to Jenkins war file is actually `/usr/share/jenkins/jenkins.war`.

For me the easiest way to fix it would be to add a value `master.jenkinsWar`, which points to this default location. People who are using different images can alter it to their needs.

@halkeye Am I missing something was there a reason to check the `jenkinsRef` directory by default?

**Comment by torstenwalter** [comment]
@dnskr I just created a PR to fix this.

**Comment by halkeye** [comment]
Honestly I thought it worked. My initial versions had the path hard coded if you remember

**Comment by timja** [comment]
I doubt the required version of jenkins-plugin-cli is included in the LTS line yet also.

**Comment by halkeye** [comment]
> I doubt the required version of jenkins-plugin-cli is included in the LTS line yet also.

I think the image for 2.249.3-lts was released after we made the change. It has 2.1.1 

But the problem is that it's failing the war file check not the version check.

**Comment by timja** [comment]
ah nice!

**Comment by dnskr** [comment]
Now it works as expected. Thank you very much.

**Comment by torstenwalter** [comment]
Thanks for the feedback and for reporting this!

**Comment by abdennour** [comment]
actually, this is required as we are downloading plugins thru proxy.
Something like this : https://github.com/jenkinsci/docker/issues/1005#issuecomment-714476433

**Comment by halkeye** [comment]
Please don't hijack issues. New problems should get new tickets so they get handled that.
