### ISSUE TITLE
 /tmp volume prevents jstack/jmap to attach on openshift 

### ISSUE THREAD

**Issue by janssk1** [jenkinsci/helm-charts#135]
**Describe the bug**
It's not possible to diagnose the pod using jmap/jstack  when running inside openshift

**Which version of the chart**:
2.7.1

**What happened**:
Openshift uses a default securitycontext with userId=1000640000, group=0 and fsGroup=1000640000
Since /tmp is mounted as a volume, all files in /tmp get assigned the fsGroup. 
When jmap/jstack tries to attach, it complains that the group of the pid file in /tmp (1000640000) does not match the group of the user (0)

> jmap -heap:live 8
8: well-known file /tmp/.java_pid8 is not secure: file's group should be the current group (which is 0) but the group is 1000640000

Note that this problem will happen on any kubernetes cluster that forces a fsGroup, not just openshift. 

**What you expected to happen**:
jmap/jstack should work

**How to reproduce it** (as minimally and precisely as possible):
Start jenkins in openshift, exec into the pod an try to run eg jmap
> jmap -heap:live 8

**Anything else we need to know**:
A workaround is to chmod the pid file in /tmp before running jstack/jmap

I think this issue can be fixed by removing the /tmp volume. Since openshift enables fsGroup for all pods, all volumes will get their groups changes. 
Also, i don't think there is a need for /tmp to be a volume. AFAIK, /tmp should not be shared between containers of the jenkins pod.

**Comment by torstenwalter** [comment]
You could check if and where the tmp container is used and create a PR to fix it.
