### ISSUE TITLE
Can't start Jenkins if get.jenkins.io is down

### ISSUE THREAD

**Issue by marek-obuchowicz** [jenkinsci/helm-charts#137]
**Describe the bug**
During the loooong downtime of `get.jenkins.io` (https://github.com/jenkins-infra/jenkins.io/issues/3962) - pods created by this helm chart can't start, as they rely on plugin downloads.

**Version of Helm and Kubernetes**:

Helm Version:

```console
v3.3.4
```

Kubernetes Version:

```console
$ kubectl version
lient Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
`helm.sh/chart=jenkins-2.0.0`

**What happened**:
We rotated our k8s worker nodes and noticed, that Jenkins isn't starting

**What you expected to happen**:
I expect Jenkins to start, even if some jenkins website is down.

**How to reproduce it** (as minimally and precisely as possible):
`n/a` - probably simulating downtime of `get.jenkins.io` and connection timeouts would work.

**Anything else we need to know**:
I understand it's consequence of the way this chart was built, however - as it's official jenkins chart - it might be time to re-think this approach, or built some safety mechanism to handle this situation (ie. use plugins downloaded last time?)

**Comment by marek-obuchowicz** [comment]
I just learned about `initializeOnce` flag, which seems to address this issue directly.

**Comment by torstenwalter** [comment]
https://github.com/jenkins-infra/jenkins.io/issues/3962#issuecomment-726837191 might also help.

**Comment by Alien2150** [comment]
To add my 2 cents to it: think the overwrite plugin should be reworked. Checked it in the helm chart. It does remove the directory before downloading. I think the downloads should go into a temp dir before downloading and also check the return code. I will also try to add a PR that adds the Env that is needed to do downloads from a mirror instead

**Comment by torstenwalter** [comment]
Copying my reply here:

Jenkins Helm chart is using docker images from https://github.com/jenkinsci/docker#preinstalling-plugins.

So you should be able to use the same environment variables as described there to use a different update center when downloading plugins.

Plugin download is done using the init container. Once can set environment variables for it using `master.initContainerEnv`.

For production environments I recommend not to rely on downloading plugins at all. I suggest to build a custom image which contains all the plugins you need. That way you are independent from the update site during startup. https://github.com/jenkinsci/helm-charts/issues/12 is about describing exactly that.

https://github.com/jenkinsci/docker#preinstalling-plugins does a pretty good job on describing on how this can be done.

**Comment by torstenwalter** [comment]
> I will also try to add a PR that adds the Env that is needed to do downloads from a mirror instead

That is already possible via `master.initContainerEnv`

**Comment by Alien2150** [comment]
A cool. Thanks for pointing out @torstenwalter. Think the other statement I mentioned would remain true and is an enhancement. Will make a ticket 👍

**Comment by torstenwalter** [comment]
Sure. Any improvements there are really appreciated.
