### ISSUE TITLE
value files not working

### ISSUE THREAD

**Issue by fans3210** [jenkinsci/helm-charts#138]
**Describe the bug**
Install jenkins using helm install myjenkins jenkins/jenkins --values jenkins.values.yaml

The value file has a list of installed plugins, which never get installed. This worked about 1 month ago

**Version of Helm and Kubernetes**:
helm 3 with minikube 1.14.2

```console
$ kubectl version

**Which version of the chart**:
Latest

**Comment by torstenwalter** [comment]
Did you notice that Jenkins plugin site is down?

**Comment by fans3210** [comment]
@torstenwalter Do you mean this one: https://plugins.jenkins.io? The site is ok but I'm unable to install any plugin.
I tried to run a jerkins container like:
docker run -p 8080:8080 -p 50000:50000 
But I'm still failing in installing all the suggested plugins

**Comment by ravbaba** [comment]
Having the same issue, it worked 2-3 days ago, after running `helm install jenkins-test jenkins/jenkins` I get running jenkins but without login form and default plugins installed.

Tested with minikube on ubuntu and mac

**Comment by torstenwalter** [comment]
Duplicate of #137

**Comment by torstenwalter** [comment]
There are more issues about that:

https://github.com/jenkins-infra/jenkins.io/issues/3958
https://github.com/jenkins-infra/jenkins.io/issues/3959
https://github.com/jenkins-infra/jenkins.io/issues/3960
https://github.com/jenkins-infra/jenkins.io/issues/3962
