### ISSUE TITLE
Improve overwrite plugin logic

### ISSUE THREAD

**Issue by Alien2150** [jenkinsci/helm-charts#139]
**Is your feature request related to a problem? Please describe.**
The current way overwrite is way too aggressive as it was introducing another issue barrier (delete first then download) during the update center downtime.

**Describe the solution you'd like**
When the flag is set. All downloads should go to a temp folder which gets a persistent check (alternatively check the return code of the install operation). Only if these are ok the plugin folder should be replaced.

**Describe alternatives you've considered**
Add a flag to not delete the the plugins folder when update fail.

**Additional context**

**Comment by torstenwalter** [comment]
One thing to consider is that people could want to only have plugins (including their dependencies) installed, which are specified via `values.yaml`.

For that it would be great if we could take care of plugins being removed.

**Comment by Alien2150** [comment]
Just thought if it might be an option to "versionize" the plugin folder and than symlink the current version

**Comment by torstenwalter** [comment]
Could be an idea. We could also calculate checksum of the plugin list. We could save the that to a file and only download plugins if that checksum fails.

This is an example from the helm documentation:

> `checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}`

If one would render something like that into an environment variable then it would be available for the script to check the download.

One could even combine it with your approach and download plugins into a directory named after the checksum and symlink that directory.

To use it people should put version numbers for their plugins as it would not download newer versions if the ch ckecksum does not change.
