### ISSUE TITLE
Init:CrashLoopBackOff error on helm install

### ISSUE THREAD

**Issue by rnkhouse** [jenkinsci/helm-charts#165]
**Describe the bug**
I am getting Init:CrashLoopBackOff error on helm install

>jenkins2-0                                                        0/5     Init:CrashLoopBackOff   4          3m2s

    Events:
      Type     Reason                  Age                From                     Message
      ----     ------                  ----               ----                     -------
      Normal   Scheduled               115s               default-scheduler        Successfully assigned default/jenkins2-0 to aks-spotnodepool-12314291-vmss00001j
      Normal   SuccessfulAttachVolume  105s               attachdetach-controller  AttachVolume.Attach succeeded for volume "jenkins-home"
      Normal   Pulling                 17s (x4 over 98s)  kubelet                  Pulling image "jenkins/jenkins:lts"
      Normal   Pulled                  17s (x4 over 92s)  kubelet                  Successfully pulled image "jenkins/jenkins:lts"
      Normal   Created                 17s (x4 over 89s)  kubelet                  Created container init
      Normal   Started                 16s (x4 over 89s)  kubelet                  Started container init
      Warning  BackOff                 8s (x4 over 67s)   kubelet                  Back-off restarting failed container

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"c86ad89b8715ed17fd55b87cbb2888ccc6fa9878", GitTreeState:"clean", BuildDate:"2020-09-25T01:53:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
3.0.2

It was working fine in previous chart versions.

**Comment by torstenwalter** [comment]
Did you check logs of the init container?
Please consider using an image with pre-installed plugins as described in the README.

**Comment by rnkhouse** [comment]
@torstenwalter There were some plugin dependency errors. Thanks.

**Comment by arjunnayak11** [comment]
@torstenwalter I am getting Init:CrashLoopBackOff error on pod. I am using jenkins/stable version 1.27.0
<img width="503" alt="image" src="https://user-images.githubusercontent.com/17535099/176724968-f2ad3dd9-fced-435a-8893-f230ea77dc4a.png">

`arjun@Arjuns-MacBook-Pro-16 platform-k8s % k describe pod jenkins-79c5677d67-6jjdz -n tools 
Name:         jenkins-79c5677d67-6jjdz
Namespace:    tools
Priority:     0
Node:         ip-10-30-4-158.ec2.internal/10.30.4.158
Start Time:   Thu, 30 Jun 2022 09:41:51 -0400
Labels:       app.kubernetes.io/component=jenkins-master
              app.kubernetes.io/instance=jenkins
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=jenkins
              helm.sh/chart=jenkins-1.27.0
              pod-template-hash=79c5677d67
Annotations:  checksum/config: 29d5495fd32042669ff447cadbab7b2ed601cb16e4100d4f25f144308289f104
              kubernetes.io/psp: eks.privileged
Status:       Pending
IP:           10.30.4.200
IPs:
  IP:           10.30.4.200
Controlled By:  ReplicaSet/jenkins-79c5677d67
Init Containers:
  copy-default-config:
    Container ID:  docker://d4150b29b8b647a89ae0811309551fb91cfd7aaecad1f7f4f68bc53b1b6f083b
    Image:         jenkins/jenkins:lts
    Image ID:      docker-pullable://jenkins/jenkins@sha256:f6dfae7da7e3f93e3b214a432cfa32e1d1e581986a0d03d5ba8f44d2b8860862
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      /var/jenkins_config/apply_config.sh
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 30 Jun 2022 12:00:48 -0400
      Finished:     Thu, 30 Jun 2022 12:00:48 -0400
    Ready:          False
    Restart Count:  32
    Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:     50m
      memory:  256Mi
    Environment:
      ADMIN_PASSWORD:               <set to the key 'jenkins-admin-password' in secret 'jenkins'>  Optional: false
      ADMIN_USER:                   <set to the key 'jenkins-admin-user' in secret 'jenkins'>      Optional: false
      AWS_DEFAULT_REGION:           us-east-1
      AWS_REGION:                   us-east-1
      AWS_ROLE_ARN:                 arn:aws:iam::021467410846:role/platform-dev-jenkins
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /tmp from tmp (rw)
      /usr/share/jenkins/ref/secrets/ from secrets-dir (rw)
      /var/jenkins_config from jenkins-config (rw)
      /var/jenkins_home from jenkins-home (rw)
      /var/jenkins_plugins from plugin-dir (rw)
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from jenkins-token-rz2dd (ro)
Containers:
  jenkins:
    Container ID:  
    Image:         jenkins/jenkins:lts
    Image ID:      
    Ports:         8080/TCP, 50000/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      --argumentsRealm.passwd.$(ADMIN_USER)=$(ADMIN_PASSWORD)
      --argumentsRealm.roles.$(ADMIN_USER)=admin
      --httpPort=8080
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:      50m
      memory:   256Mi
    Liveness:   http-get http://:http/login delay=90s timeout=5s period=10s #success=1 #failure=5
    Readiness:  http-get http://:http/login delay=60s timeout=5s period=10s #success=1 #failure=3
    Environment:
      POD_NAME:                     jenkins-79c5677d67-6jjdz (v1:metadata.name)
      JAVA_OPTS:                    
      JENKINS_OPTS:                 
      JENKINS_SLAVE_AGENT_PORT:     50000
      ADMIN_PASSWORD:               <set to the key 'jenkins-admin-password' in secret 'jenkins'>  Optional: false
      ADMIN_USER:                   <set to the key 'jenkins-admin-user' in secret 'jenkins'>      Optional: false
      AWS_DEFAULT_REGION:           us-east-1
      AWS_REGION:                   us-east-1
      AWS_ROLE_ARN:                 arn:aws:iam::021467410846:role/platform-dev-jenkins
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /tmp from tmp (rw)
      /usr/share/jenkins/ref/plugins/ from plugin-dir (rw)
      /usr/share/jenkins/ref/secrets/ from secrets-dir (rw)
      /var/jenkins_config from jenkins-config (ro)
      /var/jenkins_home from jenkins-home (rw)
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from jenkins-token-rz2dd (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  aws-iam-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  86400
  plugins:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  jenkins-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      jenkins
    Optional:  false
  secrets-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  plugin-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  jenkins-home:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  jenkins
    ReadOnly:   false
  jenkins-token-rz2dd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  jenkins-token-rz2dd
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                     From     Message
  ----     ------   ----                    ----     -------
  Warning  BackOff  3m46s (x650 over 143m)  kubelet  Back-off restarting failed container`
  
  It was working fine until yesterday not sure what happen all of a sudden.
