### ISSUE TITLE
Extra secrets for Jenkins container to keep credentials passwords/files/tokens

### ISSUE THREAD

**Issue by oisis** [jenkinsci/helm-charts#167]
**Is your feature request related to a problem? Please describe.**
Currently i can setup Jenkins via CasC and that is fine(thanks for good work), but what to do with credentials? I do not want to keep them in configMap and even if could, currently there is no possibility to do it. I know i can find tools like HashiCorp Vault but i do not need such a complicated solution to add lets say 2 secrets.

**Describe the solution you'd like**
IMHO best way could be to add something like you already have implemented with envs, for example:
```
controller:
  extraSecrets:
    var1: value1
    var2: value2
```
If chart could support this i could use SOPS and encrypt all password in one file.

**Describe alternatives you've considered**
Like i said Vault but sometimes is too complicated solution if you do not need secret management tool.

**Comment by torstenwalter** [comment]
Did you check https://jenkinsci.github.io/kubernetes-credentials-provider-plugin/?

You need to set the following so that the service account has the required permissions:

```
rbac:
  readSecrets: true
```

See also: https://docs.google.com/presentation/d/1RS8PwlR_FzxYypBlwtp4LcZls8hr3dG_4KJ65U00Xlo/edit#slide=id.g9cc8b7d424_0_158

**Comment by oisis** [comment]
Thanks, it is interesting, but again nie i will need two tools: Jenkins plugin and somehow create secret with credentials. Sorry but still thinking that extraSecrets is better, faster, simpler solution.

**Comment by oofnikj** [comment]
I second @oisis 's point re: having to rely on an additional plugin to handle something that can be done anyway by JCasC directly. This also relates to #168 (`secretsFilesSecret`) - I used this feature to mount additional secrets in the Jenkins controller (in my case OIDC provider credentials, which are subsequently templated out by JCasC). Many charts have a similar feature, for example `extraSecretMounts` in the official Grafana Helm chart: https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L337-L344

Without having a built-in way to mount additional secrets through the chart, managing provisioning secrets is either cumbersome (having to go through the Jenkins credentials provider) or insecure (relying on environment variables).

I am open to other suggestions, but I really think having an option like `extraSecretMounts` in the chart can be helpful for cases like this.

**Comment by oisis** [comment]
@oofnikj Thanks for hint with persistence maybe somebody will use it that way, as far as i remember i was trying to do it same way as you did(`persistence.mounts` and `persistence.volumes`). It works but you have to find out that is possible to do it that way. I still think `extraSecretMounts` will be good idea to implement.

**Comment by torstenwalter** [comment]
> UPDATE: After reviewing the chart templates, I managed to mount my extra secrets through `persistence.mounts` and `persistence.volumes`. Now I can reference these values directly in JCasC config as I did previously through `secretsFilesSecret`. Here is how I got it working: https://github.com/oofnikj/jenkins-easy/blob/master/deploy/config/values.yaml

Could you create a PR for the readme to describe there how it can be done? I think that will help others.

**Comment by torstenwalter** [comment]
Also describing how Octa can be configured might help.

**Comment by oofnikj** [comment]
Thanks @torstenwalter for the lighting-fast review. I think this covers the use case for extra secrets sufficiently.

> It works but you have to find out that is possible to do it that way. I still think extraSecretMounts will be good idea to implement.

@oisis Now that it is documented I think it's best to use an existing feature to mount secrets rather than adding a dedicated chart option for that as doing so would be duplicating functionality. Hopefully your use case is covered.
As for deploying the secrets themselves, I guess it is workflow dependent but I can recommend Kustomize + Flux Helm Operator. This way you only need one deploy tool.

**Comment by torstenwalter** [comment]
@oisis Looking forward to your feedback if this helps.

**Comment by oisis** [comment]
@torstenwalter will check this out in few days from now and let you know. Thanks.

**Comment by oisis** [comment]
@torstenwalter Looks ok but what if you have lets say 100 secrets? You need to add them one by one in mounts? I think this case should be also documented.

PS: i found typo in documentation, should be:
      `subPath: client_id`
and now is
      `subpath: client_id`

Do not get me wrong but this chart is the only one where i saw this way to mount extra secrets. I still think it is too complicated to do simple thing like add secrets to be mounted in container.

**Comment by torstenwalter** [comment]
I think you can also mount all keys from a secret. 

Do you want to test and document this?

**Comment by oisis** [comment]
@torstenwalter as far as I know, you cannot. Will double check this and let you know. If this will not work out I can create PR with extraSecret variable if you want.

**Comment by oofnikj** [comment]
> PS: i found typo in documentation, should be:
> `subPath: client_id`
> and now is
> `subpath: client_id`

I will push a fix for this.

> I think you can also mount all keys from a secret.

Yes, all keys can be mounted as individual files. In the example I included in the docs, there are two. I don't see a reason why this can't be scaled up to 100, but if you need to mount 100 individual secrets, perhaps consider using a single secret resource with multiple keys?

**Comment by missingcharacter** [comment]
FYI, I made another PR where I document how to use `controller.additionalSecrets` https://github.com/jenkinsci/helm-charts/pull/310
