### ISSUE TITLE
secretsFilesSecret is missing in new version

### ISSUE THREAD

**Issue by rnkhouse** [jenkinsci/helm-charts#168]
**Describe the bug**
I was using `master.secretsFilesSecret` in old Jenkins chart. But, it's not available in a new version. What's the replacement of it?

I was providing `master.key` and `hudson.util.Secret` in that.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
Client: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T00:06:38Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
jenkins-3.0.2

**Comment by torstenwalter** [comment]
What's your use case for it - configuring secrets?

For that you can either use https://jenkinsci.github.io/kubernetes-credentials-provider-plugin/examples/ or configure credentials via https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc

**Comment by rnkhouse** [comment]
@torstenwalter I was using that to migrate credential files from a different Jenkins server.

**Comment by torstenwalter** [comment]
That feature was removed together with XML configuration option as it conflicts with configuration as code.
I suggest to try one of the methods mentioned above.

**Comment by rnkhouse** [comment]
Alright. Thanks.

**Comment by tannerjfco** [comment]
For anyone stumbling into this issue looking for `secretsFilesSecret` replacement, the docs suggested above don't really provide what `secretsFilesSecret` did, which was to allow loading in secret files in /var/jenkins_home/secrets from a k8s secret. If you need this, the new chart provides ability to define additional volumes and mounts for the controller, and you can use that to mount your previous `secretsFilesSecret` to the specific file paths you need.

example:
```
persistence:
  volumes:
    - name: jenkins-keys
      secret:
        secretName: jenkins-keys
  mounts:
    - name: jenkins-keys
      mountPath: /var/jenkins_home/secrets/master.key
      subPath: master.key
      readOnly: true
    - name: jenkins-keys
      mountPath: /var/jenkins_home/secrets/hudson.util.Secret
      subPath: hudson.util.Secret
      readOnly: true
```
