### ISSUE TITLE
Crashloopbackoff V3.0.2

### ISSUE THREAD

**Issue by trey2001** [jenkinsci/helm-charts#171]
Upgrading to the latest chart 2.19.0 I get a crashloopbackoff and i'm unsure why as the pod won't start. I'm thinking something was added to time out on container start up but I have health probes turned off for now.
37s         Normal    Pulling                  pod/test4-jenkins-85d586b4f9-rs4bs                          Pulling image "jenkins/jenkins:lts"
37s         Normal    Pulled                   pod/test4-jenkins-85d586b4f9-rs4bs                          Successfully pulled image "jenkins/jenkins:lts"
37s         Normal    Created                  pod/test4-jenkins-85d586b4f9-rs4bs                          Created container copy-default-config
37s         Normal    Started                  pod/test4-jenkins-85d586b4f9-rs4bs                          Started container copy-default-config
9s          Warning   BackOff                  pod/test4-jenkins-85d586b4f9-rs4bs                          Back-off restarting failed container

**Comment by torstenwalter** [comment]
Did you check the logs of the different containers? Could be that there is an error shown in the init container. In case it exits with non zero exit code the pod will restart.



BTW: 2.19.0 is not the latest version of the chart.

**Comment by trey2001** [comment]
Updated to 3.0.2 the jenkins/config containers are in state of PodInitializing and the init container shows successful downloads but I did notice this:
Downloaded file is not a valid ZIP
Downloaded file is not a valid ZIP
Downloaded file is not a valid ZIP
Downloaded file is not a valid ZIP
credentials downloaded successfully
scm-api downloaded successfully
Downloaded file is not a valid ZIP
Downloaded file is not a valid ZIP
Downloaded file is not a valid ZIP

And one file that did not download:  Unable to download ace-editor

Can I turn off all plugin downloads?

**Comment by torstenwalter** [comment]
README explain how you can build an image which contains plugins and how to use it.

**Comment by trey2001** [comment]
I turned off plugins but it's still downloading. I'll have to go through the steps to create a custom image I suppose I'm not sure with installPlugins: []   it's still trying to.
