### ISSUE TITLE
Provide configuration option for timezone

### ISSUE THREAD

**Issue by pcornelissen** [jenkinsci/helm-charts#182]
**Is your feature request related to a problem? Please describe.**
I am using the jenkins helm chart, running in my kubernetes cluster. The time of all builds seems to be GMT, but I am in GMT+1 and it seems, there is no easy way to set that for the container.

All proposed fixes for the jenkins timezone require to set certain java options or configure the host, which doesn't help with containers.

I'd like to avoid having to for the helm chart or roll out my own jenkins container

**Comment by torstenwalter** [comment]
@pcornelissen What would you suggest to implement it?

Are you aware of https://plugins.jenkins.io/timestamper/? This helps you to show timestamps in the locale of the browser you are using. In my experience (working with teams distributed over different countries) that is superior than the configuring a timezone on the server.
It also allows to disable timestamps or show elapsed time since the build started.

**Comment by pcornelissen** [comment]
Good question, I wasn't aware of that plugin, I'll give that a try. But in my builds I also create timestamps and I assume that the plugin doesn't help there a lot. I'll get back to you when I tried that

**Comment by pcornelissen** [comment]
OK, I checked that and it basically just displays log timestamps differently.

So, what would be good is either a way to set the timezone in the jenkins container (which might be harder) or a way to set the jenkins java properties (-D....) from within the helm values file. In this case you could provide the timezone (and more) by configuring it in your values file.

**Comment by binarywang** [comment]
> Assuming this could help others here's how this could be done through the values provided by the chart:
> 
> ```
> controller:
>   initScripts:
>     - |
>       System.setProperty('org.apache.commons.jelly.tags.fmt.timeZone', 'Europe/Berlin')
>       System.setProperty('user.timezone', 'Europe/Berlin')
> ```

thanks, is there any new simple way to complish this right now as to the latest version?

**Comment by ophintor** [comment]
> Assuming this could help others here's how this could be done through the values provided by the chart:
> 
> ```
> controller:
>   initScripts:
>     - |
>       System.setProperty('org.apache.commons.jelly.tags.fmt.timeZone', 'Europe/Berlin')
>       System.setProperty('user.timezone', 'Europe/Berlin')
> ```

Thanks! That worked for me.
