### ISSUE TITLE
copy-default-config - How to skip check "there is an older version defined on the top level" ?

### ISSUE THREAD

**Issue by Giancarlo1974** [jenkinsci/helm-charts#186]
**Describe the bug**
The installation of the chart by setting certain versions of plugins (installPlugins) in the values

```
  installPlugins:
    - ace-editor:1.1
    - active-directory:2.20
    - amazon-ecr:1.6
    - ansible:1.1
    - ansicolor:0.7.3
    - apache-httpcomponents-client-4-api:4.5.10-2.0
    - authentication-tokens:1.4
    - aws-bucket-credentials:1.0.0
    - aws-credentials:1.28
    - aws-java-sdk:1.11.854
    - blueocean-autofavorite:1.2.4
    - blueocean-bitbucket-pipeline:1.24.3
    - blueocean-commons:1.24.3
    - blueocean-config:1.24.3
    - blueocean-core-js:1.24.3
    - blueocean-dashboard:1.24.3
    - blueocean-display-url:2.4.0
    - blueocean-events:1.24.3
    - blueocean-git-pipeline:1.24.3
    - blueocean-github-pipeline:1.24.3
    - blueocean-i18n:1.24.3
    - blueocean-jira:1.24.3
    - blueocean-jwt:1.24.3
    - blueocean-personalization:1.24.3
    - blueocean-pipeline-api-impl:1.24.3
    - blueocean-pipeline-editor:1.24.3
    - blueocean-pipeline-scm-api:1.24.3
    - blueocean-rest-impl:1.24.3
    - blueocean-rest:1.24.3
    - blueocean-web:1.24.3
    - blueocean:1.24.3
    - bouncycastle-api:2.18
    - cloudbees-bitbucket-branch-source:2.9.4
    - cloudbees-folder:6.15
    - configuration-as-code:1.46
    - credentials-binding:1.24
    - credentials:2.3.14
    - display-url-api:2.3.4
    - docker-commons:1.17
    - docker-workflow:1.25
    - durable-task:1.35
    - extended-read-permission:3.2
    - favorite:2.3.2
    - generic-webhook-trigger:1.72
    - git-client:3.5.1
    - git-server:1.9
    - git:4.4.5
    - github-api:1.117
    - github-branch-source:2.9.1
    - github:1.32.0
    - handlebars:1.1.1
    - handy-uri-templates-2-api:2.1.8-1.0
    - htmlpublisher:1.25
    - http_request:1.8.27
    - jackson2-api:2.12.0
    - jenkins-design-language:1.24.3
    - jira:3.1.3
    - job-import-plugin:3.4
    - job-restrictions:0.8
    - jquery-detached:1.2.1
    - jsch:0.1.55.2
    - junit:1.44
    - kubernetes-client-api:4.11.1
    - kubernetes-credentials:0.7.0
    - kubernetes:1.26.3 # danger, if you upgrade, Jenkins becomes unstable
    - lockable-resources:2.10
    - mailer:1.32.1
    - matrix-auth:2.6.4
    - matrix-project:1.18
    - mercurial:2.12
    - momentjs:1.1.1
    - next-build-number:1.6
    - Office-365-Connector:4.13.2
    - okhttp-api:3.14.9
    - pipeline-aws:1.43
    - pipeline-build-step:2.13
    - pipeline-graph-analysis:1.10
    - pipeline-input-step:2.12
    - pipeline-milestone-step:1.3.1
    - pipeline-model-api:1.7.2
    - pipeline-model-definition:1.7.2
    - pipeline-model-extensions:1.7.2
    - pipeline-rest-api:2.19
    - pipeline-stage-step:2.5
    - pipeline-stage-tags-metadata:1.7.2
    - pipeline-stage-view:2.19
    - pipeline-utility-steps:2.6.1
    - plain-credentials:1.7
    - pubsub-light:1.13
    - role-strategy:3.1
    - scm-api:2.6.4
    - script-security:1.75
    - simple-theme-plugin:0.6
    - snakeyaml-api:1.27.0
    - sonar-quality-gates:1.3.1
    - sonar:2.1
    - sse-gateway:1.24
    - ssh-credentials:1.18.1
    - structs:1.20
    - token-macro:2.12
    - throttle-concurrents:2.0.3
    - trilead-api:1.0.12
    - variant:1.3
    - workflow-aggregator:2.6
    - workflow-api:2.40
    - workflow-basic-steps:2.22
    - workflow-cps-global-lib:2.17
    - workflow-cps:2.87
    - workflow-durable-task-step:2.37
    - workflow-job:2.40
    - workflow-multibranch:2.22
    - workflow-scm-step:2.11
    - workflow-step-api:2.23
    - workflow-support:3.7

```

fails to install plugins correctly.
The init container copy-default-config fails with:

`kubectl logs jenkins-3569d7g576-tcm1s copy-default-config`

```
applying Jenkins configuration
apply XML configuration
copy XML configuration
download plugins
cp: overwrite '/var/jenkins_home/config.xml'? cp: overwrite '/var/jenkins_home/jenkins.CLI.xml'? cp: overwrite '/var/jenkins_home/jenkins.model.JenkinsLocationConfiguration.xml'? Plugin blueocean-autofavorite:1.2.4 depends on git:4.5.0, but there is an older version defined on the top level - git:4.4.5

```
**Attention:**
last week, i installed exactly this helm without changing anything

The problem happens when new versions of some plugins are released
A few weeks ago, I just killed Jenkins' POD
(so everything was installed correctly)
The POD stayed down, for that check

**Which version of the chart:**
2.19.0

**What happened:**
503 Service Temporarily Unavailable

**What you expected to happen:**
Jenkins being installed with all the provided plugins

Anything else we need to know:

is there any way to avoid this check?

**Comment by hectoralicea** [comment]
yep, I had the same exact issue which started yesterday.  I just kept removing the dependent plugin which errored, from my jcac list of plugins, and allow the plugin that needs the dependent plugin to load the correct version it needs.

for example I just removed `git:4.4.5` from my list of plugins.  You may get another plugin issue.  I had to resolve 3 of them, by removing them from the list. Then the plugin that needed the plugin loaded the correct one.

I'm  not sure you want do disable the check.  You want to go with a configuration that has been tested together.

**Comment by dnskr** [comment]
This issue is related to [plugin-installation-manager-tool](https://github.com/jenkinsci/plugin-installation-manager-tool) and one of the plugins in your `installPlugins` list.
I had the same issue last week with `git:4.4.5` and `git-parameter:0.9.13` plugins and solved it by removing `git` plugin from the list.

**Comment by Giancarlo1974** [comment]
I do not understand
In my case, which plugin should I remove from the list?

**Comment by Giancarlo1974** [comment]
In my opinion this is a very serious bug
If by bad luck Jenkins' POD dies, I would have all production blocked

Today I am trying to remove plugins from the list:
there are too many plugins wanting git: 4.4.5

git: 4.4.5 doesn't work with chart 2.19.0

at the moment i can't upgrade to chart 3.0
because I use an old version of Rancher, which only supports helm 2

**Comment by hectoralicea** [comment]
> In my case, which plugin should I remove from the list?
remove
     git: 4.4.5

The plugin that depends on this will install the correct version.

**Comment by dnskr** [comment]
> In my opinion this is a very serious bug
> If by bad luck Jenkins' POD dies, I would have all production blocked
> 
> Today I am trying to remove plugins from the list:
> there are too many plugins wanting git: 4.4.5
> 
> git: 4.4.5 doesn't work with chart 2.19.0
> 
> at the moment i can't upgrade to chart 3.0
> because I use an old version of Rancher, which only supports helm 2

You are right, it should be fixed, but the question is how and where?
This problem is not related to helm chart itself. I mean you will have the same issue with 2.17 and 3.0.6

One of the guaranteed solutions is to build your own jenkins image with all build-in plugins: https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins#consider-using-a-custom-image

**Comment by dnskr** [comment]
Hi, @Giancarlo1974 
I have created PR for this issue but for newest chart version.

In your case try this solution:
1. Downgrade chart from 2.19.0 to 2.18.2
2. Add custom init container to values.yaml
```
master:
  customInitContainers:
  - name: fixed-download-plugin
    image: "jenkins/jenkins:2.249.3"
    command:
    - "sh"
    - "-c"
    - |
      echo "Start plugins download";
      java -jar /usr/lib/jenkins-plugin-manager.jar --plugin-file /var/jenkins_config/plugins.txt --latest-specified;
      echo "Copy plugins";
      cp -i /ust/share/jenkins/ref/plugings/* /var/jenkins_plugins/;
    volumeMounts:
    - name: jenkins-config
      mountPath:  /var/jenkins_config
    - name: plugin-dir
      mountPath:  /var/jenkins_plugins
```

**Comment by twz123** [comment]
Problem with this is that it's no longer safe to evict the Jenkins Master, since you're never sure that the currently running configuration will still be accepted by Jenkins Plugin Manager. Seen this regularly in the last month. A config that was "good" a week ago becomes "invalid" because some plugin released a new point release. An example:

```
Plugin badge:1.8 depends on script-security:1.76, but there is an older version defined on the top level - script-security:1.75
```

badge:1.8 was running absolutely smoothly with script-security:1.75 and that version was also accepted as a valid dependency by Jenkins Plugin Manager one week ago. But today, it isn't anymore...

**Comment by mmerrill3** [comment]
I ran into this as well, where I have the github-branch-source plugin defined as an additional plugin in my override yaml file.  Everything was great until a restart, and the init container ran again.  Turns out the git plugin was advanced to 4.6 as the latest version of the plugin.  the github branch plugin dynamically looks for the latest, which is now 4.6, which is in conflict with the top level git plugin version of 4.5.2.  

I had to upgrade immediately to 4.6 for the git plugin, which causes the configuration as code plugin and other plugins to be required to be updated.  

The dynamic links to the "latest" for the git plugin are scary.  I know it's not a chart problem, but I do like the option to specify to the plugin loader to ignore the latest from the plugin repo.  

I didn't see a way to do that with current version of jenkins-plugin-cli that is used in my version of jenkins.

**Comment by pashcan** [comment]
@mmerrill3 Unfortunately specifying '--latest false' results in its own set of startup errors for me. Even on a list of plugins that was working fine with that flag set to true (default behaviour). With the most basic set of plugins default for the chart:
`    installPlugins:
      - kubernetes:1.27.6
      - workflow-aggregator:2.6
      - configuration-as-code:1.47
      - git:4.6.0`
I get these errors:
` Failed to load: Kubernetes Credentials Plugin (0.7.0) 
 - Update required: Docker Commons Plugin (1.5) to be updated to 1.14 or higher
Failed to load: Jenkins Git plugin (4.6.0)  
 - Update required: Matrix Project Plugin (1.4) to be updated to 1.18 or higher
Failed to load: Kubernetes plugin (1.27.6)
 - Update required: Pipeline: Groovy (2.56) to be updated to 2.83 or higher
 - Update required: Pipeline: Declarative Extension Points API (1.3.2) to be updated to 1.7.2 or higher
 - Failed to load: Kubernetes Credentials Plugin (0.7.0)`
Best bet is to stay on top of dependencies or bake your own docker images. But even then there are edge cases that caused my Jenkins instances not to start (misconfigured update center json, mirror sync issues, etc).
This is just #jenkinslife :sob:
