### ISSUE TITLE
Need to bring CA cert (.crt) into Jenkins Pod with this Chart

### ISSUE THREAD

**Issue by latituder** [jenkinsci/helm-charts#189]
**Is your feature request related to a problem? Please describe.**
Yes. We have own enterprise CA certificate. Need to install this CA cert into Jenkins, otherwise Jenkins may not accept the internal https connections;
The Jenkins container currently run with `jenkins` user, it don't have privilege to execute command `update-ca-certificates`

**Describe the solution you'd like**
Would like to provide the CA certificate(s) in `.crt` to values of this HELM Chart;
then HELM help to store it into a k8s-secret, and auto mount into jenkins container `/usr/local/share/ca-certificates` folder;
the container need to run command `update-ca-certificates` with root privilege to install the CA certs

**Describe alternatives you've considered**
remove the sts yaml `runAsNonRoot: true`, so user can run the Jenkins container as root, and install the CA certs.
but this is not a secure way to run Pod.

**Additional context**

**Comment by torstenwalter** [comment]
The best way to solve it is to build a custom image which contains the required ca certificates. For production environments this is anyhow recommend.

**Comment by latituder** [comment]
yes, custom image helps to resolve this need, but it is not very convenient because everytime Jenkins official image updates / or the CA cert expires, people need to build the custom image again;
if we can show how "inject" the CA certs from k8s-secrets to container in runtime, then it would more convenience;

**Comment by latituder** [comment]
i currently use local shell script to generate merged security store files for OS and JAVA, and place to a K8S secret;

then mount the secret to jenkins-master container in path:
/etc/ssl/certs/ca-certificates.crt
$JAVA_HOME/jre/lib/security/cacerts

is this way safe, to be integrate into HELM chart?

**Comment by fhossfel** [comment]
Why not add a lifecycle method to the statefulset? One would need to specify a ConfigMap name in values.yaml to mount under /usr/local/share/ca-certificates. An additional lifecycle handler is added to add the certs to the system and the Java keystore:

    lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "/usr/bin/update-ca-certificaes && for cert in $(ls /usr/local/share/ca-certificates/*.crt); keytool -import...; done"]

I am willing to provide a patch if this is an acceptable way forward.

**Comment by torstenwalter** [comment]
@fhossfel I suppose you would run into permissions issues if jenkins is run as non root.

**Comment by torstenwalter** [comment]
> i currently use local shell script to generate merged security store files for OS and JAVA, and place to a K8S secret;
> 
> then mount the secret to jenkins-master container in path:
> /etc/ssl/certs/ca-certificates.crt
> $JAVA_HOME/jre/lib/security/cacerts
> 
> is this way safe, to be integrate into HELM chart?

@latituder do you think it's possible to do this in the chart? E.g. to run the shell script in an init container and generate the merged security store in a temporary volume which is then mounted by jenkins container?

**Comment by fhossfel** [comment]
We run an older version of Jenkins (v 2.263.4() and user the following successfully:

    lifecycle:
      postStart": 
       exec:
          command:
          - "/usr/sbin/update-ca-certificates"

I am not wurde which user is used for the lifecycle handler. I would assume it is the one defined in the Docker image but it might be root.

**Comment by cmoulliard** [comment]
I doubt that the tricks reported here aer working as we will be faced to a permission denied error
```
for Container "jenkins" in Pod "jenkinsci-0_ci(6761199d-5213-41b2-8a19-45066a31237b)" failed - error: 
command '/bin/sh -c openssl s_client -connect gitlab.cee.redhat.com:443  < /dev/null | openssl x509 -outform PEM > /tmp/cert.pem;
cp /tmp/cert.pem /usr/local/share/ca-certificates;
update-ca-certificates
                                                                                                                          
exited with 1: 139837021189248:error:2008F002:BIO routines:BIO_lookup_ex:system lib:../crypto/bio/b_addr.c:724:Name or service not known           
connect:errno=22                                                                                                                                     
unable to load certificate                                                                                                                           
140245145207936:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
                       
cp: cannot create regular file '/usr/local/share/ca-certificates/cert.pem': Permission denied                                                        
rm: cannot remove 'ca-certificates.crt': Permission denied                                                                                           
, message: "Updating certificates in /etc/ssl/certs...\n139837021189248:error:2008F002:BIO routines:BIO_lookup_ex:system lib:../crypto/bio/b_addr.c:7
24:Name or service not known\nconnect:errno=22\nunable to load certificate\n140245145207936:error:0909006C:PEM routines:get_name:no start line:../cry
pto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE\ncp: cannot create regular file '/usr/local/share/ca-certificates/cert.pem': Permission denied\n
rm: cannot remove 'ca-certificates.crt': Permission denied\n"
```
using 
```
lifecycle:                                                                                                           
  postStart:                                                                                                         
    exec:                                                                                                            
      command:                                                                                                       
      - /bin/sh                                                                                                      
      - -c                                                                                                           
      - |                                                                                                            
        openssl s_client -connect gitlab.cee.redhat.com:443  < /dev/null | openssl x509 -outform PEM > /tmp/cert.pem;
        cp /tmp/cert.pem /usr/local/share/ca-certificates;                                                           
        update-ca-certificates
```

**Comment by jessegeens** [comment]
Any updates on this? I would love to install a self-signed CA pem that we use for LDAP, now it is impossible to properly use TLS on our LDAP connection.
