### ISSUE TITLE
Allow to set updateStrategy

### ISSUE THREAD

**Issue by olivierboudet** [jenkinsci/helm-charts#191]
The chart does not allow to change the statefulset updateStrategy. It is RollingUpdate per default but I would like to set it to OnDelete (to avoid restarting each time the config map is updated because some jobs can be running).

Would it be possible to have such a setting in values ?

**Comment by abdennour** [comment]
Guys ! please let's merge this one.
Our usecase is to disable auto rolling update of jenkins controller statefulset. Instead, we want to make it manually using "scale replica 0", then "scale replica 1"
Our old in-house helm chart considered that: 

```yaml
  updateStrategy:
    type: {{ .Values.master.updateStrategy }}
```

As now, we adopted this chart is the official chart, please review this PR #225

**Comment by abdennour** [comment]
Awesome!
