### ISSUE TITLE
Environment variables list being overridden by `--set`

### ISSUE THREAD

**Issue by fowlie** [jenkinsci/helm-charts#194]
Hi!

I'm injecting environment variables via both `--set` and `-f`, and the ones coming from `--set` is overriding the ones from `-f`.

**Is your feature request related to a problem? Please describe.**
In my setup each namespace has an autogenerated idp-secret, which means I do not know what the name of the secret will be in advance. To work around this, I have a bash script that finds the relevant secret name and then injects it as an environment variable like this:

```
--set controller.containerEnv[0].name=IDP_SECRET \
--set controller.containerEnv[0].value=$secretName
```

The problem with this approach is when I'm adding additional environment variables via the `-f` flag, it will be overridden by the ones from `--set`.

**Describe the solution you'd like**
After reading [this Helm tip](https://helm.sh/docs/chart_best_practices/values/#consider-how-users-will-use-your-values), I think it would help to define `containerEnv` as a map and not a list. Then I could to this instead:

`--set controller.containerEnv.IDP_SECRET=$secretName`

So it will be both easier to read, and it won't override other stuff.

**Describe alternatives you've considered**
For now, my workaround is to define placeholder values in the `containerEnv` list.

**Comment by gauravkr19** [comment]
The  `controller.containerEnv` does not allow the value as a map like below. This,  however, worked with the deprecated repo (https://charts.helm.sh/stable). I could not find any other way in values.yaml to declare my secrets as environment variable of type map. Please guide if there is any environment variable which can be used as a map to declare the secrets.

```
  containerEnv:
    - name: PROJECT_ID
      valueFrom:
        secretKeyRef:
            name: jenkins-k8s-config
            key: project_id
```
