### ISSUE TITLE
Azure Managed Disk PersistentVolume taking up to 40 minutes to attach

### ISSUE THREAD

**Issue by pedrohdz** [jenkinsci/helm-charts#203]
**Describe the bug**
Azure Managed Disk PersistentVolume on AKS can take anywhere from 25 to 45 minutes to attach as the `jenkins_home`.

It started at 10 minutes and has slowly increased over the course of a year, spanning multiple versions of Kubernetes, and the Jenkins Helm Chart.

After having worked this out with the Azure Support team, it was determined that the issue is https://github.com/kubernetes/kubernetes/issues/67014.  Specifically, the solution is https://github.com/kubernetes/kubernetes/issues/67014#issuecomment-589915496.

`supplementalGroups` needs to be used instead of `fsGroup` in `securityContext`.

We have a PR coming shortly.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.12", GitCommit:"5ec472285121eb6c451e515bc0a7201413872fa3", GitTreeState:"clean", BuildDate:"2020-09-16T13:39:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-20T16:22:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
`main`, but has been happening since `v2`, maybe `v1`.

**What happened**:
Azure Managed Disk PersistentVolume on AKS can take anywhere from 25 to 45 minutes to attach as the `jenkins_home`.

**What you expected to happen**:
The PersistentVolume should be taking a fraction of the time to mount.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by pedrohdz** [comment]
I totally missed that this is a duplicate of https://github.com/jenkinsci/helm-charts/issues/110.  Sorry!

Should I close this out in favor of #110?

The solution in PR #204 is slightly different though.  Instead of adding a `supplementalGroups` field to the pod `securityContext`, I opted to allow overwriting the `securityContext` field completely with the contents of the `podSecurityContextOverride` Helm Chart value.  Idea is that it would give greater flexibility in the future, also keeps the logic simpler IMO.

**Comment by torstenwalter** [comment]
If supplementalGroups can be used instead of fsGroup and that solves the issue for Azure then it would make sense to consider it as new default.
That makes it easier for users.

**Comment by pedrohdz** [comment]
Hey @torstenwalter,
I'm not entirely sure a straight replacement of the two would work to be honest. The documentation around the differences between `supplementalGroups` and `fsGroup` in regards to storage is virtually non-existent as far as I can tell.  The closest I have found is in [OpenShift - Volume Security - Supplemental Groups](https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/pod_security_context.html#supplemental-groups)

> Supplemental groups are regular Linux groups. When a process runs in Linux, it has a UID, a GID, and one or more supplemental groups. These attributes can be set for a container’s main process. The supplementalGroups IDs are typically used for controlling access to shared storage, such as NFS and GlusterFS, whereas fsGroup is used for controlling access to block storage, such as Ceph RBD and iSCSI.

So it seems like it really depends on the type of storage that is being used.  Swapping `fsGroup` with `supplementalGroups` might fix things for some people and break it for others.

I am also trying to take into backwards compatibility, as well as future-proofing.

**Comment by pedrohdz** [comment]
Also, I was thinking that something like the following should be considered for the next major release:

```
{{- if .Values.controller.usePodSecurityContext }}
      securityContext:
  {{- if hasKey .Values.controller "podSecurityContextOverride" }}
    {{- tpl (toYaml .Values.controller.podSecurityContextOverride | nindent 8) . -}}
  {{- else }}
        runAsUser: 1000
        fsGroup: 1000
        runAsNonRoot: true
  {{- end }}
{{- end }}
```

**Comment by pedrohdz** [comment]
I posted more details pertaining to the slow volume attachment times in https://github.com/kubernetes/kubernetes/issues/67014#issuecomment-754006567.

Another potential solution is setting `fsGroupChangePolicy` to `OnRootMismatch` in the pod's security context.  I have not tested this though.

**Comment by pedrohdz** [comment]
Thanks @timja!

**Comment by cmcga1125** [comment]
any updates on this?
