### ISSUE TITLE
remove unused var

### ISSUE THREAD

**Issue by Hokwang** [jenkinsci/helm-charts#211]
Hi,

I think there are unused variables any more.
One is
https://github.com/jenkinsci/helm-charts/blob/c4ad23cdb2be0091ebe48fa4966d49b1bc320362/charts/jenkins/values.yaml#L137

I think helm chart still too big and complicated for basic users,
and if specific setting needed and it can be set using jcasc, guide to use jcasc is better.

**Comment by torstenwalter** [comment]
Hi @Hokwang thanks for pointing this out. Can you create a PR to remove those?

3.0 was a big milestone to get rid of old configuration options and to promote usage of JCasC. Looks like we missed to remove those.
