### ISSUE TITLE
How restart the StateFulSet pod?

### ISSUE THREAD

**Issue by moriyahazan** [jenkinsci/helm-charts#213]
By `helm upgrade` command i want force StateFulSet pod to restart with new image, there are no changes in config files. 
I tried add following to values.xml 

> statefulSetAnnotations: 
>      timestamp: "{{ .Values.timestamp }}"
 
OR 

> statefulSetAnnotations: 
>        rollme: "{{ randAlphaNum 5 | quote }}"

But this is not helping since helm adds this value as String to resource yaml

> apiVersion: apps/v1
> kind: StatefulSet
> metadata:
>   name: jenkins
>   namespace: jenkins
>   labels:
>     "app.kubernetes.io/name": 'jenkins'
>     "helm.sh/chart": "jenkins-3.0.14"
>     "app.kubernetes.io/managed-by": "Helm"
>     "app.kubernetes.io/instance": "jenkins"
>     "app.kubernetes.io/component": "jenkins-controller"
>   annotations:
>     rollme: '{{ randAlphaNum 5 | quote }}'

Any idea?

**Comment by torstenwalter** [comment]
Best practice when using different images is to reference specific image versions. That automatically triggers a restart and makes clear what changed.
