### ISSUE TITLE
CSRF Protection Enable proxy compatibility remain false

### ISSUE THREAD

**Issue by OriBenHur** [jenkinsci/helm-charts#216]
https://github.com/jenkinsci/helm-charts/blob/3c496b75f3aa49c46d378e8750396a6f6d4d1019/charts/jenkins/values.yaml#L140-L143

https://github.com/jenkinsci/helm-charts/blob/3c496b75f3aa49c46d378e8750396a6f6d4d1019/charts/jenkins/templates/_helpers.tpl#L176-L178

For some reason, this notation is not honored and the setting remains false after Jenkins deployment

**Comment by OriBenHur** [comment]
Anyone?

**Comment by imranrazakhan** [comment]
@OriBenHur  Still same issue with latest helm chart

**Comment by OriBenHur** [comment]
I have no idea haven't redeploy it since.
I'll check when i have a chance.
