### ISSUE TITLE
Allow to load JCasC.configScripts from files in directory

### ISSUE THREAD

**Issue by vazhnov** [jenkinsci/helm-charts#218]
**Is your feature request related to a problem? Please describe.**

I'm newbie with JCasC. I'm glad to see unify format for [standalone Jenkins plugin](https://github.com/jenkinsci/configuration-as-code-plugin) and Kubernetes Helm Chart. But I'm worry about huge `values.yaml` I have to create and support.

Real Jenkins configuration can have dozens jobs. The only one way to create jobs now is to create Groovy script(s) in `controller.JCasC.configScripts`. I have to add Groovy pipelines with yaml wrapping: indents, escaping, e.t.c. The configuration became even more complicated. Syntax highlighting glitches in VIM with such big yaml file.

**Describe the solution you'd like**

From [documentation](https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins#configuration-as-code)

> The sub-keys (prior to `|` character) are only labels used to give the section a meaningful name. The only restriction is they must conform to RFC 1123 definition of a DNS label, so they may only contain lowercase letters, numbers, and hyphens.
> Each key will become the name of a configuration yaml file on the controller in `/var/jenkins_home/casc_configs` (by default) and will be processed by the Configuration as Code Plugin during Jenkins startup.

It would be great to have **possibility** to place Groovy `configScripts` code outside of `values.yaml`, with native Groovy syntax, without additional escaping. For example, stored locally in Helm Chart in separate directory. And these files will be pushed into `/var/jenkins_home/casc_configs` (but they have to be converted into yaml?)

**Describe alternatives you've considered**

* Use `--set-file controller.JCasC.configScripts=file.yaml`, but anyway it is yaml, not Groovy script file.
* Create one [seed job](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/seed-jobs.md), which will create all other jobs.

**Additional context**

\-

**Comment by avazhnov-griddynamics** [comment]
As I see in https://github.com/jenkinsci/job-dsl-plugin/wiki/JCasC :
```yaml
jobs:
  - file: ./jobdsl/job.groovy
```

Is it possible to use this syntax in Helm Chart?

**Comment by cmoulliard** [comment]
> It would be great to have **possibility** to place Groovy `configScripts` code outside of `values.yaml`, with native Groovy syntax, without additional escaping

This is mandatory !!!!

**Comment by nickjmv** [comment]
This would greatly benefit our values file as we have around 2K of groovy lines in there now... Any update on this here?

**Comment by nickjmv** [comment]
This really got closed? :(

**Comment by patsevanton** [comment]
@nickjmv @vazhnov How did you load groovy script to jenkins in Kubernets? Thanks!
