### ISSUE TITLE
Plugin installer always wants to install the latest version for plugin dependencies

### ISSUE THREAD

**Issue by ChrisRamsayITV** [jenkinsci/helm-charts#219]
**Describe the bug**
The plugin installer always wants to install the latest plugin dependency version rather than the version I have specified

**Version of Helm and Kubernetes**:

Helm Version: 3.3.4
Kubernetes Version: v1.18.9-eks-d1db3c
Kubectl version: v1.17.14

**Which version of the chart**: 3.1.0

**What happened**:
When installing plugins via controller.installPlugins, eg:
```
  installPlugins:
    - slack:2.0.1
    - ace-editor:1.1
    - active-directory:2.13
    - ansicolor:0.6.2
    - ant:1.11
   ...
```
the init container always seems to try to fetch the latest plugin version:
```
disable Setup Wizard
remove all plugins from shared volume
download plugins
Plugin slack:2.0.1 depends on junit:1.48, but there is an older version defined on the top level - junit:1.44
```

v2.0.1 of the slack plugin defines junit 1.3 as minimum: https://github.com/jenkinsci/slack-plugin/blob/slack-2.0.1/pom.xml#L50-L54 

junit:1.48 is the latest version

**What you expected to happen**:
Install the plugin versions I defined

**How to reproduce it** (as minimally and precisely as possible):
(without specifying my entire plugin list)
Specify junit:144 and slack:2.01 in controller.installPlugins

If I resolve that particular plugin version to the latest, it does it with other plugins.

**Anything else we need to know**:
This works correctly when specifying the jenkins image version of `2.235.5-lts` - it seems to have broken in later versions

**Comment by torstenwalter** [comment]
If it's an issue with the plugin installer then it would make sense to address the issue there.

**Comment by ChrisRamsayITV** [comment]
Thanks - just seen the issue mentioned here: https://github.com/jenkinsci/plugin-installation-manager-tool/issues/250
