### ISSUE TITLE
failed to download "jenkinsci/jenkins"

### ISSUE THREAD

**Issue by rnkhouse** [jenkinsci/helm-charts#22]
I ran the below commands before I installed the chart.

    helm repo add jenkinsci https://charts.jenkins.io
    helm repo update

But, still getting `failed to download "jenkinsci/jenkins"` error.

    helm search repo jenkinsci
    No results found

Logs:

    "jenkinsci" has been added to your repositories
    Hang tight while we grab the latest from your chart repositories...
    ...Skip local chart repository
    ...Successfully got an update from the "jenkinsci" chart repository
    Update Complete.

**Comment by torstenwalter** [comment]
Which version of helm are you using?

**Comment by rnkhouse** [comment]
Helm version:

Client: &version.Version{SemVer:"v2.16.10", GitCommit:"bceca24a91639f045f22ab0f41e47589a932cf5e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.10", GitCommit:"bceca24a91639f045f22ab0f41e47589a932cf5e", GitTreeState:"clean"}

**Comment by rnkhouse** [comment]
Yes. Even I can see it with `helm search jenkins`:

    NAME             	CHART VERSION	APP VERSION	DESCRIPTION                                                 
    bitnami/jenkins  	5.0.24       	2.235.5    	The leading open source automation server                   
    jenkinsci/jenkins	2.6.1        	lts        	Open source continuous integration server. It supports mu...
    stable/jenkins   	2.5.3        	lts        	Open source continuous integration server. It supports mu...

But, I am not able to install `jenkinsci/jenkins` because of the above error.

**Comment by torstenwalter** [comment]
Chart should be referenced via `jenkinsci/jenkins`. Otherwise you are trying to download it from the old location and that one is already deprecated.

```
/helm install jenkinsci/jenkins --name jenkins \
--set master.adminUser=test \
--set master.adminPassword=test123 \
--set master.numExecutors=5


```

**Comment by rnkhouse** [comment]
I think I am using the same chart name.

**Comment by torstenwalter** [comment]
For me the commands above work. Just installed it to minikube with those.

**Comment by ricardojdsilva87** [comment]
Hello, I'm having the same exact error.
The repo add and update works with no issue, I can see it if I do helm repo list:
```
NAME             	CHART VERSION	APP VERSION	DESCRIPTION
jenkinsci/jenkins	2.6.1        	lts        	Open source continuous integration server. It supports mu...
stable/jenkins   	2.5.3        	lts        	Open source continuous integration server. It supports mu...
```

I'm running the following command to install the helm chart:
```
helm upgrade --install jenkins jenkinsci/jenkinsci
```
But I always get the error:
```
Error: failed to download "jenkinsci/jenkinsci" (hint: running `helm repo update` may help)
```

Using the --debug flag I can see the following information. I'm currently using version 1.27.0 before upgrading to version 2 or above:
```
[debug] Created tunnel using local port: '63691'

[debug] SERVER: "127.0.0.1:63691"

Error: chart "jenkinsci" matching version "1.27.0" not found in jenkinsci index. (try 'helm repo update'). no chart name found
```

It seems that for some reason there are no helm versions available in the repository, the same error also appears if the version is not set:
```
Error: chart "jenkinsci" matching version "" not found in jenkinsci index. (try 'helm repo update'). no chart name found
```

I'm using the following helm version:
```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

**Comment by scottrigby** [comment]
I'm not able to reproduce the error either. Just tried on a new [kind](https://kind.sigs.k8s.io/) cluster:

```console
$ helm version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}

$ helm repo add jenkinsci https://charts.jenkins.io
"jenkinsci" has been added to your repositories

$ helm repo update
...Successfully got an update from the "jenkinsci" chart repository
Update Complete. ⎈ Happy Helming!⎈ 

$ helm search repo jenkinsci
jenkinsci/jenkins         	2.6.1        	lts        	Open source continuous integration server. It s...

$ helm search hub jenkinsci
URL                                               	CHART VERSION	APP VERSION	DESCRIPTION                                       
https://hub.helm.sh/charts/codecentric/jenkins    	1.7.0        	2.222.3    	The leading open source automation server         
https://hub.helm.sh/charts/incubator/jenkins-op...	0.3.0        	0.3.0      	A Helm chart for Kubernetes Jenkins Operator      
https://hub.helm.sh/charts/jenkinsci/jenkins      	2.6.1        	lts        	Open source continuous integration server. It s...

$helm install jenkins jenkinsci/jenkins
NAME: jenkins
LAST DEPLOYED: Thu Sep  3 09:42:40 2020
NAMESPACE: default
STATUS: deployed
...

$ kubectl get po
NAME                       READY   STATUS    RESTARTS   AGE
jenkins-565986cb87-6qt4x   2/2     Running   0          5m14s
```

**Comment by rnkhouse** [comment]
I don't know how to debug this because in search result I can see the repo but not able to install it.

**Comment by torstenwalter** [comment]
Do you still have this issue?
Could you try if you could download the release manually? e.g. https://github.com/jenkinsci/helm-charts/releases/download/jenkins-2.7.1/jenkins-2.7.1.tgz

Just want to ensure that this part works.

**Comment by rnkhouse** [comment]
@torstenwalter 
I changed my laptop recently and it's working on a new one. Closing this issue for now. Thanks for getting back.
