### ISSUE TITLE
Issues using docker on agent

### ISSUE THREAD

**Issue by byronmansfield** [jenkinsci/helm-charts#221]
**Describe the bug**
When mounting the `/var/run/docker.sock` on the inbound-agent when trying to run `docker build` or any other `docker` commands. I get permissions denied.

```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: dial unix /var/run/docker.sock: connect: permission denied
```

I understand why this occurs and generally how to resolve this. `chown jenkins:jenkins`. However, I did not have had to do this in the past. This occurs in the v3.1.1 chart. It's my first time using a 3.x.x version. I am using 2.x.x. version on many projects and this was never an issue. I just added the mount volume and it just worked. I read through the [migration guide for 3.x](https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins#to-300) and did not see anything mentioning adjustments/changes I would have to do in this case. 

**Version of Helm and Kubernetes**:

Helm Version: 

```console
$ helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**: 3.1.1

**What happened**: I mounted the `/var/run/docker.sock` to the inbound-agent pod, and get permissions denied.

**What you expected to happen**: To be able to mount the `/var/run/docker.sock` on the inbound-agent and run `docker` commands in the job, without it giving me permissions denied, as it does for me in chart version 2.x.x. Or at least it does for me.

**How to reproduce it** (as minimally and precisely as possible): Mount the `/var/run/docker.sock` to the inbound-agent. And then run a job which uses some `docker` command.

values.yaml

```
agent:
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock
```

**Anything else we need to know**: 

A minimal example of my job's `Jenkinsfile`

```
#!/usr/bin/env groovy

pipeline {
  agent any

  stages {
    stage('Build and Push Docker Image') {
      steps {
        script {
          sh "docker build -t <my-image:tag> ."
        }
      }
    }
  }
}
```

I realize this could be many things, not just the chart. It could be the docker containers, the kubernetes plugin, the cluster host the pod is running on, my configurations. I honestly don't know where the problem lays, but I am asking all of them. There are too many factors in which this issue could be coming from. But regardless, it would be nice to know how to deal with short living pods to troubleshoot. They get terminated almost as fast as they come up.

As for the docker images the inbound-agent is using. They are custom, but only to install tooling such as `docker`, `helm`, `kubectl`, `aws cli`, etc. They are all from the official inbound-agent docker image. The master/controller as well. I tried `chown`'ing the `/var/run/docker.sock` in the docker image build for the inbound-agent. But since it is not there, it fails. I thought about adding some kind of init container to do the `chmod`'ing for me. But to me that sounds like more of a hack or work-a-round. Not the proper way to handle it.

**Comment by mcandre** [comment]
Hi, I am experiencing a similar problem. I have a need for Docker in Docker in Jenkins worker jobs. However, the chart is not making this easy.

When I deploy a normal Kubernetes job pod, then I am able to use Docker in Docker. However, the chart does not accept the same volume [mount] fields. In any case, the Jenkins job reports an error.

Worker Dockerfile:

```docker
FROM jenkins/inbound-agent:4.6-1
USER root
RUN apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*
USER jenkins
```

Jenkinsfile:

```jenkins
podTemplate(containers: [
    containerTemplate(
        name: 'docker-in-docker',
        image: 'docker-in-docker:latest',
        alwaysPullImage: true,
        command: 'cat', // Fix worker infinite recursion
        ttyEnabled: true
    )
]) {
    node(POD_LABEL) {
        stage('Deploy') {
            container("docker-in-docker") {
                checkout scm
                sh """
                    docker build -t derp:latest .
                    docker rmi derp:latest
                """
            }
        }
    }
}
```

Application source Dockerfile:

```docker
FROM ubuntu
```

Trace:

```console
[Pipeline] sh

+ docker build -t derp:latest .
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
time="2021-06-01T15:30:32Z" level=error msg="failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: no such file or directory"
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```

I also tried adding `usermod -aG docker jenkins` to the worker image, just before the `USER jenkins` directive. But no luck.

**Comment by mcandre** [comment]
Update:

As jwenz723 notes, it is possible to get the correct socket mounted. Both the Helm chart and the Jenkins plugin appear to be bad at this. But the `yaml` option to `podTemplate` in the Jenkins plugin appear to work for me.

https://github.com/helm/charts/issues/7002#issuecomment-566112931

values.yaml:

(Dropped the custom configuration. Back closer to defaults.)

Jenkinsfile:

```jenkins
podTemplate(yaml: """
---
apiVersion: "v1"
kind: "Pod"
spec:
  containers:
    - name: "docker-in-docker"
      image: "docker-in-docker:latest"
      imagePullPolicy: "Always"
      tty: true
      command: ["/bin/cat"] # Fix worker infinite recursion
      volumeMounts:
      - mountPath: "/var/run/docker.sock"
        name: "docker-socket-volume"
      securityContext:
        privileged: true
        runAsUser: 0
      restartPolicy: "Never"
  volumes:
  - name: "docker-socket-volume"
    hostPath:
      path: "/var/run/docker.sock"
      type: "File"
""") {
    node(POD_LABEL) {
        stage('Deploy') {
            container("docker-in-docker") {
                checkout scm
                sh """
                    docker build -t derp:latest .
                    docker rmi derp:latest
                """
            }
        }
    }
}
```
