### ISSUE TITLE
Configure jobs with config.xml

### ISSUE THREAD

**Issue by Spritekin** [jenkinsci/helm-charts#224]
**Is your feature request related to a problem? Please describe.**
I installed version 2.15 of this chart and it works like a charm. Our developers are used to define their jobs manually while testing, then we can get the job config.xml and write it in the master.jobs section so it is maintained as code. All good.

However in this version I see all is configured with JCASC and I would like to jump to the new version but I can't find a way to write the jobs using the job config.xml. Apparently it only works using the JobDSL plugin.

For example the old job allowed us to say
```
master:
  jobs:
    backup-au-prod-mysql: |-
        <?xml version='1.1' encoding='UTF-8'?>
        <flow-definition plugin="workflow-job@2.40">
            <actions/>
            <description/>
            <keepDependencies>false</keepDependencies>
            <properties>
              ... etc
        </flow-definition>
```

And then it was written to a ConfigMap and loaded into jenkins (https://github.com/jenkinsci/helm-charts/blob/jenkins-2.15.1/charts/jenkins/templates/jobs.yaml) Easy peasy.

However it looks like that the master.jobs option has been dropped now in favour of JCASC that seems like only accepts JobDSL. Is there an alternative that won't force me to rebuild all my jobs and just use the XML jobs configuration?

**Describe the solution you'd like**
Define jobs as part of the configuration YAML using XML

**Describe alternatives you've considered**
I have considered writing a ConfigMap myself but not even sure if Jenkins will accept it.

**Comment by longc** [comment]
@Spritekin , I did a work around to get the xml jobs back to Jenkins, see https://github.com/jenkinsci/helm-charts/issues/296#issuecomment-850439273
