### ISSUE TITLE
Init scripts files are not updated on change in values

### ISSUE THREAD

**Issue by sturman** [jenkinsci/helm-charts#229]
**Describe the bug**
Each time user changes the value in `controller.initScripts` value in the chart values the changes are not applied to groovy script files in controller pod in `$JENKINS_HOME/init.groovy.d/`

**Version of Helm and Kubernetes**:

Helm Version: risko@t540p:~/projects/evconnect/evcloud-infrastructure/terraform/lower-account$  kubectl version

```console
$ helm version
terraform helm provider version = "~> 2.0"
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Which version of the chart**:
3.1.2

**What happened**:
When the user applies changes in `controller.initScripts` then the groovy files are not changes in accordance to changes in the helm chart values

**What you expected to happen**:
The groovy script files are overridden on any changes in `controller.initScripts` value

**How to reproduce it** (as minimally and precisely as possible):
- set initScripts:
  ```controller:
        initScripts:
          - |
            println("Foooooo")
  ```
- install helm chart
- change `initScripts` value:
  ```controller:
        initScripts:
          - |
            println("Baaaaar")
  ```
- upgrade helm chart release
- check Jenkins startup logs 
- the output should be "Baaaaar" but actual output is "Foooooo"
- check the file content in `$JENKINS_HOME/init.groovy.d/` in Jenkins pod
- a script file `$JENKINS_HOME/init.groovy.d/init0.groovy` is not updated with 
  ```
   println("Baaaaar")
  ```

**Anything else we need to know**:
This happens because the init script files are not overridden in `apply_config.sh` during copying from `/var/jenkins_config/` to `$JENKINS_HOME/init.groovy.d/` https://github.com/jenkinsci/helm-charts/blob/85c304950a6f85aab0e39da7e3aee299fdeaa422/charts/jenkins/templates/config.yaml#L49
Is there any reason why the init scripts should not be ever changed or it's just a bug?

**Comment by torstenwalter** [comment]
That rather sounds like a bug. We could also think about mounting the config map (or parts of it) rather then copying these files.


Would you like to create a PR to fix it?

**Comment by sturman** [comment]
@torstenwalter PR #230 is opened
