### ISSUE TITLE
UPGRADE FAILED: unable to recognize "": no matches for kind "ServiceMonitor"

### ISSUE THREAD

**Issue by holmesb** [jenkinsci/helm-charts#23]
Original issue from old stable repo is [here](https://github.com/helm/charts/issues/23371).  `master.prometheus.enabled` installs custom Prometheus Operator resources.  If Prometheus was installed using [the non-operator helm chart ](https://github.com/helm/charts/tree/master/stable/prometheus), the following error occurs:

`Error: UPGRADE FAILED: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"`

Need to add a way of simply creating a Prom metrics endpoint.  `master.prometheus.enabled` is too opinionated.  Should have been a subkey `master.prometheus.operator.enabled`.  

If `master.prometheus.enabled` = true, but `master.prometheus.operator.enabled` = false, just the exporter is added.

**Comment by torstenwalter** [comment]
The property just configures `ServiceMonitor` and `PrometheusRule`. You are right that this requires Prometheus Operator.
It also requires that [Jenkins Prometheus Metrics Plugin](https://github.com/jenkinsci/prometheus-plugin) is installed.


If you just want prometheus metrics endpoint then all you need to to is to install that plugin and set `master.prometheus.enabled: false`

**Comment by holmesb** [comment]
That's good enough for us, thx Torsten.  Perhaps just needs a note in the documentation, see PR #39
