### ISSUE TITLE
Jenkins Settings reset on pod restart

### ISSUE THREAD

**Issue by autarchprinceps** [jenkinsci/helm-charts#235]
Some Jenkins settings are not permanently stored for some reason.
Most are, like Jobs, Plugins, Users, but not for example that Users should be used (as in Global Security -> Security Realm) or the Password of the admin user, changed or left at what it was last time.

**Comment by torstenwalter** [comment]
Everything which is configured via JCasC as overwritten with whatever is configured as code. That's by design.
So the choice is either to configure these things as code or to disable JCasC configuration for it.

**Comment by huasipango** [comment]
> or to disable JCasC configuration for it.

@torstenwalter How to do that? Changing `controller.JCasC.defaultConfig: true` to `false`?
I have a running helm-chart jenkins pod that I want to persist after restarting Jenkins.

**Comment by MCANMCAN** [comment]
> > or to disable JCasC configuration for it.
> 
> @torstenwalter How to do that? Changing `controller.JCasC.defaultConfig: true` to `false`? I have a running helm-chart jenkins pod that I want to persist after restarting Jenkins.

Did you solve this issue ?

**Comment by huasipango** [comment]
No, I didn't.

**Comment by MCANMCAN** [comment]
changing controller.JCasC.defaultConfig: true to false on the helm chart configuration solved my issue. Writing your own JCasC or disabling it are the solutions.
