### ISSUE TITLE
Agent pod has the nodeSelector: kubernetes.io/os=linux

### ISSUE THREAD

**Issue by nitro2003** [jenkinsci/helm-charts#239]
**Describe the bug**
Agent created by jenkins has the nodeSelector: kubernetes.io/os=linux
![image](https://user-images.githubusercontent.com/10734493/106397287-91698780-6447-11eb-98d2-42490e7bcc3a.png)
This node selector is neither configured in the values.yaml file nor in the pod template in the Jenkins UI.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:52:31Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:05:01Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
I've tried the following versions:
- latest (3.1.5)
- 3.0.0
- 2.19.0

**What happened**:
A pod is stuck at pending state because of the nodeSelector

**What you expected to happen**:
A pod is created and runs the job

**Anything else we need to know**:
The agent image is extended. The docker file is as follow:
Currently testing how to add dependencies to the agent image.
```
FROM jenkins/inbound-agent:4.6-1

USER root

RUN apt-get update && apt-get install -y curl jq

USER jenkins
```

I've tried changing the value of *nodeSelector* in the values file with "" or null but it still the same.

Any help would be appreciated, thanks!

**Comment by wmcdona89** [comment]
Set `nodeSelector` to `beta.kubernetes.io/os=linux` for kubernetes v1.11 or OpenShift v3.11

kubernetes plugin v1.26.0 started defaulting to `kubernetes.io/os=linux`

See https://github.com/jenkinsci/kubernetes-plugin#running-with-openshift-3

**Comment by nitro2003** [comment]
Hi @wmcdona89 

Thanks for your response! 
Is there anyway to just remove any nodeSelectors or is that the way to do it?

**Comment by wmcdona89** [comment]
You have to override the default value.

**Comment by nitro2003** [comment]
Thank you so much @wmcdona89.
This is now working for me!
