### ISSUE TITLE
[improvement] - Add option to add scriptapproval hashes value on helm chart

### ISSUE THREAD

**Issue by ricardojdsilva87** [jenkinsci/helm-charts#24]
Migrating from https://github.com/helm/charts/issues/23265 like requested

Hello this would be a request for improvement,

We currently are running Jenkins with no persistent storage, with everything configured via CASC.
We have a few script that need to be approved at startup to be used right away. Thing here is even though the scripts are declared in the **scriptApproval** helm value, after every deployment the script asks to be approved again.

Doing some tests I've checked that the **approvedSignatures** xml tag is not as important as the **approvedScriptHashes**. 
After every manual approval I've noticed that the hash is always the same (if the script doesn't change). Implementing this feature would bring more benefits than having just the **approvedSignatures** in place

The file where is set:
https://github.com/helm/charts/blob/master/stable/jenkins/templates/config.yaml#L129

Having something like the following would help alot:

![image](https://user-images.githubusercontent.com/12953702/88262412-0bae9780-ccc0-11ea-8c25-baf7f2a7513b.png)

This way every script approval could be managed directly under the Values file.
Thank you for the help

**Comment by torstenwalter** [comment]
Do you know if we could configure script approvals via [JCasC](https://github.com/jenkinsci/configuration-as-code-plugin).
If so then I would prefer to configure it with that as we plan to remove all xml configuration (#10).

You can test that already if you configure it via `configScripts` like the example below:

```
master:
  JCasC:
    enabled: true
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our CI\CD server.
```

**Comment by ricardojdsilva87** [comment]
@torstenwalter, not sure if you can create the xml file using the CASC feature, since the scriptApproval.xml file is built during the deployment, I'm not sure if it would be overwritten

**Comment by torstenwalter** [comment]
I haven't tried it, but it looks quite promising.


https://github.com/jenkinsci/script-security-plugin/pull/233#issuecomment-612590623

> For anybody searching current working configuration is under security. See here.
> 
> security:
>   scriptApproval:
>     approvedSignatures:
>     - method java.net.URI getHost
> And it works for me on Jenkins 2.190, casc plugin 1.36 and Script Security plugin 1.68.

@ricardoespsanto Could you verify if that works? If so then it would be useful to document it.

**Comment by jfrabaute** [comment]
Hi,

Here is a PR which might be related to this: https://github.com/jenkinsci/helm-charts/pull/105

**Comment by torstenwalter** [comment]
#105 actually closes this ;-)

**Comment by ofir-elementor** [comment]
please open this there is no option to add  `approvedScriptHashes`

**Comment by chenshap** [comment]
did you find a resolution for approvedScriptHashes?

**Comment by davidreis97** [comment]
@torstenwalter #105 does not close this issue, as this issue relates to the `approvedScriptHashes` field and #105 only enables the `scriptApproval` field.
