### ISSUE TITLE
Naming Style in jcasc-config.yaml

### ISSUE THREAD

**Issue by jayfo** [jenkinsci/helm-charts#240]
**Describe the bug**:

Most of the chart avoids using `jenkins` in naming, following a pattern like:

```console
name: {{ template "jenkins.fullname" . }}-agent
```

`jcasc-config.yaml` and associated code uses `jenkins-config`. In the common case where `fullname` is `jenkins`, this results in many names that follow an unfortunate pattern of `jenkins-jenkins-*`. For example:

```console
# Source: jenkins/charts/jenkins/templates/jcasc-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jenkins-jcasc-config
  namespace: jenkins
  labels:
    "app.kubernetes.io/name": jenkins
    "helm.sh/chart": "jenkins-3.1.3"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "jenkins"
    "app.kubernetes.io/component": "jenkins-controller"
    jenkins-jenkins-config: "true"
```

**Which version of the chart**:

3.1.5

**Anything else we need to know**:

This does not break anything, it just seems out-of-style. My environment is separately creating configurations to be loaded by the Jenkins instance created in this chart, so the `jenkins-jenkins-*` naming pattern is escaping from this chart into my charts.

Is this something where a fix would be considered? 

It is an internal implementation detail, so I am not sure whether you would consider a change here to be a breaking change.

**Comment by torstenwalter** [comment]
How about extracting that name into a template? In addition you could introduce a variable to follow the existing naming schema or the one proposed from you as new naming?

That way you would not break anything in the chart, but still allow people to opt-in to the new naming? In the next major release we could make the new naming style the default by switching a single default.

**Comment by jayfo** [comment]
Makes perfect sense.

I can manage this in my charts, and will obviously defer on whether you want to leave this open as a future fix.

**Comment by torstenwalter** [comment]
@jayfo You could also create a PR which does the above mentioned thing in this chart. I am happy to review and provide guidance.

**Comment by jayfo** [comment]
Oh right, I misunderstood. Happy to keep this open and try that. Not sure on schedule.
