### ISSUE TITLE
Not found: "jenkins-home" when adding volumes in Persistence.volumes

### ISSUE THREAD

**Issue by RamanVaskevich1984** [jenkinsci/helm-charts#244]
**Describe the bug**
On EKS cluster there is a new Jenkins instance created with default Persistence settings (Persistence.enabled). Then there is a need to attach a volume with Jenkins backup. The volume type is persistentVolumeClaim which point to manually created PV and PVC. Here is a .yaml file content with custom values for this:

> persistence:
  volumes:
    - name: jenkins-home-bu
      persistentVolumeClaim:
        claimName: test-jenkins-pv
  mounts:
    - mountPath: /var/jenkins_home_bu
      name: jenkins-home-bu
      readOnly: false

After running `helm_release` terraform resource apply default PV and PVC are deleted and there is an error `Not found: "jenkins-home"`, `persistentvolumeclaim "test-jenkins" not found`

**Version of Helm and Kubernetes**:

Helm Version: 1.2.0
helm provider for terraform is used
```console
$ helm version
please put the output of it here
```

Kubernetes Version: 1.18 (EKS)

```console
$ kubectl version
please put the output of it here
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:52:40Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
3.1.2

**What happened**:
persistentvolumeclaim "test-jenkins" not found. Default PV and PVC which were attached to new Jenkins instance deleted.

**What you expected to happen**:
Additional volume `jenkins-home-bu` created and mounted to `jenkins` container

**How to reproduce it** (as minimally and precisely as possible):
run helm_release with terraform 12

**Anything else we need to know**:

**Comment by RamanVaskevich1984** [comment]
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/home-pvc.yaml#L1 should not contain `jenkins-home` in volume name

**Comment by RamanVaskevich1984** [comment]
please close issue

**Comment by hazzik** [comment]
@RamanVaskevich1984 you can close issue yourself.

**Comment by RamanVaskevich1984** [comment]
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/home-pvc.yaml#L1 should not contain jenkins-home in volume name
