### ISSUE TITLE
canonical way to use an init container to install a custom tool?

### ISSUE THREAD

**Issue by jstrachan** [jenkinsci/helm-charts#245]
**Is your feature request related to a problem? Please describe.**

I'd like a canonical way to install general purpose tools in Jenkins via the helm chart which does not require wrapping up the tool inside a Jenkins plugin. I don't see any way with JCasC or the helm chart to do that.

**Describe the solution you'd like**

Have an EmptyDir folder (say `/tools`) which can be shared via an init-container so that the init container can install shared tools such as terraform / kubectl / jx /whatever and have them available for use inside pipelines. Then allow `/tools/bin` to be added to the `$PATH`

**Describe alternatives you've considered**

The only alternative I can see - unless anyone has any good ideas - is creating a custom jenkins plugin which seems overly complex when its very easy to download + install binaries on the file system via existing k8s mechanisms.

I don't see a place to put binaries on the existing EmptyDir so they would be picked up as the `$PATH` for pipelines either; so wonder if the `$PATH` needs changing?

e.g. we could add a `/tools` folder mounted to an EmptyDir volume in the main chart and then init containers could install additional tools into the tools folder - then adding the actual binaries to `/tools/bin` (either copying or symlink)

**Additional context**

FWIW Tekton uses a similar approach to allow init containers to copy binaries into the main container (or pipeline steps). Might be nice to have something similar in the jenkins helm chart

**Comment by jstrachan** [comment]
I'm gonna close this as we should probably assume that all tools are provided by container images and folks should use the kubernetes plugin now

**Comment by torstenwalter** [comment]
You can just use a container with the tools you need.
