### ISSUE TITLE
V3.x does not work for K8S version 1.15.x 

### ISSUE THREAD

**Issue by dex80526** [jenkinsci/helm-charts#246]
**Describe the bug**

Version 3.x removes the conditional check for K8S version in supporting "startupProb". "startupProb" requires K8S 1.16+. Hence, the version 3.x chart does not work on K8S version 1.15 or earlier.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:42:56Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
v.3.0.10

**What happened**:
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0]): unknown field "startupProbe" in io.k8s.api.core.v1.Container
helm.go:81: [debug] error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0]): unknown field "startupProbe" in io.k8s.api.core.v1.Container

**What you expected to happen**:
No error

**How to reproduce it** (as minimally and precisely as possible):
Run the following command: ```
helm install jenkins jenkinsci/jenkins  --dry-run --debug --namespace=jenkins --version=3.0.10

**Anything else we need to know**:

**Comment by nareshnayini** [comment]
Any thoughts on when this would be fixed ? Getting the same error as our cluster version is 1.15.x.

**Comment by torstenwalter** [comment]
Unless you file a PR for it I would not expect a fix soon. If you check the CI pipeline the oldest version tested is 1.16 https://github.com/jenkinsci/helm-charts/blob/main/.github/workflows/lint-test.yaml#L13-L17

![image](https://user-images.githubusercontent.com/1743774/112060375-69e88e80-8b5d-11eb-858e-040d480369b1.png)
1.15 is already out of support: https://en.wikipedia.org/wiki/Kubernetes
