### ISSUE TITLE
[BUG] Incorrect indentation, blocks normal usage of javaOps

### ISSUE THREAD

**Issue by akaRem** [jenkinsci/helm-charts#25]
**Describe the bug**
Here https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml#L187 
you have a space inside "if" block which introduces extra indentation

if in variables

```
...
  javaOpts: >
    -server -XX:+AlwaysPreTouch    
    -Xloggc:$JENKINS_HOME/gc-%t.log   
    -XX:NumberOfGCLogFiles=5
...
```
then it will create something like 
```
...
            - name: JAVA_OPTS
              value: >
                -server -XX:+AlwaysPreTouch    
                -Xloggc:$JENKINS_HOME/gc-%t.log   
                -XX:NumberOfGCLogFiles=5                
                 -Dcasc.reload.token=$(POD_NAME)
```
which can't be parsed

possible workaround:

```
...
  # THE LEADING SPACE IS IMPORTANT!
  javaOpts: " -server -XX:+AlwaysPreTouch -Xloggc:$JENKINS_HOME/gc-%t.log -XX:NumberOfGCLogFiles=5"
...
```

Which makes it ugly and unmanageable with 15+ java opts

**Version of Helm and Kubernetes**:

**Which chart**:
stable/jenkins starting from 1.8.0

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
provide any java opts

**Anything else we need to know**:

**Comment by torstenwalter** [comment]
@akaRem Thanks for catching this! Would you like to create a PR for it?
Something like this could work.

```
{{- if .Values.master.sidecars.configAutoReload.enabled }}
-Dcasc.reload.token=$(POD_NAME)
{{- end }}
```

**Comment by akaRem** [comment]
@torstenwalter Could you please just commit the fragment you posted here?

**Comment by akaRem** [comment]
Any update on this?

**Comment by akaRem** [comment]
Any update on this?

**Comment by torstenwalter** [comment]
I did not find the time to do it. If you created a PR for it it would be easier to approve.

PS: I am not affiliated with cloudbees in any way and doing this in my spare time.

**Comment by scottrigby** [comment]
@akaRem this is now how contributions work. See https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#how-to-contribute
