### ISSUE TITLE
controller.customVolumes option

### ISSUE THREAD

**Issue by realrill** [jenkinsci/helm-charts#256]
**Is your feature request related to a problem? Please describe.**
I have the use-case of restoring backup of Jenkins without using `persistent` option.
This is because I use customInitContainer to populate/maintain secrets for Jenkins at spin-up time.
I use [SOPS](https://github.com/mozilla/sops) for this with `sops-alpine` image.
My script relies on placeholders in Jenkins' XML files -before parsing and copying them to the necessary locations-, so Persistent volume could cause conflicts as well as huge challenge to me.

**Describe the solution you'd like**
`controller.customVolumes: []` option in the values.yaml

**Describe alternatives you've considered**
Short on alternatives

**Additional context**
WIth customVolumes option to  the controller statefulset, I could leverage configmaps for bash and  other advanced  scripts. I'd able to mount these configmaps/secrets to the customInitContainers to make customInitContainer maintenance and experience much better.

**Comment by hazzik** [comment]
Does this work for you?

```
persistence:
  volumes:
  - name: my_volume
    emptyDir: {}
  mounts:
  - name: my_volume
    mountPath: "/whatever"
```

**Comment by realrill** [comment]
Hi @hazzik,
Haven't tried this. Will do as soon as I can spend time on this again. Don't have ETA, but will keep this as priority. Thanks
