### ISSUE TITLE
Wrong redirect after login

### ISSUE THREAD

**Issue by TBFreaq** [jenkinsci/helm-charts#268]
**Describe the bug**
We're using Jenkins with an ingress, which is only accessible via VPN on Port 8080. We can reach the login page (jenkins.someurl.net:8080) without any problem, but after the login we get redirected to jenkins.someurl.net . Is there a way to fix this?

**Version of Helm and Kubernetes**:

Helm Version: 

```console
$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**: 3.1.10

**What happened**: Redirect after login to http://jenkins.someurl.net

**What you expected to happen**: Redirect after login to http://jenkins.someurl.net:8080

**Anything else we need to know**:
We're using two ingress controllers: one for internal services only (port 8080) and one for external services (port 443).

![Screenshot 2021-02-23 174125](https://user-images.githubusercontent.com/38905244/108876461-8648e800-75fe-11eb-95fa-66cb8dc71815.png)

**Comment by TBFreaq** [comment]
Ingress settings

`ingress:
    enabled: true
    paths: []
    apiVersion: "networking.k8s.io/v1"
    labels: {}
    annotations:
      kubernetes.io/ingress.class: nginx-internal
    hostName: "jenkins.someurl.net"
    tls: []`

**Comment by hazzik** [comment]
Try setting `controller.jenkinsUrl` to `http://jenkins.someurl.net:8080` it should work
