### ISSUE TITLE
Ability to install additional plugins on top of plugins included with controller.image

### ISSUE THREAD

**Issue by pashcan** [jenkinsci/helm-charts#278]
**Problem**
When using ephemeral Jenkins without any persistence, I have to download all the plugins and their dependencies every time I want to add new plugin to the mix. Alternatively, I have to create a custom controller image which includes every plugin I want to try out.

**Describe the solution you'd like**
I would like to use custom jenkins image with some base plugins already "baked-in" and have the ability to add other plugins via installPlugins or additionalPlugins.
For example, if I create and then use a custom controller.image which already has kubernetes, workflow-aggregator, git, configuration-as-code plugins and their dependencies, I would like to be able to add monitoring plugin and have it downloaded in addition to plugins from the image. 
```
jenkins: 
  controller:
    image: jenkins-that-already-has-some-plugins
    installPlugins:
      - monitoring
```

**Describe alternatives you've considered**
I tried setting controller.overwritePluginsFromImage and overwritePlugins while providing plugins via installPlugins. Regardless of what I use for those, only plugins listed under installPlugins get downloaded and plugins from the image are no longer available when Jenkins starts.

**Comment by hazzik** [comment]
It seems you need to set  `controller.overwritePluginsFromImage` to `true`.

**Comment by hazzik** [comment]
It seems you need to set  `controller.overwritePluginsFromImage` to `false`.

**Comment by pashcan** [comment]
Thanks for the suggestion and I've tried it before posting with both values for `overwritePluginsFromImage`. The VALUES_SUMMARY ("Keep plugins that are already installed in the controller image.") and inline comment in values.yaml ("Configures if plugins bundled with `controller.image` should be overwritten with the values of 'controller.installPlugins' on upgrade or redeployment.") have somewhat contradicting wording so I had to try both. If I get around to providing logs from init container where plugins get installed, I can change this to a bug instead of enhancement.

**Comment by pashcan** [comment]
Could it be that I need persistence enabled for `overwritePluginsFromImage` set to `false` to be effective?

**Comment by pashcan** [comment]
Enabling persistence help but not for the right reason - plugins from the image simply stay installed unless I configure `overwritePlugins: true`.
This portion in templates/jenkins-controller-statefulset.yaml is the only mention of overwritePluginsFromImage:
```
          volumeMounts:
            - mountPath: {{ .Values.controller.jenkinsHome }}
              name: jenkins-home
              {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
              {{- end }}
            - mountPath: /var/jenkins_config
              name: jenkins-config
            {{- if .Values.controller.installPlugins }}
            {{- if .Values.controller.overwritePluginsFromImage }}
            - mountPath: {{ .Values.controller.jenkinsRef }}/plugins
              name: plugins
            {{- end }}
            - mountPath: /var/jenkins_plugins
              name: plugin-dir
            {{- end }}
```
When I set `overwritePluginsFromImage: false` the contents of /usr/share/jenkins/ref/plugins still get overwriten with plugins from installPlugins section instead of the ones from my custom jenkins image. It's looking more like a bug :(
