### ISSUE TITLE
JCasC ConfigMap does not scale - Too long: must have at most 262144 characters

### ISSUE THREAD

**Issue by abdennour** [jenkinsci/helm-charts#280]
**Describe the bug**
the configmap become bigger by time as it holds all configuration namely when `.Values.controller.sidecars.configAutoReload` is false
After sometimes, we ended up with this error message: 

```console
metadata.annotations: Too long: must have at most 262144 characters
```
`k create .. `/`k replace ...` can overcome the issue, however, we don't want to break the idempotency.

**Version of Helm and Kubernetes**:

Helm Version: 

```console
$ helm version
v3.2.4
```

Kubernetes Version:

```console
$ kubectl version
v1.17.4 8d8aa39
```

**Which version of the chart**: `3.1.11`

**Suggested Fix**

- Simply, keep multi configmaps even when `.Values.controller.sidecars.configAutoReload` is False.. just like the current behavior when `.Values.controller.sidecars.configAutoReload` is true.

- Alternatively, I suggest to fetch these configurations (namely config-as-code) from a git repository.
I know that [this is deprecated](https://kubernetes.io/docs/concepts/storage/volumes/#gitrepo) but think about something similar like initContainer.. so on.

**Comment by torstenwalter** [comment]
You can put your configurations easily into different ConfigMaps if you want.

**Comment by abdennour** [comment]
Sorry !  i was saying  `.Values.controller.JCasC.enabled` but i meant `controller.sidecars.configAutoReload`.
I updated the issue

--

So , @torstenwalter  this is not possible when `.Values.controller.sidecars.configAutoReload` is false.

Actually, i noticed that this helm chart created multiple configmap for each config-as-code block only when `.Values.controller.sidecars.configAutoReload` is true.
However,
