### ISSUE TITLE
Jenkins plugins download failing behind http proxy in the init container

### ISSUE THREAD

**Issue by longc** [jenkinsci/helm-charts#293]
**Describe the bug**
Jenkins plugins download failing behind http proxy in the init container, there is no javaOpts option to be specified in the plugin download process, which runs as: 
```
java -jar /usr/lib/jenkins-plugin-manager.jar --war /usr/share/jenkins/jenkins.war --plugin-file /var/jenkins_home/plugins.txt
```

**Version of Helm and Kubernetes**:

Helm Version: 3.5.3

Kubernetes Version: 1.16.15

**Which version of the chart**: 3.2.4

**What happened**:
Error occurs in Jenkins init stage, the Jenkins plugins download process timed out in the init container.
```
NAME            READY   STATUS     RESTARTS   AGE
testjenkins-0   0/2     Init:0/1   0          92s
testjenkins-0   0/2     Init:Error   0          2m33s
```

**What you expected to happen**:
If you run the process manually with the proxy setting inside the init container, it is working.
```
$ kubectl exec -it testjenkins-0  -c init -- sh
$ java -Dhttp.proxyHost=<proxy_host> -Dhttp.proxyPort=<proxy_port> -Dhttps.proxyHost=<proxy_host> -Dhttps.proxyPort=<proxy_port> -jar /usr/lib/jenk
ins-plugin-manager.jar --war /usr/share/jenkins/jenkins.war --plugin-file /var/jenkins_home/plugins.txt
Done
```

**How to reproduce it** (as minimally and precisely as possible):

```
helm upgrade testjenkins jenkins/jenkins \
  --install \
  --atomic \
  --wait \
  --timeout 5m \
  --version 3.2.4 \
  --set controller.tag=2.283-alpine \
  --set controller.initContainerEnv[0].name=http_proxy,controller.initContainerEnv[0].value="http://<proxy_host>:<proxy_port>",controller.initContainerEnv[1].name=https_proxy,controller.initContainerEnv[1].value="http://<proxy_host>:<proxy_port>" \
  --set controller.containerEnv[0].name=http_proxy,controller.containerEnv[0].value="http://<proxy_host>:<proxy_port>",controller.containerEnv[1].name=https_proxy,controller.containerEnv[1].value="<proxy_host>:<proxy_port>" \
  --set controller.javaOpts="-Dhttp.proxyHost=<proxy_host> -Dhttp.proxyPort=<proxy_port> -Dhttps.proxyHost=<proxy_host> -Dhttps.proxyPort=<proxy_port>" \
  --set controller.serviceType=ClusterIP \
  --set controller.overwritePlugins=true \
  --values "jenkins_plugins.yaml"
```

jenkins_plugins.yaml
```
controller:
  installPlugins:
    - ace-editor:1.1
    - ansicolor:0.7.5
    - ant:1.11
    - antisamy-markup-formatter:2.1
    - apache-httpcomponents-client-4-api:4.5.13-1.0
    - authentication-tokens:1.4
    - authorize-project:1.3.0
```

**Anything else we need to know**:

**Comment by pashcan** [comment]
We had the same issue few months ago. Thanks to [this PR](https://github.com/jenkinsci/docker/pull/1025) for the Jenkins docker image, we were able to add proxies via JAVA_OPTS specified under initContainerEnv section:
```
jenkins:
  controller:
    initContainerEnv:
      - name: JAVA_OPTS
        value: "-Dhttps.proxyHost="
```
It also looks like this specific issue is documented in the documentation for this helm chart: https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins#running-behind-a-forward-proxy

**Comment by longc** [comment]
That will fix the issue, thanks.

**Comment by longc** [comment]
@pashcan Thanks for fixing this issue, but the documentation is not quite accurate and needs to be updated, in the values file,  a good example for the http proxy in the init container will be like the following:
```
initContainerEnv:
  - name: JAVA_OPTS
    value: "-Dhttp.proxyHost=<proxy_host> -Dhttp.proxyPort=<proxy_port> -Dhttps.proxyHost=<proxy_host> -Dhttps.proxyPort=<proxy_port>"
```

**Comment by pashcan** [comment]
@longc I am also adding them the way you've listed.
Have you already tried the format from the docs? Seems somewhat more legible (as long as it works :smile: ).
```
controller:
  javaOpts: >-
    -Dhttp.proxyHost=192.168.64.1
```

**Comment by vanlongme** [comment]
I have same issue, already set both javaOpts and env like: https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins#running-behind-a-forward-proxy.
But from squid proxy logs, I did not see initContainer connect to my proxy
