### ISSUE TITLE
document how an ingress can be configured

### ISSUE THREAD

**Issue by torstenwalter** [jenkinsci/helm-charts#31]
maybe even more import, which values can be used to configure external URL

jenkins.url template is defined in:

https://github.com/jenkinsci/helm-charts/blob/91a2a39971d62861e3b1bba8832ddb12fbe25249/charts/jenkins/templates/_helpers.tpl#L51-L68

That should give you an idea which values you can set to configure it.

This template is then used to configure it via JCasC:
https://github.com/jenkinsci/helm-charts/blob/91a2a39971d62861e3b1bba8832ddb12fbe25249/charts/jenkins/templates/_helpers.tpl#L159-L163

**Comment by 11000100111000** [comment]
Since I'm configuring that soon on my instance i might as well write some documentation ^^
Where do we put documentation of these things?

**Comment by torstenwalter** [comment]
You can put it directly in the README. That way it will also show up in Artifacthub.

**Comment by 11000100111000** [comment]
I've created a merge request :) Is the documentation alright?
