### ISSUE TITLE
spec.replicas value configurable for multiple Jenkins masters

### ISSUE THREAD

**Issue by cheungaryk** [jenkinsci/helm-charts#313]
**Is your feature request related to a problem? Please describe.**
I want to deploy a highly-available Jenkins instance will multiple masters using AWS EFS as the backend, however, I see that in the [jenkins-controller-statefulset.yaml](https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/jenkins-controller-statefulset.yaml), the value of `spec.replicas` is hardcoded as 1. My attempt to do a Github issues/internet search yielded no results (which sounds to me that no one tried, or wanted to try it), so I figured that I will raise a feature request here. If there is a reason why it is hardcoded (e.g. ease of maintenance) or if I should try other methods, I am happy to be educated on the topic.

**Describe the solution you'd like**
make the `spec.replicas` value configurable in the values yaml. Some additional logic changes around the `persistence` block as well (e.g. `accessMode`).

**Describe alternatives you've considered**
I have considered using manifests instead of the helm chart, or fetching the helm chart locally to create our own version. My personal preference would be to use the community chart though 😃 

**Additional context**
N/A

**Comment by torstenwalter** [comment]
Jenkins does not support running multiple instances reading/writing to the same volume. Not even considering if and how good this is supported by plugins.
Closing this issue as it's nothing which can be solved by the helm chart.

**Comment by cheungaryk** [comment]
thanks for the quick reply!

**Comment by karanjain71** [comment]
Hi @torstenwalter,

I was facing this issue and just tried to update the replica value to 2. But Jenkins was not working as expected.

Can you please tell why this is happening with Jenkins as there are many stateful applications that run like this where states are there and use stateful sets.

Also, why plugins cannot support it is a question I am wondering. Just wanted to dive down in how Jenkins is originally configured.

**Comment by torstenwalter** [comment]
Jenkins does not support running multiple servers. To my knowledge it does not support it when running outside of Kubernetes, so there is nothing a Kubernetes configuration could do to fix this.
