### ISSUE TITLE
Update Jenkins to v2.282

### ISSUE THREAD

**Issue by mcandre** [jenkinsci/helm-charts#343]
**Is your feature request related to a problem? Please describe.**

Bugfixes for the SSH Credentials plugin are unable to uninstall without a new version of Jenkins, at least Jenkins 2.282. Whereas the Helm chart currently targets Jenkins 2.277.3.

**Describe the solution you'd like**

Update Jenkins to at least v2.282.

**Comment by torstenwalter** [comment]
Helm chart is following Jenkins LTS releases. If you want/need something you can just specify a different image via values.yaml.
