### ISSUE TITLE
Broken pipes when port forwarding

### ISSUE THREAD

**Issue by mcandre** [jenkinsci/helm-charts#353]
**Describe the bug**

`kubectl port-forward` keeps losing the connection all the time. This results in the Jenkins Web UI becoming unresponsive for around 40% of clicks.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:

master

**What happened**:

The Jenkins Web UI is very slow. The port forward experiences timeouts and broken pipes.

I have to use multiple workarounds all the time:

* Jenkins Web UI: Right-click, open links in new browser tab (40% of clicks).
* Disconnect and reconnect the port forward (several times a minute).

**What you expected to happen**:

The Jenkins Web UI should be fast and the port forward should be reliable.

**How to reproduce it** (as minimally and precisely as possible):

1. Run `kubectl port-forward <jenkins-master-pod> 8080:8080`
2. Open `http://localhost:8080/` in a Web browser

**Comment by torstenwalter** [comment]
Why would you use port-forward for things other than testing?

**Comment by mcandre** [comment]
* Because this is a standard Kubernetes feature and one would expect it to work better.
* Before long term CNAMEs are provisioned.
* For emergency support.
