### ISSUE TITLE
Init container can't download plugins behind TLS-inspecting proxy

### ISSUE THREAD

**Issue by holmesb** [jenkinsci/helm-charts#386]
**Describe the bug**
Even with all of the [update center env vars](https://github.com/jenkinsci/docker/blob/3e494870bf5376f7066c19c2ef5b6bf71c44b7ca/README.md#setting-update-centers) pointing to http (not https) endpoints, the init container [still tries](https://gitter.im/jenkinsci/plugin-installation-manager-cli-tool?at=60b76b75bdecf719a093159e) to pull from http**s**://get.jenkins.io.  According to @timja, this is because the update center includes download links pointing to https://get.jenkins.io.  

Behind a TLS-inspecting proxy (which effectively does a man-in-the-middle attack), unless the proxy's CA cert is trusted, https endpoints cannot be reached.  The init container fails with errors such as "Downloaded file is not a valid ZIP", so Jenkins fails to start.

**Which version of the chart**:
latest as of 2nd June 2021

**Anything else we need to know**:
[Mounting ](https://github.com/jenkinsci/helm-charts/blob/330c61cebe3393b3d7fdd6216805338a59d4e7cd/charts/jenkins/templates/jenkins-controller-statefulset.yaml#L119)the [httpsKeyStore ](https://github.com/jenkinsci/helm-charts/blob/330c61cebe3393b3d7fdd6216805338a59d4e7cd/charts/jenkins/templates/jenkins-controller-statefulset.yaml#L215)in the init container, same as it is in the main jenkins container, fixes.  This allows java properties to be specified:
```
controller:
  initContainerEnv:
    - name: JAVA_OPTS
      value: >-
        -Djavax.net.ssl.trustStore=/var/jenkins_keystore/keystore.jks
        -Djavax.net.ssl.trustStorePassword=<password>
```
and the proxy's CA cert to be trusted.  I have validated this works and allows Jenkins to start.

The simplest way to mount the keystore in the init container is probably for the list of custom _.Values.persistence.mounts_ also to be mounted in init, which is how we mount the keystore for the main jenkins container.

**Comment by timja** [comment]
Can't you build it into your custom docker image?

**Comment by holmesb** [comment]
Can and probably will when I figure out how.  Especially since the new plugin-installation-manager-tool seems to take > 3 times longer to download the same set of plugins versus the old install-plugins.sh script.  Not an improvement IMO.  

Are you suggesting the vanilla jenkins docker image should remain broken for proxy users?  Would be nice to at least have the option of using it.

**Comment by timja** [comment]
It's not broken?

> https://github.com/jenkinsci/docker/blob/master/jenkins-plugin-cli.sh

JAVA_OPTS can be passed to it

**Comment by holmesb** [comment]
I'll qualify that: broken for tls-inspecting proxy users.  Many enterprises use these to be able to check https traffic for malware.  

JAVA_OPTS takes the proxy host and port.  Doesn't help pull-down plugins from https endpoints when the CA cert is untrusted.  Anyway, I'll create a PR.
