### ISSUE TITLE
v3.0.0 release

### ISSUE THREAD

**Issue by torstenwalter** [jenkinsci/helm-charts#41]
# How does a bigger v3.0.0 release help us

While working on #10 I had some ideas regarding v3.0.0 release of the helm chart.

Basically removing all XML configuration options is a breaking change and requires a major version increment.
As I'd love to avoid to do too many breaking changes updates in a row I thought it might be useful to combine several others with this one.

- removal of all XML configuration options
- upgrading to Helm version 3
  helm 3 is out for a while now and support for version 2 will formally end Nov 13, 2020. See https://helm.sh/blog/2019-10-22-helm-2150-released/#helm-2-support-plan for details.
  I think it also helps us to worry less about things like is a feature supported in a specific version of helm 2 as pointed out in #35 as we then can safely assume that people are using helm version 3
- remove values which are deprecated already
- other items which you think should be done as part of a v3 release.

My hope is that this will help us going forward in keeping the chart maintainable and also making it easier for users to use the chart as they have less config flags to worry about and making it easier for contributors as the chart gets less complex.

# How does it align with other plans

## Documentation

In my opinion we should have more documentation and provide in examples how settings can be used and which features this chart offers. I started to label some issues with [documentation](https://github.com/jenkinsci/helm-charts/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation). These are items which would be worth documenting so that other people don't have to ask again.

As I see it this could be done before or after a v3.0.0 release. Having more documentation always help. So it's totally fine to create PRs for it before a v3.0.0 release, but I think a lack thereof should also not block us from creating a release as outlined above. A less complex chart  also makes documentation easier.

## Replace deprecated terminology

@timja raised issue #11 to remove deprecated terminology and offensive terms. For me this absolutely makes sense. Most important are these changes:

- master => controller
- slave => agent

We are using them in `values.yaml` and reference them in the templates. Some values are also used as selectors. So this is for sure a breaking change. I would not start doing it before removing XML configuration options as that reduces the number of occurrences, which we have to replace.

We could do that change together with v3.0.0 or as a major release afterwards. Both would be ok for me, but I think that spilling it up makes it easier for users to migrate. And we could have that release sooner.
Hopefully we are able to make the change deprecating terminology shortly afterwards and the user just has to replace `master` key in `values.yaml` with `controller` and adjust a small set of other values. 

# How to put his into practice

@jenkinsci/helm-charts-developers I pushed my branch which removes the XML configuration option as https://github.com/jenkinsci/helm-charts/tree/jenkins-3-0-0 to this repository. I also made it protected and enforced PR reviews there. That way more people can contribute to that one and we can discuss PRs.

As a starting point I created a PR to migrate to helm 3 (#38)

@wmcdona89 If this procedure is fine with you I would close #34 in favor of #40.

@jenkinsci/helm-charts-developers I appreciate your feedback.

**Comment by timja** [comment]
Sounds reasonable to me.

I'm in favour of less major releases is better normally.

But it's probably better to split the changes out as otherwise people might never upgrade.

**Comment by wmcdona89** [comment]
@torstenwalter this all sounds good. I lean towards doing the terminology changes in v3 but I'm good either way.

have you given any thought to chart version linting on the 3.0.0 branch?
we could disable it (and then re-enable it at the end)...or we could use pre-release versions e.g. 3.0.0-beta.1
I used beta versions recently and it worked out well

**Comment by wmcdona89** [comment]
> we could disable it (and then re-enable it at the end)

looks like `--check-version-increment false` would disable the check
https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md

**Comment by torstenwalter** [comment]
> > we could disable it (and then re-enable it at the end)
> 
> looks like `--check-version-increment false` would disable the check
> https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md

This should not b necessary if you target the https://github.com/jenkinsci/helm-charts/tree/jenkins-3-0-0 branch as the checks are done against `main` branch and there is a version increment. We just need to merge `main` branch whenever there are changes.

**Comment by torstenwalter** [comment]
To give an update here. I think it's time to cut off a 3.0.0 release. Quite some improvements where made and the chart is way simpler then the current state.

- XML configuration was dropped
- offending terms have been removed
- values have been renamed and re-ordered to make it easier to use
- already deprecated items got removed
- chart migrated to helm 3.0.0

[Helm 2 is unsupported since 13th of November](https://helm.sh/blog/helm-2-becomes-unsupported/), so there is no reason to keep supporting Helm 2.


What I suggest to do next:

- stop accepting PRs for `main` as all those changes have to be ported to `jenkins-3-0-0` branch
  Only exception would be emergency changes e.g. if the chart can not be installed at all.
- merge latest changes from`main` into `jenkins-3-0-0`
- prepare a clean PR for 3.0.0
- review and test it
- create the release ;-)

What do I mean by creating a clean PR for 3.0.0? At the moment #40 is kind of a mess with many merges from `main` into it and also the DCO check does not pass. I would try to create a new PR, which contains all changes in a single commit on top of `main`. Of course I will add everybody, who contributed to it as Co-Author. Keeping the existing `jenkins-3-0-0` should make it easier to verify that the new commit and `jenkins-3-0-0` have the same content. As `jenkins-3-0-0` contains already reviewed increments that should help in reviewing the final PR.

@maorfr @mogaal @wmcdona89 @timja Hope this sounds reasonable. Do you see any missing pieces, which would need to go into 3.0.0?

The only thing which comes to my mind is to resolve the issue with the admin user.

**Comment by timja** [comment]
Sounds reasonable to me and yes it would be great to solve the admin user issue too

**Comment by timja** [comment]
@halkeye did you want to take a look?
