### ISSUE TITLE
Unable to deploy chart

### ISSUE THREAD

**Issue by NasAmin** [jenkinsci/helm-charts#423]
**Describe the bug**
Unable to to deploy the chart with the following command:
```
helm install jenkins jenkins/jenkins
```

I would expect the chart to just work out of the box but I am getting this error:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0]): unknown field "startupProbe" in io.k8s.api.core.v1.Container
````

I have an existing deployment from stable/jenkins which has been deprecated and I need to upgrade my deployment. Tried to switch to this chart but it doesn't even work with the default values file.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-eks-5817a6", GitCommit:"5817a6e720450eb7940e4f7827e06aaac0e36dea", GitTreeState:"clean", BuildDate:"2021-02-12T23:28:03Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

```

**Which version of the chart**:
latest version.
The stable/jenkins version currently installed is jenkins-1.9.16

**What happened**:
When deploying the chart with no customizations, I get the following error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0]): unknown field "startupProbe" in io.k8s.api.core.v1.Container
```

When I try to upgrade the existing chart with custom values for security realm etc, I get the following error:

```
Error: template: jenkins/templates/jcasc-config.yaml:43:8: executing "jenkins/templates/jcasc-config.yaml" at <include "jenkins.casc.defaults" .>: error calling include: template: jenkins/templates/_helpers.tpl:149:10: executing "jenkins.casc.defaults" at <include "jenkins.casc.podTemplate" .>: error calling include: template: jenkins/templates/_helpers.tpl:208:47: executing "jenkins.casc.podTemplate" at <"^$">: invalid value; expected string
```

**What you expected to happen**:
The chart to upgrade/install successfully.

**How to reproduce it** (as minimally and precisely as possible):
```
helm install jenkins-dev jenkins/jenkins --namespace=jenkins
```

I'll really appreciate if some guidance can be provided for this please.

**Comment by torstenwalter** [comment]
Your Kubernetes version is not supported:
`Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-eks-5817a6", GitCommit:"5817a6e720450eb7940e4f7827e06aaac0e36dea", GitTreeState:"clean", BuildDate:"2021-02-12T23:28:03Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}`

The oldest Kubernetes version this chart is tested against is 1.16 see https://github.com/jenkinsci/helm-charts/blob/26affd02465f7ef444967b0528142a6cd6b9642a/.github/workflows/lint-test.yaml#L13-L17.

I think `startupProbe` was added in Kubernetes 1.16 https://github.com/kubernetes/enhancements/issues/950

The probes are defined in https://github.com/jenkinsci/helm-charts/blob/26affd02465f7ef444967b0528142a6cd6b9642a/charts/jenkins/values.yaml#L132-L159:

So you could try to override it in your `custom-values.yaml` file.

**Comment by NasAmin** [comment]
That explains it @torstenwalter. Thanks very much for the response!

**Comment by torstenwalter** [comment]
You're welcome.
