### ISSUE TITLE
kubernetes cloud config is missing when restart jenkins

### ISSUE THREAD

**Issue by Henry-Kim-Youngwoo** [jenkinsci/helm-charts#424]
**Describe the bug**
After installing some plugins, after restart Jenkins, the global pod template and container templates are resetting by default
But other configurations about pipelines or credentials are still there, only cloud-config is missing

**Version of Helm and Kubernetes**:

Helm Version:
```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```
Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
**Which version of the chart**:
```
NAME   	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART         	APP VERSION
jenkins	jenkins  	1       	2021-06-08 15:19:38.730759 +0900 KST	deployed	jenkins-3.3.22	2.289.1
```
**What happened**:
cloud-config especially global pod templates are missing

**What you expected to happen**:
global pod templates should be the same after the restart

**How to reproduce it** (as minimally and precisely as possible):

```
helm repo add jenkins https://charts.jenkins.io
```
```
helm install -n jenkins jenkins jenkins/jenkins
```

**Anything else we need to know**:

**Comment by torstenwalter** [comment]
Cloud configuration is managed via JCasC see https://github.com/jenkinsci/helm-charts/blob/db14f30745362859827977492552c7c3f2aa48eb/charts/jenkins/templates/_helpers.tpl#L120-L168

So if you make manual changes there they will be overridden whenever configuration as code is applied as the `cloud` key is managed ma JCasC.

The best option would be to manage also you other cloud configuration as code. Than you can be sure that everything is there.
Other alternative would be to extend the chart to not manage the cloud settings at all. I would see that rather as a fallback option as most people use kubernetes agents.

**Comment by Henry-Kim-Youngwoo** [comment]
@torstenwalter thank you for response

**Comment by Henry-Kim-Youngwoo** [comment]
@torstenwalter thank you for your response
I'm not sure how it works
is that mean when I change configuration on GUI that config is overridden on the JCasC YAML file?
but when I check the YAML file like below there are no changes applied.
```
cat /var/jenkins_home/casc_configs/jcasc-default-config.yaml
```
is this normal?

**Comment by torstenwalter** [comment]
> that mean when I change configuration on GUI that config is overridden on the JCasC YAML file?

No. The file stays the same. That's exactly the problem. You make manual changes in the UI, which are not reflected in the config file. The next time the configuration is re-loaded from that file your manual settings are overwritten.

The content of that file can be configured via values of the chart. See https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/README.md#configuration-as-code

**Comment by torstenwalter** [comment]
The plugin has really good [documentation](https://github.com/jenkinsci/configuration-as-code-plugin) how everything works.
For a start you can make changes in the UI and try to export them to see how those settings could be reflected in a configuration file https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/configExport.md

**Comment by SirNeo** [comment]
I face the same problem since some weeks ago and I don't found a good solution. I make manual changes in the UI as create credentials, add roles, change pod templates and when I upgrade using helm chart, all config is reset. Also, if the pod is restarted too the config is reset.

**Comment by Henry-Kim-Youngwoo** [comment]
@torstenwalter Thank you for your kind explanation
I fully understand why the default config overwrite my manual changes
export config looks nice I can change chart config with that feature
