### ISSUE TITLE
Update using Helm Chart

### ISSUE THREAD

**Issue by sagaraspl** [jenkinsci/helm-charts#425]
**Describe the bug**

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.7", GitCommit:"bfb38f707bc4a8edfcd73472ec3d96b500b8b781", GitTreeState:"clean", BuildDate:"2020-08-12T20:27:48Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
jenkins-3.5.8

**What happened**:
When ever I will update chart using helm upgrade each time I am facing difficulties in plugin dependency and then I have to trial and error each time to solve that plugin dependency issue.
For e.g.
helm upgrade -n <namespace> jenkins <path/to/directory of chart/> --version 3.5.7

**What you expected to happen**:
I think whenever I upgrade using helm all plugin dependency should be fixed automatically.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by torstenwalter** [comment]
Any idea of how that could be solved?

The best option I see is building a custom image. Then all plugin dependency issues are resolved while building the image and there is no impact on users when updating Jenkins.

See https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/README.md#consider-using-a-custom-image and https://github.com/jenkinsci/docker#plugin-installation-manager-cli-preview

**Comment by sagaraspl** [comment]
Well, Yes we may try to see if building a custom image will help here or not. However how I have solved is like seeing errors on Jenkins like following...

kubectl -n <namespace> logs jenkins-master-test-0 jenkins

And based on that I put one by one plugin in installPlugin like this way

installPlugins:
      - kubernetes:1.29.4
      - workflow-aggregator:2.6
      - git:4.7.1
      - configuration-as-code:1.51
      **- junit:1.29
      - workflow-support:3.7
      - ace-editor:1.1
      - pipeline-model-api:1.7.2
      - workflow-job:2.39
      - credentials-binding:1.23**

As you can see that it is one way to fix using trial and errors but that isn't correct behavior right?

But I don't understand how custom image can help to solve this?

**Comment by torstenwalter** [comment]
This example uses the old installer
```
FROM jenkins/jenkins:2.289.2
ARG PLUGINS=plugins.txt
COPY ${PLUGINS} /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
```

In the plugins.txt I just specify the versions I need. So the installer will figure out which version work together.
In the helm chart I am disabling plugin installation altogether.

How does it solve the issue?
- I have no plugin dependency issue during deployment time.
- issues which arise because of plugin version and jenkins version not matching together are cached during image build time.

**Comment by sagaraspl** [comment]
Yes that seems to be a workaround of this situation.

I will try with custom image. Thanks
