### ISSUE TITLE
Unable to remove systemMessage via JCasC

### ISSUE THREAD

**Issue by pashcan** [jenkinsci/helm-charts#430]
**Describe the bug**
After I set systemMessage via JCasC, removing that section of the configuration does not remove the message.
The only way to remove the message is to set it to empty string via JCasC or to clear it via UI.

**Version of Helm and Kubernetes**:

Helm Version: version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

Kubernetes Version: 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

**Which version of the chart**:
Happens in 3.3.22 & 3.5.7

**What happened**:

I am able to set systemMessage via values.yaml:
```yaml
jenkins:
  controller:
    JCasC:
      configScripts:
        message: |
          jenkins:
            systemMessage: Testing systemMessage.
```
I see it reflected in UI, inside config.xml and there is a ./casc_configs/message.yaml file. I also see the change propagating via config-reload container:
```
[2021-08-04 15:10:53] Working on configmap sandbox-jenkins/sandbox-jenkins-jenkins-config-message
[2021-08-04 15:10:53] File in configmap message.yaml MODIFIED
[2021-08-04 15:10:55] POST request sent to http://localhost:8080/reload-configuration-as-code/?casc-reload-token=sandbox-jenkins-0. Response: 200 OK
```
When I remove message section from JCasC, the configmap in the namespace is updated, the yaml file is removed from casc-configs directory and the change shows up in config-reload container:
```
[2021-08-04 15:16:50] Working on configmap sandbox-jenkins/sandbox-jenkins-jenkins-config-message
[2021-08-04 15:16:50] File in configmap message.yaml MODIFIED
[2021-08-04 15:16:50] Contents of message.yaml haven't changed. Not overwriting existing file
[2021-08-04 15:16:52] Working on configmap sandbox-jenkins/sandbox-jenkins-jenkins-config-message
[2021-08-04 15:16:52] File in configmap message.yaml DELETED
[2021-08-04 15:16:53] POST request sent to http://localhost:8080/reload-configuration-as-code/?casc-reload-token=sandbox-jenkins-0. Response: 200 OK
```
However, it does not get removed from UI nor config.xml.
Using `Reload existing configuration` action on <jenkins-url>/configuration-as-code/ doesn't not remove it. Removing the pod doesn't remove it since we have persistence enabled.

**What you expected to happen**:

Removing explicit configuration from JCasC should remove it from the resulting Jenkins.

**How to reproduce it** (as minimally and precisely as possible):
In values.yaml set:
```yaml
jenkins:
  controller:
    JCasC:
      configScripts:
        message: |
          jenkins:
            systemMessage: Testing systemMessage.
```
Watch it appear in UI. Then remove that section of JCasC.

**Comment by torstenwalter** [comment]
That's as designed. JCasC only configures settings where a key is present in the yaml configuration.


So if you remove a key it will not be emptied. Only if you set it to an empty value it will have an effect.
Defaults for the chart follow this approach. So we rather not configure an empty `systemMessage` by default as it would overwrite a system message if a user had configured one manually.

**Comment by pashcan** [comment]
Alright. Thanks for clarifying @torstenwalter.
My workaround was to use an empty systemMessage to clear it and then remove it from JCasC section altogether.
