### ISSUE TITLE
issue title

### ISSUE THREAD

**Issue by shakenfr** [jenkinsci/helm-charts#439]
Hello,

not a bug but an advised I need.

When I installed this jenkins chart, after I create a job using git as version controlled. To access my job repo script, I have to create an access token credential into jenkins. After it works. But if I reinstall the jenkins chart my token credential is not crypted because probably the master.key change each time I installed jenkins chart.
Is it possible to fix this key to be sure having each time the same token to use git controlled jobs ?

best

bruno

**Comment by torstenwalter** [comment]
The best option is to configure credentials via configuration as code plugin https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc or to use [Kubernetes Crendentials Provider](https://plugins.jenkins.io/kubernetes-credentials-provider/)
