### ISSUE TITLE
Add secondary ingress to allow webhooks to be public

### ISSUE THREAD

**Issue by halkeye** [jenkinsci/helm-charts#44]
**Is your feature request related to a problem? Please describe.**
We have various jenkins installation that contain sensitive data, and thus hidden behind firewalls, but still would like github notifications

**Describe the solution you'd like**
Add a secondary ingress that just exposes the webhook urls (github-webhook/bitbucket-webhook/etc)

**Describe alternatives you've considered**
Could use a sidecar container that starts up smee, but thats an extra dependancyan

**Comment by torstenwalter** [comment]
That's a good idea. We are actually doing something like this in our setup.

Would you like to submit a PR for that?

**Comment by halkeye** [comment]
If i get to it sure, but totally up for others to contribute too. I think its a decent newbie friendly issue (I'm practicing labeling before hacktober next month)

**Comment by torstenwalter** [comment]
> If i get to it sure, but totally up for others to contribute too. I think its a decent newbie friendly issue (I'm practicing labeling before hacktober next month)

Do you have a convention which label should be used for newbie friendly issues?

**Comment by halkeye** [comment]
"good first issue" is usually the convention. the standard labels should be on new repos, so you should have it.
