### ISSUE TITLE
Plugin issues in the latest version of helm chart

### ISSUE THREAD

**Issue by rmkanda** [jenkinsci/helm-charts#442]
Chart Version: 3.5.12
App Version: 2.289.3

When installing the latest version of helm chart, I am seeing the following errors in the Jenkins UI.
Is this anything related to our helm chart plugins included and its versions?

![image](https://user-images.githubusercontent.com/38713281/130626675-df0b050b-1453-4bcb-af1b-de3ca8c06cbc.png)

**Comment by rmkanda** [comment]
@timja @torstenwalter Any thoughts?

**Comment by timja** [comment]
what values are you passing?

**Comment by rmkanda** [comment]
@timja I am not passing any values. Just doing `helm install jenkins jenkins/jenkins`

**Comment by rmkanda** [comment]
Tried to fetch the plugin info, 
*After Install*
[initial-plugins-json.txt](https://github.com/jenkinsci/helm-charts/files/7043436/initial-plugins-json.txt)
[initial-plugins.txt](https://github.com/jenkinsci/helm-charts/files/7043437/initial-plugins.txt)

*After correcting the above issues manually from Plugin UI*
[plugins-json-after-update.txt](https://github.com/jenkinsci/helm-charts/files/7043433/plugins-json-after-update.txt)
[plugins-after-update.txt](https://github.com/jenkinsci/helm-charts/files/7043438/plugins-after-update.txt)

Not sure this issue belongs to helm chart, whether updating the plugin versions in helm charts will solve this OR we need to make changes in Jenkins itself.

**Comment by timja** [comment]
It normally fixes itself if we update these to the latest version:
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml#L220-L224

(and the corresponding tests, basically search the repo for the strings)

**Comment by torstenwalter** [comment]
@rmkanda thank you for reporting this. I mainly use pre built docker images and therefor did not encounter the issue myself. I also thought that just updating the required plugins to the latest versions would solve it, but unfortunately that was not enough.

You can check the related PR for how to solve it by adjusting a value or just wait until it's reviewed and merged.

**Comment by rmkanda** [comment]
Thanks @torstenwalter for looking into the issue. I will try with your changes and check the result...
