### ISSUE TITLE
Getting many plugin load errors

### ISSUE THREAD

**Issue by mcandre** [jenkinsci/helm-charts#460]
The latest chart release fails to spin up due to dozens of plugin load errors.

As a workaround, I am specifying the following plugin pins:

```yaml
  installPlugins:
    - "ace-editor:1.1"
    - "aws-credentials:1.30"
    - "configuration-as-code:1.52"
    - "docker-workflow:1.26"
    - "git:4.8.2"
    - "git-parameter:0.9.13"
    - "kubernetes:1.30.1"
    - "lockable-resources:2.11"
    - "oic-auth:1.8"
    - "pipeline-graph-analysis:1.11"
    - "pipeline-model-declarative-agent:1.1.1"
    - "pipeline-model-definition:1.9.1"
    - "pipeline-model-extensions:1.9.1"
    - "pipeline-rest-api:2.19"
    - "pipeline-stage-view:2.19"
    - "role-strategy:3.2.0"
    - "ssh-agent:1.23"
    - "workflow-aggregator:2.6"
    - "workflow-cps:2.93"
    - "workflow-cps-global-lib:2.21"
    - "workflow-durable-task-step:2.39"
    - "workflow-multibranch:2.26"
    - "workflow-support:3.8"
```

**Comment by pashcan** [comment]
Even without seeing your error log, I can easily guess the issue is dependencies related. Your best bet is to [use a custom image](https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins#consider-using-a-custom-image).

**Comment by torstenwalter** [comment]
Update bundled dependencies one more with #525, but as @pashcan suggestes the best option is tu use a custome image and bundle specific plugin versions.
