### ISSUE TITLE
Stronger validation for oic configurations

### ISSUE THREAD

**Issue by mcandre** [jenkinsci/helm-charts#470]
**Is your feature request related to a problem? Please describe.**

`clientId` and `clientSecret` are important values for `oic` security realm configurations. However, the chart currently does not warn in the case where `clientId` and/or `clientSecret` are blank. Such a configuration can lead to a broken Jenkins server.

**Describe the solution you'd like**

When a security realm `oic` block is configured, then require `clientId` and `clientSecret` parameters to be non-blank string values.

**Comment by torstenwalter** [comment]
It's not in scope of the helm chart to validate plugin configurations done via configuration as code.
