### ISSUE TITLE
Using azurefiles as storage class on AKS

### ISSUE THREAD

**Issue by bsloan-icl** [jenkinsci/helm-charts#480]
**Describe the bug**
When following the instructions at https://www.jenkins.io/doc/book/installing/kubernetes/ to install Jenkins on AKS the setup works fine. When changing the storage class to "default" (which uses azure managed disks), the setup also works fine. However when trying to change the storage class to "azurefile" (which uses azure files) I get the following error from the logs: 
`[2021-10-12 10:41:16] Received unknown exception: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /reload-configuration-as-code/?casc-reload-token=jenkins-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f580455b520>: Failed to establish a new connection: [Errno 111] Connection refused'))`.

Describing the pod gives me:
```
  Normal   Created           10s                kubelet            Created container config-reload
  Normal   Started           10s                kubelet            Started container config-reload
  Warning  Unhealthy         2s                 kubelet            Startup probe failed: Get "http://10.244.1.4:8080/login": dial tcp 10.244.1.4:8080: connect: connection refused
```
I can use the "azurefile" storage class when deploying Jenkins using a standard deployment.yaml but when trying to use the helm chart it doesn't work. I'm assuming there may be some additional config required in the values file but I'm not sure what. I've also tried changing "runasuser" to 0 but it still falls over. I can see in the azure portal that the pv and pvc are both bound and the storage account/ fileshare has been created but only with the casc_configs, plugins & war directories and copy_reference_fie.log, jenkins.installUtil.lastExecVersion, jenkins.install.UpgradeWizard.state and & plugins.txt files. 

**Version of Helm and Kubernetes**:

Helm Version: 

```console
$ helm version
version.BuildInfo{Version:"v3.7.0-rc.2", GitCommit:"4a7c306aa9dcbdeecf79c7517851921a21b72e56", GitTreeState:"clean", GoVersion:"go1.16.7"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"8dc42052754bfacb111a0426830122dd9cc9cfa0", GitTreeState:"clean", BuildDate:"2021-08-31T00:01:04Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
version: 3.7.0

**What happened**:
Startup probe failed: Get "http://10.244.1.5:8080/login": dial tcp 10.244.1.5:8080: connect: connection refused

**What you expected to happen**:
Both pods to be running and Jenkins to be accessible

**How to reproduce it** (as minimally and precisely as possible):
kubectl create ns jenkins
kubectl apply -f jenkins-sa.yaml (from https://www.jenkins.io/doc/book/installing/kubernetes/)
helm install -n jenkins jenkins -f jenkins-values.yaml jenkinsci/jenkins (with custom values shown below)

```
serviceType: NodePort
  nodePort: 32000 

serviceAccount:
  create: false
  name: jenkins

persistence:
  enabled: true
  existingClaim:
  storageClass: azurefile
  annotations: {}
  labels: {}
  accessMode: "ReadWriteMany"
  size: "8Gi"
 
```

**Anything else we need to know**:

**Comment by hazzik** [comment]
@bsloan-icl my PR #295 has been merged, so it should be in the latest helm.

**Comment by bsloan-icl** [comment]
That's great, thanks @hazzik.
