### ISSUE TITLE
list repository in https://hub.helm.sh/

### ISSUE THREAD

**Issue by torstenwalter** [jenkinsci/helm-charts#5]
Process is described in https://github.com/helm/hub/blob/master/Repositories.md

**Comment by timja** [comment]
See also https://github.com/helm/hub/issues/439

**Comment by scottrigby** [comment]
Was just about to say, let's also add to artifacthub.io. I just added the jenkinsci org and helm repo there and will invite you so you can maintain it

**Comment by torstenwalter** [comment]
Thanks. Just signed up. My username is `torstenwalter`.
Do you have permissions to merge https://github.com/helm/hub/pull/451?

**Comment by scottrigby** [comment]
Yes, done and done

**Comment by scottrigby** [comment]
Helm hub should sync the chart within the next 30 mins. Artifact hub chart is there now https://artifacthub.io/packages/helm/jenkinsci/jenkins

**Comment by torstenwalter** [comment]
Thank you. With this we can close this taks.
