### ISSUE TITLE
Vulnerable version, 1.55 of configuration-as-code installed

### ISSUE THREAD

**Issue by scramados** [jenkinsci/helm-charts#542]
**Describe the bug**
The helm chart installs a vulnerable version of the configuration-as-code plugin. It should install version 1.55.1 instead.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}

```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8+rke2r1", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T21:37:43Z", GoVersion:"go1.16.10b7", Compiler:"gc", Platform:"linux/amd64"}
```
**Which version of the chart**: 3.11.0

**What happened**: the chart install version 1.55 of the configuration-as-code plugin

**What you expected to happen**: The chart install version 1.55.1 of the configuration-as-code plugin

**How to reproduce it** (as minimally and precisely as possible): install the helm chart

**Comment by torstenwalter** [comment]
@scramados Thanks for the pointer. I did not notice that version as it is not listed on the release pages https://github.com/jenkinsci/configuration-as-code-plugin/releases

**Comment by scramados** [comment]
Sorry for the updates spam. I was setting up a gpg key to do it myself but you beat me to it :)

**Comment by torstenwalter** [comment]
> Sorry for the updates spam. I was setting up a gpg key to do it myself but you beat me to it :)

No worries. Thanks again for raising that issue. Was just lucky to see it directly when you created it.
