### ISSUE TITLE
Jenkins default usename "Admin" and "Password" are not working

### ISSUE THREAD

**Issue by gh-srudra** [jenkinsci/helm-charts#550]
Hi, 

I have installed Jenkins using helm chart. After successfully installation of the charts, I retrieved the password from the pod and trying to sign in with credentials.

username: admin
password:  *********

After doing exec to the pod, running  command for getting the password `cat /run/secrets/chart-admin-password && echo`  

When I try to sign with this credentials, It is giving error with invalid credentials.

Thanks in advance!!

**Comment by roopaax** [comment]
what is the solution for this?

**Comment by HariSekhon** [comment]
This is probably why:

https://github.com/jenkinsci/helm-charts/issues/1026

This is the solution - reset your admin password:

https://github.com/HariSekhon/Docs/blob/main/jenkins.md#reset-the-jenkins-admin-password-on-kubernetes
