### ISSUE TITLE
Specify POD Distrubtion Budget

### ISSUE THREAD

**Issue by Alien2150** [jenkinsci/helm-charts#56]
Hey folks,

I think it would be great to provide a Pod Distrubtion Budget for Jenkins Master. The simple reason is that in a cloud environment every time a node could break or could get replaced and the service and as as result right now ingress 
shows 502 (As long as it takes to ramp up Jenkins. Which can some minutes). It sounds like low-hanging fruits to specify a PDB for the master node to provide the Kubernetes scheduler a hint that the service should be moved first before termination: https://kubernetes.io/docs/tasks/run-application/configure-pdb/

Cheers!

**Comment by torstenwalter** [comment]
@Alien2150 good idea. Could you create a PR for that?

**Comment by Alien2150** [comment]
Good point. Also after rereading the docs; It might be problematic in various cases when running in non-HA setup (It's even not recommended to not do it then)

**Comment by torstenwalter** [comment]
>Possible Solution 1: Do not use a PDB and tolerate occasional downtime.

>Possible Solution 2: Set PDB with maxUnavailable=0. Have an understanding (outside of Kubernetes) that the cluster operator needs to consult you before termination. When the cluster operator contacts you, prepare for downtime, and then delete the PDB to indicate readiness for disruption. Recreate afterwards.

For solution 1 there is nothing to do. Solution 2 is something I'd rather not implement in the helm chart.

**Comment by Alien2150** [comment]
So providing it as a template? Might work
