### ISSUE TITLE
Allow using securityContext fsGroup without using runAsUser

### ISSUE THREAD

**Issue by LMojica** [jenkinsci/helm-charts#59]
**Is your feature request related to a problem? Please describe.**

The `jenkins-master-deployment.yaml` file only allows setting the `fsGroup` value if the `runAsUser` value is set to a non-root user (user 0).

**Describe the solution you'd like**

Allow the `fsGroup` value to be set without having to set `runAsUser` to `0`.

**Describe alternatives you've considered**

**Additional context**

I have a use case that requires me to set the `fsGroup` value, while still setting `runAsUser` to 0. The current template does not allow for this case.

**Comment by torstenwalter** [comment]
@LMojica could you provide more background information on your use case?

In general we do not recommend running Jenkins as root (uid 0).

**Comment by LMojica** [comment]
Actually, to be more clear, what I really want is to be able to set `fsGroup` without having to set `runAsUser` at all. The current template only allows setting `fsGroup` if `runAsUser` is set, and only if it's set to a non-root user.

The use case I have is that I'm running my Jenkins pod with Istio. The init-container for Istio requires that it run with root privileges. Setting `runAsUser` to a non-root user causes the Istio init-container to fail because it also runs as a non-root user. So I would like to leave `runAsUser` unset, so each container can use its default user, but I also need to be able to set `fsGroup` so that the `jenkins` user can access its home directory.

**Comment by torstenwalter** [comment]
@LMojica looks like that check was introduced to stay compatible with older versions of the chart.

I would say it's safe to remove the condition https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/jenkins-master-deployment.yaml#L76 if we document in the Changelog and in  https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins#summary-of-updated-values
that the behavior was changed.

Could you create a PR for it and link it to this issue?

**Comment by LMojica** [comment]
Closing this issue since I have decided to go with a different approach.
