### ISSUE TITLE
Possibility of semver mismatch

### ISSUE THREAD

**Issue by hjubi** [jenkinsci/helm-charts#592]
Hi.

What about custom name of controller tag?

https://github.com/jenkinsci/helm-charts/blob/43ed7d4785011fa40461805566ef48db222f2bc8/charts/jenkins/templates/_helpers.tpl#L118

I think that helm linter will fails when we set custom controller name e.g. "jenkins-2137" (pulling image from own docker hub)

Helm chart version >= 3.11.7

**Comment by lukaszkubisiak-intel** [comment]
+1

**Comment by sichapman** [comment]
We use `lts` tag which does indeed now fail

**Comment by mount986** [comment]
any tag that isn't strictly the version fails.. we use `tag: "lts-alpine"`

**Comment by jgrasett** [comment]
I'm getting:
`Error: template: jenkins/templates/jcasc-config.yaml:43:8: executing "jenkins/templates/jcasc-config.yaml" at <include "jenkins.casc.defaults" .>: error calling include: template: jenkins/templates/_helpers.tpl:117:28: executing "jenkins.casc.defaults" at <semver (default .Chart.AppVersion .Values.controller.tag)>: error calling semver: Invalid Semantic Version`

**Comment by Nezale** [comment]
+1

**Comment by michalmagun** [comment]
+1

**Comment by atomporowski** [comment]
+1

**Comment by TheSp1der** [comment]
+1

**Comment by bchanson** [comment]
+1

**Comment by alan-mas** [comment]
+1

**Comment by rnkhouse** [comment]
+1

**Comment by Bryan-Ortiz** [comment]
+1

**Comment by emilianofs** [comment]
+1

**Comment by gsomoza** [comment]
+1

**Comment by jgournet** [comment]
Looks like many people are stuck on version "3.11.6" because of this.
=> can someone actually look at this ?
(or is there a workaround ?)

**Comment by timja** [comment]
Closed by https://github.com/jenkinsci/helm-charts/pull/625
