### ISSUE TITLE
test ci pipeline

### ISSUE THREAD

**Issue by torstenwalter** [jenkinsci/helm-charts#6]
- chat should be linted
- DCO version should be checked

=> enforce both checks for PRs

**Comment by scottrigby** [comment]
This is all working now, yes?

**Comment by torstenwalter** [comment]
Yes all of this is working now:

# DCO Check and CI Pipeline

  ![image](https://user-images.githubusercontent.com/1743774/91822683-654b9f80-ec38-11ea-8a97-5573aa50ce06.png)
  https://github.com/jenkinsci/helm-charts/pull/17
  
  ![image](https://user-images.githubusercontent.com/1743774/91822596-4e0cb200-ec38-11ea-9b53-a045e9c385d3.png)
  https://github.com/jenkinsci/helm-charts/pull/17/checks?check_run_id=1055056797



# CD Pipeline

  ![image](https://user-images.githubusercontent.com/1743774/91822397-08e88000-ec38-11ea-89a1-f54c8e3843be.png)
  https://github.com/jenkinsci/helm-charts/actions?query=workflow%3A%22Release+Charts%22
