### ISSUE TITLE
Chart no longer starts with host cluster added as cloud

### ISSUE THREAD

**Issue by rbambrough-intel** [jenkinsci/helm-charts#617]
### Describe the bug

Chart used to spawn a Jenkins instance with the hosting Kubernetes cluster already configured as a cloud. I'm unable to find any documentation on where this was disabled and how to re-enable this behavior.

### Version of Helm and Kubernetes

```markdown
- Helm: version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}
- Kubernetes: Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.12", GitCommit:"4bf2e32bb2b9fdeea19ff7cdc1fb51fb295ec407", GitTreeState:"clean", BuildDate:"2021-10-27T17:07:18Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Chart version

jenkins-3.12.0

### What happened?

```bash
1. Install chart
2. Manage Jenkins -> Manage Nodes and Clouds -> Configure Clouds
```

### What you expected to happen?

The hosting Kubernetes cluster to have been configured in Jenkins clouds.

### How to reproduce it

```markdown
I'm behind a corporate proxy so can't put the values.yaml, but I've had the values working on a previous version of the chart.
```

**Comment by rbambrough-intel** [comment]
Mis-identified root cause, going to re-issue when better understood

**Comment by hectoralicea** [comment]
> Mis-identified root cause, going to re-issue when better understood

I have the exact same issue.  What root cause did you find?
