### ISSUE TITLE
Default jcasc config not set when sidecars.configAutoReload is disabled

### ISSUE THREAD

**Issue by Cirrith** [jenkinsci/helm-charts#618]
### Describe the bug

Default jcasc file (jcasc-default-config.yaml) is not copied to jenkinsHome unless a configScript is specified.

### Version of Helm and Kubernetes

```markdown
- Helm: v3.8.0
- Kubernetes: v1.20.15
```

### Chart version

jenkins-3.12.0

### What happened?

```bash
1. Install chart
2. Manage Jenkins -> Manage Nodes and Clouds -> Configure Clouds
```

### What you expected to happen?

The hosting Kubernetes cluster to have been configured in Jenkins clouds.

### How to reproduce it

```markdown
values.yaml

controller:
  sidecars:
    configAutoReload:
      enabled: false

helm install jenkins jenins/jenkins --values values.yaml
```

### Anything else we need to know?

Bug appears to be in charts/jenkins/templates/config.yaml:46

```go
{{- if not .Values.controller.sidecars.configAutoReload.enabled }}
  echo "copy configuration as code files"
  mkdir -p {{ .Values.controller.jenkinsHome }}/casc_configs;
  rm -rf {{ .Values.controller.jenkinsHome }}/casc_configs/*
  {{- if .Values.controller.JCasC.configScripts }}
  cp -v /var/jenkins_config/*.yaml {{ .Values.controller.jenkinsHome }}/casc_configs
  {{- end }}
{{- end }}
```

Pretty sure the following line can be removed:
`{{- if .Values.controller.JCasC.configScripts }}` 

Or modified to check if default config is enabled:
`{{- if or .Values.controller.JCasC.configScripts .Values.controller.JCasC.defaultConfig }}`

**Comment by ShihouinYoruichi** [comment]
Hello, I'm very surprised that this fact has been raised as an issue quite a long time without any responses from the contributors. There is no doubt that I also strongly agree with your opinion as a user.

I tried to utilize disabling that option for some particular reasons and realized Jenkins was ended up being installed without the default configuration. Thus, I had no choice but to just modify the configmap manually.

I do understand the concept of JCasC. At the same time, however, I think the freedom also should be completely allowed for the users once the default values were set on the initialization step.

**Comment by timja** [comment]
Pull requests are welcome to fix.

From my reading of it, all you need to do to workaround this is to include at least 1 `configScript` which most people would be doing.

(hence the low activity on this issue)

**Comment by ShihouinYoruichi** [comment]
@timja 

I followed the pull request rules and now I finally could create the right one.
[Pull Request for Issue #618](https://github.com/jenkinsci/helm-charts/pull/724)

It seems all the checks were successfully passed as well.
