### ISSUE TITLE
initcontainer JAVA_OPS (mainly proxy settings)

### ISSUE THREAD

**Issue by lagunary** [jenkinsci/helm-charts#620]
### Describe the bug

Hello,
I caught a bug:
Helm installation was successfull.
But the init container (called init)  cannot get JAVA_OPTS with proxy settings.
Ive tested, and although inside the container there is no JAVA_OPTS. In generated statefull set hasnt got JAVA_OPTS env for initContainer. There is no space in values.yaml like init_JAVA_OTPS or smg else. Based on intend I though they common options for all containers in pod, but it seems from statefull set it isnt.
I modified the statufull set to get JAVA_OPTS env for init container and it started to work perfectly.
The bug is only in JAVA, not in the container bash.

Please let a new variable in values called init_javaOpts, or make modification in chart to use both container the proxy settings.

BR,
Viktor

### Version of Helm and Kubernetes

```markdown
- Helm: 
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}
- Kubernetes: 
Kubernetes Version: v1.23.5
```

### Chart version

jenkins-3.12.1

### What happened?

```bash
Not works.
```

### What you expected to happen?

It will woks :)

### How to reproduce it

```markdown
Install jenkins from helm for a comuter has proxy. Init container download plugin will fail due to timeout (cannot reach internet).
You may fullfill the values with proxy settings, it wont work for init container.
```

### Anything else we need to know?

You can ask me further info anytime.

**Comment by timja** [comment]
You can pass `initContainerEnv`

https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/jenkins-controller-statefulset.yaml#L118
