### ISSUE TITLE
EKS - Kubernetes version 1.21 graduated BoundServiceAccountTokenVolume

### ISSUE THREAD

**Issue by jseiser** [jenkinsci/helm-charts#622]
### Describe the bug

Kubernetes version 1.21 graduated BoundServiceAccountTokenVolume feature [1] to beta and enabled it by default. This feature improves security of service account tokens by requiring a one hour expiry time, over the previous default of no expiration. This means that applications that do not refetch service account tokens periodically will receive an HTTP 401 unauthorized error response on requests to Kubernetes API server with expired tokens. You can learn more about the BoundServiceAccountToken feature in EKS Kubernetes 1.21 release notes

### Version of Helm and Kubernetes

```markdown
- Helm: v3.8.2
- Kubernetes: 1.22
```

### Chart version

jeknins-3.12.1

### What happened?

```bash
1. Upgrade EKS to latest release
2. Service Account Tokens were not refreshed
```

### What you expected to happen?

Service Accounts would refresh their tokens.

### How to reproduce it

```markdown
Just do a basic install into EKS.
```

### Anything else we need to know?

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.21

**Comment by jseiser** [comment]
I got the above in an Email FROM AWS.  I honestly am not sure how to properly report this, i imagine it really needs to go to the upstream Jenkins, so they use a new enough kubernetes SDK, that understands how to refresh tokens.  

As of now, in EKS, you would need to kill the running pod atleast every 90 days to prevent it from losing access.

**Comment by gfoligna-nyshex** [comment]
Sorry for adding more to the unknown, but I'm also wondering where to address this in our current setup.
We are running EKS 1.21, and we have Jenkins 2.319.3 currently running.

The output I'm getting from AWS is that one of my service accounts is using the old tokens, so not sure what to do here.

If someone can shed some light here I'll appreciate it :)

**Comment by timja** [comment]
This should be reported to the plugin, see report an issue on https://plugins.jenkins.io/kubernetes/
