### ISSUE TITLE
Allow override of JCasC.configScripts ConfigMap names

### ISSUE THREAD

**Issue by miles-w-3** [jenkinsci/helm-charts#650]
### Is your feature request related to a problem? Please describe

Currently, config scripts generated through controller.JCasC.configScripts get processed by the `casc-config.yaml` template. Both of the configMaps named in this template on lines 9 and 30 append `-jenkins` in the name. Since we name our chart jenkins, the call to jenkins.fullname results in a redundantly long name. Additionally, it adds confusion when viewing the resources in argo because the differentiating part of the name gets cut off

### Describe the solution you'd like

The most ideal solution would be to template out the jcasc function name to _helpers.tpl, under a name like "jenkins.jcasc-config" rather than generating it on the fly inside of the template. This would allow it to be overridden by downstream charts without disrupting current functionality.

Another option would be to just remove the `-jenkins` hardcoded name in the title since most people probably include it in their release name. However this is more disruptive since it will interrupt current functionality.

I would be happy to contribute to either solution above. Thank you for your time. 

### Describe alternatives you've considered

I've tried overriding jenkins.fullname myself in the downstream chart to just remove jenkins from that template, but that affects a lot of other resources like the statefulset that don't duplicate the name. I've also considered re-creating this template with flexibility for the name and disabling the functionality within the chart, but I would like to usee as much of the chart as possible because it is so well done.

**Comment by timja** [comment]
fine to make that part of it configurable, I think dropping it may be a bit disruptive to people so wouldn't want to do that as a first option

**Comment by miles-w-3** [comment]
Sounds good to me, how would I go about making a branch for this? I don't see the option under "development"
