### ISSUE TITLE
Unable to start Jenkins 

### ISSUE THREAD

**Issue by botkosmos** [jenkinsci/helm-charts#657]
### Describe the bug

Hi, Jenkins can't start because init container is already in failed status when trying to download plugin : 

Downloaded and validated plugin branch-api
No checksum found for branch-api (probably custom built plugin)
Downloaded configuration-as-code from https://mirror.gruenehoelle.nl/jenkins/plugins/configuration-as-code/1429.v09b_044a_c93de/configuration-as-code.hpi (attempt 1 of 3)
Downloaded and validated plugin configuration-as-code
Checksum valid for: configuration-as-code
Downloaded script-security from https://mirror.gruenehoelle.nl/jenkins/plugins/script-security/1175.v4b_d517d6db_f0/script-security.hpi (attempt 1 of 3)
Downloaded and validated plugin script-security
Checksum valid for: script-security
Downloaded workflow-basic-steps from https://mirror.gruenehoelle.nl/jenkins/plugins/workflow-basic-steps/948.v2c72a_091b_b_68/workflow-basic-steps.hpi (attempt 1 of 3)
Downloaded and validated plugin workflow-basic-steps
Checksum valid for: workflow-basic-steps
Downloaded pipeline-build-step from https://mirror.gruenehoelle.nl/jenkins/plugins/pipeline-build-step/2.18/pipeline-build-step.hpi (attempt 1 of 3)
Downloaded and validated plugin pipeline-build-step
Checksum valid for: pipeline-build-step
Downloaded jsch from https://mirror.gruenehoelle.nl/jenkins/plugins/jsch/0.1.55.2/jsch.hpi (attempt 1 of 3)
Downloaded and validated plugin jsch
Checksum valid for: jsch
Downloaded variant from https://ftp.halifax.rwth-aachen.de/jenkins/plugins/variant/1.4/variant.hpi (attempt 1 of 3)
Downloaded and validated plugin variant
Checksum valid for: variant
Downloaded pipeline-input-step from https://ftp.halifax.rwth-aachen.de/jenkins/plugins/pipeline-input-step/449.v77f0e8b_845c4/pipeline-input-step.hpi (attempt 1 of 3)
Downloaded and validated plugin pipeline-input-step
Checksum valid for: pipeline-input-step
Jun 28, 2022 1:06:29 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://ftp.halifax.rwth-aachen.de:443: The target server failed to respond
Jun 28, 2022 1:06:29 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://ftp.halifax.rwth-aachen.de:443

### Version of Helm and Kubernetes

```markdown
- Helm: 3.5.2
- Kubernetes: 1.20.15
```

### Chart version

jenkins-4.1.11

### What happened?

```bash
1.
2.
3.
...
```

**Comment by lknite** [comment]
I'm still working to get this helm chart to work, still a bit of a newbie in some ways, but when I see your notes it looks like only that last item is failing.

Maybe try removing that plugin from your values.yaml and see if things start up as expected?
```
https://ftp.halifax.rwth-aachen.de/
```

**Comment by botkosmos** [comment]
Hi it seems better this morning, maybe https://ftp.halifax unreachable sometimes ?

I close this issue.
