### ISSUE TITLE
When a keystore is specified in the values.yaml, that keystore should also be mounted/available in the init pod.

### ISSUE THREAD

**Issue by lknite** [jenkinsci/helm-charts#658]
### Is your feature request related to a problem? Please describe

Yes, my init pod is failing with PKIX errors, yet I've specified a keystore in the values.yaml .

### Describe the solution you'd like

I would have expected the init pod to have the keystore provided in the values.yaml .

### Describe alternatives you've considered

Someone posted the solution of creating a custom init container and adding the keystore manually.... but this doesn't seem right when the keystore has already been specified and its in a secret ready to be mounted.

### Additional context

- Possibly, a 'truststore' needs to be added in addition to a 'keystore'?  I generally have the same values in both, but I understand they have different purposes.
- This functionality is needed within all companies / organizations which have a security team using tools to watch for dangerous traffic.  I could try to add the functionality with a pull request but I'm not sure of the right way to do so.

I have identified that the PKIX errors are coming specifically within the init when running apply_config.sh, within the jenkins cm, at the line where plugins are installed with jenkins-plugin-cli .  Is it possible to get that command to see the keystore?  Maybe a java environment variable is needed?

**Comment by lknite** [comment]
This seems to help, at least there is now a keystore.jks file we can experiment with mounted in the init container.
```
        initContainers:
          volumeMounts:
            {{- if .Values.controller.httpsKeyStore.enable }}
            {{- $httpsJKSDirPath :=  printf "%s" .Values.controller.httpsKeyStore.path }}
            - mountPath: {{ $httpsJKSDirPath }}
              name: jenkins-https-keystore
            {{- end }}
```

**Comment by lknite** [comment]
Seems like adding this to the statefulset yaml would add the keystore.jks but doesn't seem to ...
```
        initContainers:
        - name:
          volumeMounts:
            {{- if .Values.controller.httpsKeyStore.enable }}
            {{- $httpsJKSDirPath :=  printf "%s" .Values.controller.httpsKeyStore.path }}
            - mountPath: {{ $httpsJKSDirPath }}
              name: jenkins-https-keystore
            {{- end }}
```

**Comment by lknite** [comment]
Had to modify the script I was using to import multiple certificates from a PEM file into the keystore, had to add -storetype JKS:
```
$ cat tools/jks_import_pem 
#!/bin/bash
PEM_FILE=$1
PASSWORD=$2
KEYSTORE=$3
# number of certs in the PEM file
CERTS=$(grep 'END CERTIFICATE' $PEM_FILE| wc -l)

# For every cert in the PEM file, extract it and import into the JKS keystore
# awk command: step 1, if line is in the desired cert, print the line
#              step 2, increment counter when last line of cert is found
for N in $(seq 0 $(($CERTS - 1))); do
  ALIAS="${PEM_FILE%.*}-$N"
  cat $PEM_FILE |
    awk "n==$N { print }; /END CERTIFICATE/ { n++ }" |
    keytool -noprompt -import -trustcacerts \
            -alias $ALIAS -keystore $KEYSTORE -storepass $PASSWORD -storetype JKS
done
```

**Comment by lknite** [comment]
# Regarding a pull request

Would it be acceptable to just add the keystore check on the initContainer as I've done above?  I think I actually modified the truststore rather than the keystore.  I'm not sure it matters, I think a lot of folks just treat those as the same which this helm chart seems to do.  If so, if they are just kind of assumed the same then adding the keystore to the init pod seems like it might be the right approach.  What do ya'll think?

**Comment by timja** [comment]
trust stores and key stores are for different things.

You can either build a custom image and add your certificate to the default cacerts

or pass a system property that sets `javax.net.ssl.trustStore` in `javaOpts` to use your own trust store
