### ISSUE TITLE
To expose "activeDeadlineSeconds" for back job in the template

### ISSUE THREAD

**Issue by dex80526** [jenkinsci/helm-charts#66]
**Is your feature request related to a problem? Please describe.**
My Jenkins backup job is not marked completed or failed for ever in K8S. This prevents any new jobs get scheduled. The end result is that the backup cronjob did not get kicked off anymore since there is an active job. One of solutions to this problem is to specify "activeDeadlineSeconds" in the cronjob spec. However, the current helm template does not define and expose that parameter. Please add "activeDeadlineSeconds" to the backup job template.

**Describe the solution you'd like**
Add "activeDeadlineSeconds" to jenkins-backup-cronjob.yaml

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by prabhu43** [comment]
I will work on this
