### ISSUE TITLE
Jenkins URL not take effect

### ISSUE THREAD

**Issue by wufengzlw** [jenkinsci/helm-charts#665]
### Describe the bug

Hi, 

We have a deployment in AWS EKS with ALB, traffic routing: Client --> ALB --> Istio --> Jenkins
Image: jenkins/jenkins:2.332.1-jdk11

Originally, it works fine with this URL: https://jenkins.monitoring.xxx.xxx.xxx
Recently, Jenkins returned URL becomes http://jenkins.monitoring.xxx.xxx.xxx:443 (http with a port of 443), so I got this error
```
400 Bad Request
The plain HTTP request was sent to HTTPS port
```

Here is the trouble shoot I did:
1. In the Jenkins > Manage Jenkins > Configure System, Jenkins URL was configured with https://jenkins.monitoring.xxx.xxx.xxx, but Jenkins still return http+443, this is the config from Jenkins_home directory:
```
jenkins@jenkins-0:~$ more jenkins.model.JenkinsLocationConfiguration.xml
<?xml version='1.1' encoding='UTF-8'?>
<jenkins.model.JenkinsLocationConfiguration>
  <adminAddress>address not configured yet &lt;nobody@nowhere&gt;</adminAddress>
  <jenkinsUrl>https://jenkins.monitoring.xxx.xxx.xxx/</jenkinsUrl>
</jenkins.model.JenkinsLocationConfiguration>
```
2. When I removed Jenkins URL from GUI (save with empty value), this one shows: http://jenkins.monitoring.xxx.xxx.xxx:443/, and this is the config from Jenkins_home directory:
```
jenkins@jenkins-0:~$ more jenkins.model.JenkinsLocationConfiguration.xml
<?xml version='1.1' encoding='UTF-8'?>
<jenkins.model.JenkinsLocationConfiguration>
  <adminAddress>address not configured yet &lt;nobody@nowhere&gt;</adminAddress>
</jenkins.model.JenkinsLocationConfiguration>
```
Seems Jenkins URL config is properly configured, but it's not taking effect.

### Version of Helm and Kubernetes

```markdown
- Helm: v3.7.0
- Kubernetes: v1.20.15-eks-a64ea69
```

### Chart version

3.11.8

### What happened?

```bash
1.
2.
3.
...
```

### What you expected to happen?

Jenkins should return URL https://jenkins.monitoring.xxx.xxx.xxx

**Comment by torstenwalter** [comment]
You are describing changes made via the UI. That's unrelated to the helm chart. The idea of this chart is rather to have the Jenkins URL managed via JCasC.

**Comment by torstenwalter** [comment]
Did you try configuring Jenkins URL via JCasC? If you want to stick with the UI did you try entering http://jenkins.monitoring.xxx.xxx.xxx:80

**Comment by wufengzlw** [comment]
@torstenwalter 
I tried http+80 config in the UI, it doesn't work.
Haven't try JCasC yet.

**Comment by wufengzlw** [comment]
I have this in the helm values:
```
controller:
  jenkinsUrlProtocol: https
  jenkinsUrl: https://jenkins.monitoring.xxx.xxx.xxx
```
but this is not in the config:
```
jenkins@jenkins-0:~$ more jenkins.model.JenkinsLocationConfiguration.xml
<?xml version='1.1' encoding='UTF-8'?>
<jenkins.model.JenkinsLocationConfiguration>
  <adminAddress>address not configured yet &lt;nobody@nowhere&gt;</adminAddress>
</jenkins.model.JenkinsLocationConfiguration>
```

**Comment by wufengzlw** [comment]
Hi, this one is fixed by adding header setup in Istio, thanks for the help @torstenwalter
