### ISSUE TITLE
Add option to add binaryData to the ConfigMap

### ISSUE THREAD

**Issue by LMojica** [jenkinsci/helm-charts#67]
**Is your feature request related to a problem? Please describe.**

The `config.yaml` file only allows adding additional configs under the `data` key, but does not give an option to add `binaryData`.

**Describe the solution you'd like**

Add a `binaryData` key to the `config.yaml` file and allow it to be customizable through `values.yaml`.

**Describe alternatives you've considered**

An alternative is to create a separate ConfigMap yaml to store the binary data. This is an easy workaround, but results in having one more ConfigMap file to work with.

**Additional context**

**Comment by torstenwalter** [comment]
What's your use case for binary data? What do you want to use it for?

**Comment by LMojica** [comment]
I use the binary data field to place gzipped archives on Jenkins. But I'm going to close this issue since I have decided to go with a different approach.
