### ISSUE TITLE
Support custom system properties

### ISSUE THREAD

**Issue by jimsnab** [jenkinsci/helm-charts#670]
### Is your feature request related to a problem? Please describe

I would like to control [system properties](https://www.jenkins.io/doc/book/managing/system-properties/), such as the logging ring buffer size. When Jenkins runs in a container, it can get these parameters with a variable `JAVA_OPTS`. I am able to manually modify the statefulset yaml to change the logging ring buffer size. I would like to set this within my `values.yaml`.

### Describe the solution you'd like

Support a helm variable to extend `JAVA_OPTS` within the statefulset, as described [here](https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/client-and-managed-masters/how-to-add-java-arguments-to-jenkins#_running_jenkins_inside_docker).

**Comment by timja** [comment]
`controller.javaOpts` is available:

https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins#running-behind-a-forward-proxy
