### ISSUE TITLE
Can't edit "Concurrency Limit" setting

### ISSUE THREAD

**Issue by matanz121** [jenkinsci/helm-charts#677]
Hi,

I have Jenkins installed with the latest helm chart & Jenkins versions.
Unfortunately only 10 builds can run simultaneously and can't increase it from the chart/jcasc.
Somehow the default value with this helm chart is set to 10, however, I would like to keep it empty meaning no limit
Under Manage jenkins -> Manage nodes and clouds -> Configure clouds -> Concurrency Limit
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/42091469/182858750-2512b58a-2504-4d4d-8a2b-1ad1d604f52b.png">

Is there a way to change it?

**Comment by timja** [comment]
https://github.com/jenkinsci/helm-charts/blob/f6a406e68a00ecb1ed8c94c065f02ebdc8fcf150/charts/jenkins/values.yaml#L688

`agent.containerCap`

**Comment by matanz121** [comment]
WOW! Thanks a lot!!!
