### ISSUE TITLE
jenkins-test pod definition issues

### ISSUE THREAD

**Issue by andy-dws** [jenkinsci/helm-charts#683]
Just a couple of observations from running this chart in a corporate environment with no internet access and a private repository with binary authorization enabled (i.e. digests are mandatory, label tags are forbidden).

https://github.com/jenkinsci/helm-charts/blob/17fbf8f1566e139a96ff3f3084eab8da1532de3d/charts/jenkins/templates/tests/jenkins-test.yaml#L20

The above should be configurable.

https://github.com/jenkinsci/helm-charts/blob/17fbf8f1566e139a96ff3f3084eab8da1532de3d/charts/jenkins/templates/tests/jenkins-test.yaml#L34

The above should be written in the same style as the main statefulset so that digests are possible.

**Comment by timja** [comment]
PR welcome :)

**Comment by ismaelsadeeq** [comment]
Hello @andy-dws I am new to Jenkins open source would like to work on this issue, am I editing line 20 image: "bats/bats:1.2.1"  to line 34 image: {{ .Values.controller.image }}:{{ .Chart.AppVersion }}-{{ .Values.controller.tagLabel }} 
Thanks

**Comment by elmsdata** [comment]
HI @timja! I would love to work on this issue if no one else is, looking for a good first issue to get involved with the Jenkins community! We use it as our primary CI/CD at our company and also heavily use helm for a majority of our application deployments. Read through the contributing documentation and I should be set to open pull request in the next few days. My only question, after reading through the helm charts, should the [VALUES_SUMMARY.md](https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/VALUES_SUMMARY.md) be updated to include a Unit Test section now that it will be configurable? Thanks and hope you have a great day!

**Comment by timja** [comment]
> Should the [VALUES_SUMMARY.md](https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/VALUES_SUMMARY.md?rgh-link-date=2023-02-22T03%3A02%3A35Z) be updated to include a Unit Test section now that it will be configurable

May as well probably at the very bottom

> What format would be best to pass in the configurable values

Base values.yaml sounds fine to me

**Comment by elmsdata** [comment]
Wonderful, thanks for clarifying! Should have the pull request open tomorrow and hope you have an amazing Friday!
