### ISSUE TITLE
Expose slave listener port publicly to enable external worker nodes

### ISSUE THREAD

**Issue by 1w2w3y** [jenkinsci/helm-charts#70]
It is really nice to have dynamic worker nodes manged by k8s! This make the worker management work much easier!

We are also trying to add some VM agent nodes as persistent agent nodes to run some Selenium tests.

However, the master's 'slaveListenerPort' is not exposed publicly. It cannot be reached from the internet.

This is blocking us bring in our own VM nodes.

Is it possible to expose the JNLP TCP port?

### Error logs from connecting agent
Sep 26, 2020 5:58:20 AM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using C:\Users\liftrvmuser\Desktop\test-folder\work\remoting as a remoting work directory
Sep 26, 2020 5:58:20 AM org.jenkinsci.remoting.engine.WorkDirManager setupLogging
INFO: Both error and output logs will be printed to C:\Users\liftrvmuser\Desktop\test-folder\work\remoting
Sep 26, 2020 5:58:21 AM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: win-selenuim-worker-001
Sep 26, 2020 5:58:21 AM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Sep 26, 2020 5:58:21 AM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 4.5
Sep 26, 2020 5:58:21 AM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using C:\Users\liftrvmuser\Desktop\test-folder\work\remoting as a remoting work directory
Sep 26, 2020 5:58:21 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [https://jenkins.cicd.azliftr-test.io/]
Sep 26, 2020 5:58:21 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
Sep 26, 2020 5:58:26 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver isPortVisible
WARNING: connect timed out
Sep 26, 2020 5:58:26 AM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: https://jenkins.cicd.azliftr-test.io/ provided port:50000 is not reachable
java.io.IOException: https://jenkins.cicd.azliftr-test.io/ provided port:50000 is not reachable
        at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:314)
        at hudson.remoting.Engine.innerRun(Engine.java:694)
        at hudson.remoting.Engine.run(Engine.java:519)

**Comment by torstenwalter** [comment]
Would it work for you if we use  WebSockets to connect agents  instead?

https://www.jenkins.io/blog/2020/02/02/web-socket/

https://github.com/jenkinsci/helm-charts/issues/64#issuecomment-698359540

Then we would not need to expose the agent port.

**Comment by 1w2w3y** [comment]
Yes! This will work for me and it looks much easier!

Thanks!

**Comment by 1w2w3y** [comment]
@torstenwalter, thanks for the information! This is already working for me! Another port is not needed.
