### ISSUE TITLE
Enable variables for additionalExistingSecrets in values

### ISSUE THREAD

**Issue by SylivanKenobi** [jenkinsci/helm-charts#716]
### Is your feature request related to a problem? Please describe

We have dynamic Jenkins instances and we want to create dynamic secrets for those instances. These secrets have to be mounted to the Jenkins Pod. Currently this doesn't work because we can't use dynamic names for the Secrets in the values.yaml.

### Describe the solution you'd like

I would like to be able to use variables for the name of the additionalExistingSecrets in the values.yaml.

For example:
```
  additionalExistingSecrets:
  - name: "{{ .Release.Name }}-secret"
    keyName: secret-key-name
```

**Comment by timja** [comment]
What do you need these secrets for?

Is this an option instead? https://github.com/jenkinsci/kubernetes-credentials-provider-plugin

**Comment by SylivanKenobi** [comment]
We use the secrets for credentials inside Jenkins and as secret injection in casc. So the plugin only fixes half of our issue.

I think [tpl](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function) would be what we need.
