### ISSUE TITLE
Unable to override the agent label 

### ISSUE THREAD

**Issue by papi83dm** [jenkinsci/helm-charts#746]
### Describe the bug

when the Agents is enabled the label of the jenkins-agents gets created as `label: "{{ .Release.Name }}-{{ .Values.agent.componentName }} {{ .Values.agent.customJenkinsLabels  | join " " }}"` 

Please add another config podLabel similar to the podName to override the label.

### Version of Helm and Kubernetes

```markdown
- Helm: 
- Kubernetes:
```

### Chart version

4.2.12

### What happened?

```bash
1.Enable the agent in the values.yaml
2. 
3.
...
```

### What you expected to happen?

I should have the option to override the label of the jenkins-agent.

**Comment by m-ferrero** [comment]
Hello, there are several values "hidden" into _helpers.tpl for which I could not find documentation
there is already a agent.podLabels
I tested this on chart version 4.2.6

add the following to values.yaml

```
agent:
  podLabels:
    linux: true
  customJenkinsLabels: linux
```

this if you want a label "linux"

**Comment by papi83dm** [comment]
@m-ferrero Thanks, I had already found that variable and forgot to update this bug.
