### ISSUE TITLE
add support for agents connecting via websockets

### ISSUE THREAD

**Issue by torstenwalter** [jenkinsci/helm-charts#75]
**Is your feature request related to a problem? Please describe.**
Issue #64 raised awareness that we do not support websockts in the default JCasC configuration.
If people want to use it at the moment they have to disable defaults configuration and do all the other configuration it provides by themselves.

@galindro mentioned in https://github.com/jenkinsci/helm-charts/issues/64#issuecomment-698359540_ that we would need to do the following things:

> The differences are:
> 
> `jenkinsTunnel` should be removed or empty if `webSocket = ​true`
> `jenkinsUrl` should be `http://jenkins.jenkins.svc.cluster.local:8080` if run on k8s
> 
> and the following field should be added:
> `webSocket: true`

This would also solve #70 so that it simplifies connecting external agents to Jenkins, which is running on Kubernetes.

**Describe the solution you'd like**

Would be nice if we would have a flag in the values file via which we could enable websocket support e.g. `agent.websocket: true`, which would do the necessary configuration.

**Comment by 11000100111000** [comment]
I'd like to work on this issue

**Comment by torstenwalter** [comment]
Let me know of you need any help.

**Comment by 11000100111000** [comment]
currently facing the error message `io.jenkins.remoting.shaded.javax.websocket.DeploymentException: protocol = socket host = null` which doesn't really makes sense to me since when using `webSocket: false` it works without a problem.

Does something change here for the agent when using the websocket flag?

**Comment by torstenwalter** [comment]
Could you create a Draft PR? That would help to look into it.

Did you change the agent port (8080 instead of 50000)?

**Comment by 11000100111000** [comment]
That's probably it! I'll try out today and create the pr tomorrow if everything works

**Comment by 11000100111000** [comment]
I misunderstood your last comment.
I didn't change anything about the ports(and i don't see how to create a draft but my changes are linked anyways)

**Comment by torstenwalter** [comment]
Where do I find your changes?

**Comment by 11000100111000** [comment]
https://github.com/11000100111000/helm-charts/commit/b93c5c26d954d74d32e9a701e61139b316cf618e
For me they are linked in this thread ^^

**Comment by torstenwalter** [comment]
I missed that. For me this looks good. Left some small comments. The only things missing:
- bump the chart version
- add an entry in CHANGELOG.md
- optional, but very much appreciated a short documentation about that setting the README.
  That could include a link to https://www.jenkins.io/blog/2020/02/02/web-socket/

You can create a PR for it. Draft PR is just a normal PR the only difference is that while creating a PR you select draft. That indicates that it's not ready for review, yet. The benefit is that you see the results from the CI pipeline already. 

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request#creating-the-pull-request Point 6 shows how one can select draft.

https://github.blog/2019-02-14-introducing-draft-pull-requests/

PS: Feel free to create the PR as part of https://hacktoberfest.digitalocean.com/

**Comment by 11000100111000** [comment]
There is still the issue that the agents can't connect so yeah :/
