### ISSUE TITLE
chore(deps): bump lts to 2.375.1 #760

### ISSUE THREAD

**Issue by swamygoud18** [jenkinsci/helm-charts#763]
### Describe the bug

chore(deps): bump lts to 2.375.1 #760 , not having helm version to support with jenkins  2.375.1  and we see the PR #760 is failed

### Version of Helm and Kubernetes

```markdown
- Helm: 
- Kubernetes:
```

### Chart version

need helm to support 2.375.1

### What happened?

```bash
1.
2.
3.
...
```

**Comment by timja** [comment]
Raised https://github.com/jenkinsci/helm-charts/pull/765 hopefully it helps

**Comment by timja** [comment]
Fixed
