### ISSUE TITLE
Backup CronJob fails under K8S 1.25

### ISSUE THREAD

**Issue by matihost** [jenkinsci/helm-charts#773]
### Describe the bug

K8S 1.25 does not support CronJob in batch/v1beta1
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/jenkins-backup-cronjob.yaml#L2

Please add support to batch/v1

### Version of Helm and Kubernetes

```markdown
- Helm: 3.10.2
- Kubernetes: 1.25
```

### Chart version

4.2.17

### What happened?

```bash
1. Deployment with backup option
```

**Comment by kvanzuijlen** [comment]
@timja @lemeurherve This was fixed in #784
