### ISSUE TITLE
Add release notes to artifacthub.io/changes annotations

### ISSUE THREAD

**Issue by timja** [jenkinsci/helm-charts#790]
### Is your feature request related to a problem? Please describe

See https://artifacthub.io/docs/topics/annotations/helm/ and https://artifacthub.io/packages/helm/artifact-hub/artifact-hub?modal=changelog

It would be good to publish machine processable release notes that can be displayed in artifacthub

### Additional context

See also https://github.com/jenkinsci/helm-charts/issues/791

**Comment by lemeurherve** [comment]
Resolved by:
- #949
- #950 
- #951

**Comment by lemeurherve** [comment]
It failed because of https://github.com/jenkinsci/helm-charts/blob/6d1f284a25fca0dd47e052dc1361e8a050adde64/charts/jenkins/CHANGELOG.md#L20-L27

Fixup in #959
