### ISSUE TITLE
Publish changelog to GitHub releases

### ISSUE THREAD

**Issue by timja** [jenkinsci/helm-charts#791]
### Is your feature request related to a problem? Please describe

We're currently providing a static release description, see https://github.com/jenkinsci/helm-charts/releases/tag/jenkins-4.2.20 which isn't very useful.

It would be good if the changelog for that release was directly included in that, so people who subscribe to GitHub releases and ones who get automated pull requests (e.g. renovate) get a useful changelog

### Additional context

see also https://github.com/jenkinsci/helm-charts/issues/790

**Comment by lemeurherve** [comment]
Resolved by #946
