### ISSUE TITLE
Migrate to plugin-installation-manager-tool for plugin installation

### ISSUE THREAD

**Issue by timja** [jenkinsci/helm-charts#8]
Detect if the pmcli is installed and use that instead of install-plugins.sh

https://github.com/jenkinsci/plugin-installation-manager-tool

It's installed and available in recent versions of the Jenkins docker images since https://github.com/jenkinsci/docker/pull/971 was merged

install-plugins is a hacky shell script that isn't maintained due to the risks of changing it and has some limited testing around it.

plugin installation manager tool is the replacement and has much more testing around it.

**Comment by timja** [comment]
Not stale

**Comment by dnskr** [comment]
This issue is related to PR https://github.com/jenkinsci/helm-charts/pull/117 which I am waiting to be merged too

**Comment by halkeye** [comment]
so so can this be closed now?

**Comment by timja** [comment]
you missed the fixes https://github.com/jenkinsci/helm-charts/issues/8 in the PR so it would be autoclosed :p

**Comment by halkeye** [comment]
I didn't know about it until 2 comments up
