### ISSUE TITLE
Support extraLabels on serviceAccount

### ISSUE THREAD

**Issue by UXabre** [jenkinsci/helm-charts#801]
### Is your feature request related to a problem? Please describe

Azure Workload Identity needs a specif label set in order for it to handle workload identity:

      azure.workload.identity/use: "true"

Right now, we can't do this via the helm chart directly, and we'd need to create the serviceaccount ourselves.

### Describe the solution you'd like

add extraLabels configuration for ServiceAccount

### Describe alternatives you've considered

Don't let Helm chart create the service account and create it manually with the correct label set

### Extra

I can create the PR for this as it is very trivial to implement.

**Comment by timja** [comment]
interesting, I would've thought it was already supported but you're right it's missing, PR welcome with a unit test:
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/service-account.yaml
