### ISSUE TITLE
Jenkins 2.361.4 plugins are not getting installed

### ISSUE THREAD

**Issue by prabhukasisekar** [jenkinsci/helm-charts#824]
### Describe the bug

I am using Jenkins as sub chart with master deployment for past 2 years (not recent charts controller statefulset).
Recently I faced plugin dependency issue where I need to install Jenkins 2.332.4, plugins installed as expected, but Kubernetes plugin was broken which was addressed in particular version which needed Jenkins 2.361.4
Upgrade or install (new) of Jenkins 2.361.4  using helm charts is not installing any plugins.
Same helm charts is installing plugins with Jenkins 2.332.4

Jenkins pod logs are 
<img width="1174" alt="Screenshot 2023-03-28 at 3 21 35 PM" src="https://user-images.githubusercontent.com/59467321/228198923-4c607dbc-5814-4486-b95f-b32868c9d761.png">

copy-default-config - container logs 
<img width="563" alt="Screenshot 2023-03-28 at 3 23 44 PM" src="https://user-images.githubusercontent.com/59467321/228199498-88e77a08-ebad-49ef-bee4-9b6c4ff7e597.png">

Plugins list in values.yaml

<img width="388" alt="Screenshot 2023-03-28 at 3 24 14 PM" src="https://user-images.githubusercontent.com/59467321/228199607-c4269e16-0101-466f-b6e6-a40c5dcdfe3a.png">

When used the latest Jenkins charts of controller (instead of master) stateful set I am not seeing the issue.
I have scenario where already we are using older charts in some instance and not sure how the upgrade from old charts to new charts will work - not ok to take that risk.

Any help is appreciated.

### Version of Helm and Kubernetes

```markdown
- Helm: v3.2.4
- Kubernetes: v1.22.17
- Ubuntu 20.04
```

### Chart version

version: 2.10.0 using master deployment charts (not stateful set)

### What happened?

```bash
1. Install Jenkins 2.361.4 with few plugins in values.yaml
2. Installation is completing successfully but no plugins are installed
3. Attached screenshots of logs and plugins above.
```

### What you expected to happen?

I expect plugins to be installed or show dependency errors in the logs.

### How to reproduce it

```markdown
Few lines to show I am using older helm charts.

clusterZone: "cluster.local"

master:
  httpsKeyStore:
    jenkinsHttpsJksSecretName: ''
    enable: false
    httpPort: 8081
```

**Comment by EnriqueAlmanza** [comment]
following the issue. I have the exact same problem with image 2.387.1 and helm chart 4.3.10

**Comment by prabhukasisekar** [comment]
Hi,

I was able to resolve the reported issue by moving to latest Jenkins helm charts and making the values.yaml, deployment yaml changes related to our features/functions from old charts.
The issue took few days to be resolved through experimental method.
I have installed  Jenkins tag: "2.361.4" our new Jenkins helm charts.

Thank you

**Comment by Suraj-Mittal** [comment]
> Hi,
> 
> I was able to resolve the reported issue by moving to latest Jenkins helm charts and making the values.yaml, deployment yaml changes related to our features/functions from old charts. The issue took few days to be resolved through experimental method.
> 
> I have installed Jenkins tag: "2.361.4" our new Jenkins helm charts, hope it helps someone who may see the reported issue.
> 
> Thank you

Can you please close this issue?
