### ISSUE TITLE
4.3.21 is not published

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/helm-charts#852]
### Describe the bug

Hi,

Looks release 4.3.21 was published on GitHub but not the chart repository (workflow failed : https://github.com/jenkinsci/helm-charts/actions/runs/4666744552/jobs/8261693082).

It's confusing for users and also break automatic update tools like renovate that fetch GitHub releases.

Regards,

### Version of Helm and Kubernetes

```markdown
- Helm: 
- Kubernetes:
```

### Chart version

4.3.21

**Comment by NotMyFault** [comment]
I bumped the charts to 4.3.22, this doesn't fill the gap, but allows you to skip it.

Apologizes for the inconvenience.

**Comment by mcdonagj** [comment]
No worries at all; appreciate the quick turnaround! 💯
