### ISSUE TITLE
Unable to refer secret from a different namespace

### ISSUE THREAD

**Issue by getthehelloutofit** [jenkinsci/helm-charts#858]
### Describe the bug

We have a Amazon ECR secret created in a different namespace. Jenkins was created in a different namespace.
How jenkins can refer secret from different namespace ?

### Version of Helm and Kubernetes

```markdown
- Helm: 
- Kubernetes:
```

### Chart version

Jenkins 2.401

### What happened?

```bash
1. Created a image pull secret in a different namespace
2. Trying to refer our custom image from our AWS ECR using the secret, and couldn't find a way
3.
...
```

### What you expected to happen?

An additional variable to allow secret from a different namespace
  imagePullSecrets:
    - name: secret-name
      namespace: new-name_space

**Comment by ac-miller** [comment]
You won't be able to do this. Kubernetes does not allow for secret usage across namespaces. You'll have to replicate the secret(s) to namespaces they need to be used. There are operators that exist to replicate secrets easily (such as https://github.com/alexellis/registry-creds)
