### ISSUE TITLE
Is it possible add configmaps, services, endpoints in default role?

### ISSUE THREAD

**Issue by BinaryWorld2099** [jenkinsci/helm-charts#859]
### Is your feature request related to a problem? Please describe

Is it possible add configmaps, services, endpoints in default role?

https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/rbac.yaml#L20

or 

have custom role binding

I am getting below error
 message: endpoints is forbidden: User "system:serviceaccount:jenkins:default" cannot list resource "endpoints" in API group "" in the namespace "jenkins"

**Comment by timja** [comment]
The helm chart just provides what is required for it. Why do you need to read endpoints?

If it's a custom integration then you can just add another role and rolebinding referring to the service account:
https://github.com/jenkinsci/helm-charts/blob/997043be51121b415cda2d741d2c06b2719f6be9/charts/jenkins/templates/rbac.yaml#L47-L50

**Comment by BinaryWorld2099** [comment]
Thanks, this is exactly what I am doing
![image](https://user-images.githubusercontent.com/106383882/234214859-0478d8fc-b3f7-41d3-93ea-11e9f832e309.png)
