### ISSUE TITLE
Jenkins agent templates lost after jenkins controller pod restarts

### ISSUE THREAD

**Issue by ajcontrib** [jenkinsci/helm-charts#865]
### Describe the bug

Setting up custom build agents using Kubernetes plugin on Jenkins represents a major issue.

Every time the Jenkins master node restarts, the custom agent templates defined in Manage Jenkins > Configure System > Cloud > Kubernetes are lost and we need to re-add them again.

I wonder what should be done to permanently save our custom agent templates especially that we regularly update Jenkins version and/or plugins.

### Version of Helm and Kubernetes

```markdown
- Helm: 3.11
- Kubernetes: 1.23.7
```

### Chart version

jenkins-4.3.22

### What happened?

Jenkins custom agents are lost and need to be manually added again each time Jenkins pod is restarted.

### What you expected to happen?

Custom Jenkins agent templates permanently saved.

### How to reproduce it

```bash
1.Add custom agent templates under Manage Jenkins > Configure System > Cloud > Kubernetes
2.Perform an action that requires Jenkins to restart. for example install or update plugins.
3.Jenkins restarted
```

### Anything else we need to know?

Jenkins configuration, jobs, credentials etc. are stored in the Jenkins persistent volume.
Nonetheless, Jenkins custom agent templates are lost after each restart.

**Comment by timja** [comment]
Either add them to the configuration as code functionality that the helm chart provides or remove the default scripts,
have a look here:
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/jcasc-config.yaml

**Comment by ajcontrib** [comment]
Thanks @timja for the clear answer
I got it working by adding my agent templates in podTemplates map in values like the following:
`podTemplates:
    customAgent: |
      - name: customAgent
        label: customAgent
        imagePullSecrets:
        - name: regcred
        containers:
          - name: agent
            image: agent_docker_image:0.1
            command: sleep
            args: 99999
            ttyEnabled: true
            workingDir: /home/jenkins/agent
`
