### ISSUE TITLE
helm unit test fails while using latest helm-unittest plugin

### ISSUE THREAD

**Issue by w7089** [jenkinsci/helm-charts#872]
### Describe the bug

Installing any 0.3.* version of [helm unit test plugin]( https://github.com/helm-unittest/helm-unittest/tags) and running jenkins chart's unit tests using it fails with multiple errors, e.g.:

```

 FAIL  Controller Primary Ingress       jenkins/unittests/jenkins-controller-ingress-test.yaml
        - enabled

                - asserts[4] `matchRegex` fail
                        Template:       jenkins/templates/jenkins-controller-ingress.yaml
                        DocumentIndex:  0
                        Error:
                                unknown path metadata.labels.helm\.sh/chart
```

Also, installing specific version of the plugin isn't possible with 0.3.* versions anymore using `helm plugin install https://github.com/quintush/helm-unittest --version $HELM_UNIT_TEST_VERSION` (which is most probably plugin's issue), but might be related.

### Version of Helm and Kubernetes

```markdown
- Helm: `v3.12.0`
- Kubernetes: `v1.20.13`
```

### Chart version

latest

### What happened?

Helm unit tests failed

### What you expected to happen?

tests to succeed 

### How to reproduce it

1.`helm plugin install https://github.com/quintush/helm-unittest`
2.`git clone git@github.com:jenkinsci/helm-charts.git`
3.`cd helm-charts/charts/`
4.`helm unittest -u -f unittests/*-test.yaml jenkins` 

Note that `--helm3 ` flag is not required anymore

### Anything else we need to know?

Using latest `0.2.*` version and running the tests succeeds

**Comment by kvanzuijlen** [comment]
@timja This has been resolved in #974
