### ISSUE TITLE
Liveness and Readiness probe looks weird

### ISSUE THREAD

**Issue by longfei-zhang** [jenkinsci/helm-charts#90]
**Describe the bug**
Liveness and Readiness looks weird

    Liveness:       http-get http://:http/login delay=90s timeout=5s period=10s #success=1 #failure=5
    Readiness:      http-get http://:http/login delay=60s timeout=5s period=10s #success=1 #failure=3

**Version of Helm and Kubernetes**:

```console
$ helm version
Client: &version.Version{SemVer:"v2.16.6+unreleased", GitCommit:"7591224399d354723de3052fd97977f6fab3f531", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.6+unreleased", GitCommit:"086379cdd785e802d0e25212a75db86a64826d75", GitTreeState:"clean"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-es", GitCommit:"8f0157355cb1c47309f5f527fcb7b06115f96819", GitTreeState:"clean", BuildDate:"2020-09-05T07:45:42Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-es", GitCommit:"8f0157355cb1c47309f5f527fcb7b06115f96819", GitTreeState:"clean", BuildDate:"2020-09-05T07:45:42Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:

**What happened**:

The Liveness and Readiness probe looks weird
**What you expected to happen**:

Liveness and Readiness is readable

**How to reproduce it** (as minimally and precisely as possible):

install the chart

**Anything else we need to know**:

**Comment by torstenwalter** [comment]
From the description I don't get what you want to improve.

This is how the rendered output looks like:

```
$ helm template jenkins/jenkins -s templates/jenkins-master-deployment.yaml|grep -A 14 livenessProbe
          livenessProbe:
            httpGet:
              path: "/login"
              port: http
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5

```

**Comment by longfei-zhang** [comment]
helm template rendered output looks fine, my question is when I describe the pod, the Liveness and Readiness output looks wierd:
    Liveness:       http-get http://:http/login delay=90s timeout=5s period=10s #success=1 #failure=5
    Readiness:      http-get http://:http/login delay=60s timeout=5s period=10s #success=1 #failure=3

the "http://:http/login" confused me.
