### ISSUE TITLE
JCasC Security Realm in a Secret

### ISSUE THREAD

**Issue by Sadzeih** [jenkinsci/helm-charts#91]
**Is your feature request related to a problem? Please describe.**
We use the googleOAuth2 security realm for authentication. Right now, the clientId and clientSecret values are in the values file and deployed as a configmap, which is not very secure.

**Describe the solution you'd like**
I would love to be able to give a secret name and key to provide the securityRealm, so that I can put my secret securely (with sealed secrets for example) in my repository.

**Comment by torstenwalter** [comment]
Did you check if https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc solves your issue?
