### ISSUE TITLE
Understanding version details in Jenkins Helm Chart

### ISSUE THREAD

**Issue by avnerv** [jenkinsci/helm-charts#927]
### Is your feature request related to a problem? Please describe

Could you clarify the meaning of the following? Are these the versions that were tested for the applicable Helm chart version?
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml#L25
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml#L637

I'm inquiring because these are not the most recent versions, even though the Helm chart release was created just a week ago:
https://github.com/jenkinsci/helm-charts/releases/tag/jenkins-4.6.6

**Comment by timja** [comment]
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml#L25 it just showing what the default is, but it's pulled from the appVersion: https://github.com/jenkinsci/helm-charts/blob/4971255c3ef6b017a1e1837abc5aaf83b73aa2c5/charts/jenkins/Chart.yaml#L5

the app version flag is automatically updated.

https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml#L637 is the remoting image used for Kubernetes agent pods, it is not automatically updated and currently needs someone to send a PR to update it.
