### ISSUE TITLE
helm specifies that the repo cannot pull the chart

### ISSUE THREAD

**Issue by xzclinux** [jenkinsci/helm-charts#943]
### Describe the bug

![image](https://github.com/jenkinsci/helm-charts/assets/75306994/65313432-0a77-41d3-90c5-1c50908400eb)
helm version v3.10.3
k3s version v1.26.7+k3s1
This will affect my ability to deploy Jenkins through the terraform provider

### Version of Helm and Kubernetes

```markdown
- Helm: 
- Kubernetes:
```

### Chart version

4.8.2

### What happened?

```bash
1.
2.
3.
...
```

**Comment by kvanzuijlen** [comment]
@xzclinux Can you please elaborate? If you've already resolved the issue, please include how, as it could help other people.

**Comment by timja** [comment]
not enough detail so closing it
