### ISSUE TITLE
Update helm-unittests from 0.2.11 to 0.3.x

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/helm-charts#956]
Currently, we are using a deprecated and unmaintained version of the helm-unittest plugin. The helm-unittest plugin should be sourced from https://github.com/helm-unittest/helm-unittest, rather than https://github.com/quintush/helm-unittest.

**Comment by professorabhay** [comment]
Hey @NotMyFault, I would like to update the things to work correctly. 
Kindly assign this to me and provide some more details about implementation.

**Comment by NotMyFault** [comment]
> Hey @NotMyFault, I would like to update the things to work correctly. 
> 
> Kindly assign this to me and provide some more details about implementation.

No assignment needed, simply go ahead and file a PR 😀

All you need to do is updating the old reference of helm unit tests in docs and code and update test cases as needed, so the checks on the PR are green.

**Comment by professorabhay** [comment]
@NotMyFault, Someone else randomly raised the PR when he knew someone was working on it. LOL!
Anyways, you guys will merge that or should I open a new one?

**Comment by professorabhay** [comment]
Can you just tell me more about the bumping chat version, please?
Thanks

**Comment by NotMyFault** [comment]
What are you looking for in particular?
