### ISSUE TITLE
GCS backup not supported

### ISSUE THREAD

**Issue by chad-barensfeld-exa** [jenkinsci/helm-charts#96]
2020/10/18 16:09:58 Backup started!
2020/10/18 16:09:58 Getting clients
2020/10/18 16:09:58 gs not implemented

Is this still not supported? 

https://github.com/helm/charts/issues/20170

https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml#L722

**Comment by patsevanton** [comment]
Hello! Is jenkins helm support backup to Google Cloud Storage ? Thanks!
