### ISSUE TITLE
Add support for generic ephemeral storage

### ISSUE THREAD

**Issue by justusbunsi** [jenkinsci/helm-charts#982]
### Is your feature request related to a problem? Please describe

https://github.com/jenkinsci/kubernetes-plugin/pull/1489 introduces the possibility to use ephemeral storage volumes in the Build pod specification. According to https://github.com/jenkinsci/helm-charts/blob/762105a9828e241b8c52535834e70efa2b61afa6/charts/jenkins/templates/_helpers.tpl#L480-L492 the Helm Chart currently not support that new type `genericEphemeralVolume`.

### Describe the solution you'd like

I happily provide a PR to add that support. What I would need to know is whether I should also bump the `kubernetes-plugin` in such PR to the supporting version or if I should split it into different PRs? It looks like there is no automatism right now to update the listed plugins.

**Comment by timja** [comment]
> I happily provide a PR to add that support. What I would need to know is whether I should also bump the kubernetes-plugin in such PR to the supporting version or if I should split it into different PRs? It looks like there is no automatism right now to update the listed plugins.

Combined PR is fine, there's discussion in this pull request about automating the update of the plugin: https://github.com/jenkinsci/helm-charts/pull/979
