### ISSUE TITLE
Use https://github.com/norwoodj/helm-docs to generate VALUES_SUMMARY.md

### ISSUE THREAD

**Issue by kvanzuijlen** [jenkinsci/helm-charts#986]
### Is your feature request related to a problem? Please describe

I'd like to propose/implement https://github.com/norwoodj/helm-docs to automatically generate a summary of the configurable values, similar to https://github.com/renovatebot/helm-charts/tree/main/charts/renovate#values. This could be part of the `README.md` in `charts/jenkins` or (still) a separate file, your preference. Using helm-docs would mean copying the current documentation to the `values.yaml` file.

**Comment by timja** [comment]
Sounds great, happy either way depending on what it looks like

**Comment by kvanzuijlen** [comment]
I'll get a PR going once I'm done with #979 unless someone else wants to pick this up in the meantime!
