### ISSUE TITLE
Agent nodeSelector configuration is excluded

### ISSUE THREAD

**Issue by Jdelachi** [jenkinsci/helm-charts#987]
When I deploy the helm chart, I specify the parameter "agent.nodeSelector" to "lke.linode.com/pool-id=225360".

The Kubernetes plugin configuration has the expected value (lke.linode.com/pool-id=225360) in the nodeSelector field under podtemplate.
Image:
![image](https://github.com/jenkinsci/helm-charts/assets/143198329/4e659746-7f76-474e-8b4a-b071f1911c23)

When I trigger a pipeline, I don't get this node selector if not the following nodeSelector which was not specified on any field:
```
nodeSelector:
    kubernetes.io/os: "linux"
```
Image:
![image](https://github.com/jenkinsci/helm-charts/assets/143198329/248c9e48-f2e8-4ab6-8325-96080a67d94f)

**Comment by pashcan** [comment]
Heya, what does your pipeline definition look like? I've had this happen before whenever I forget to use `inheritFrom 'default'` in my agent definition. e.g.
```
pipeline {
  agent {
    kubernetes {
      inheritFrom 'default'
    }
  }
...
```

**Comment by Jdelachi** [comment]
Wow good catch, I added the following and it works as expected now:

podTemplate(inheritFrom: 'default', yaml: """
apiVersion: v1
kind: Pod

My initial confusion was because the labels from the default template were added to the pod, so I thought that the "inherentFrom" was configured out of the box.

Thanks @pashcan
