### ISSUE TITLE
Support for ARM Processors

### ISSUE THREAD

**Issue by darktempla** [jenkinsci/helm-charts#99]
**Describe the bug**
Running the helm chart on a K3S Raspberry Pi cluster (ARM architecture) fails on pod initialization.

```console
$ kubectl get pods
NAME                       READY   STATUS                  RESTARTS   AGE
jenkins-68b4b97c7b-ctv89   0/2     Init:CrashLoopBackOff   7          22m
```

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8+k3s1", GitCommit:"6b595318666804506c19cfc3d3d228423d38fab1", GitTreeState:"clean", BuildDate:"2020-08-14T20:42:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/arm"}
```

**Which version of the chart**:

```
NAME   	NAMESPACE	REVISION	UPDATED                              	STATUS  	CHART         	APP VERSION
jenkins	jenkins  	1       	2020-10-20 01:59:12.599162 +1000 AEST	deployed	jenkins-2.13.1	lts
```

**What happened**:
Fails when running init container.
Looks like it's pulling an image that cannot run on an ARM architecture.

```console
$ kubectl logs jenkins-68b4b97c7b-ctv89 -c copy-default-config
standard_init_linux.go:211: exec user process caused "exec format error"
```

**What you expected to happen**:
The Jenkins image to support multi-architectures

**How to reproduce it** (as minimally and precisely as possible):

1. Run k3s on a ARM based architecture (eg. Raspberry Pi).
2. Install helm chart
3. View pod status

**Anything else we need to know**:

My CPU version
```
$ cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
```

**Comment by torstenwalter** [comment]
All you need to do is to find images which run on arm and configure those. Would be nice if you could share am example which could be added as documentation.

**Comment by darktempla** [comment]
Thanks for the prompt reply @torstenwalter 👍 
I had a look into this and from what I can tell there are 4 images required:

1. `jenkins/jenkins` for the Jenkins master
2. `jenkins/inbound-agent` for the Jenkins dynamic agent (jnlp)
3. `kiwigrid/k8s-sidecar:0.1.144` for config auto reloading
4. `maorfr/kube-tasks` if you want to enable the backup functionality

With the following overrides (see below) I was able to get the master up and running but the issue was the only `inbound-agent` I could find that was ARM based was only for `arm64` so without any dynamic agents it pretty much renders Jenkins useless.

It is worth noting it was failing the liveliness and readiness probes preventing a successful roll-out so I had to disable that but I suspect it was just Jenkins taking ages to come up with limited resources and I could have tweaked the timeouts to remedy this. Once up and running the master seemed to work functionally well.

The `kiwigrid/k8s-sidecar` already publishes an image for `arm7` which worked a treat.

The `jenkins4eval` crew publish an ARM version of jenkins which I used by not an `inbound-agent` but from what I have  seen in Github issues is the `jenkins4eval` is the unstable version of the official Jenkins images for testing before making their way into the stable images.

The issue is people asked for support for ARM around about 2 years ago and the multi-arch still hasn't be brought into the stable build that this chart uses which to be fair is a support-ability issue.

* https://github.com/jenkinsci/docker/issues/686

To be fair as this is only a home DEV setup for me as much as I like Jenkins and it's power in the sake of timeliness now and in the future I would otherwise be better off using alternative CI/CD in which most that I have looked at already officially publish ARM based images.

If the maintainers of the Chart can get the required images published for ARM then I would be happy to re-explore this and contribute documentation around running it on ARM based clusters.

### Overrides

```yaml
master:
  image: jenkins4eval/jenkins
  tag: latest
  healthProbes: false
agent:
  image: pi4k8s/inbound-agent
  tag: 4.3
namespace: jenkins
persistence:
  enabled: true
  existingClaim: "jenkins-storage"
```

**Comment by darktempla** [comment]
Raised this issue on the `jenkins4eval/inbound-agent` see if they come to the party and also produce an ARM based image.

https://github.com/jenkinsci/docker-inbound-agent/issues/205

**Comment by darktempla** [comment]
Apparently a no-go as not on support road-map for Jenkins.
https://www.jenkins.io/project/roadmap

@torstenwalter thanks for the effort you put into replying. Appreciate it. Closing issue.

**Comment by yalopov** [comment]
Anyone who wants to try this chart on a Raspberry Pi, it's usable, you just need to modify `numExecutors` variable in values chart file to allow master node to create executors and use them as usual, just remember that those executors will be running on the master node or the jenkins container inside the jenkins pod.

Otherwise, it'll try to create pod agents in the cluster and it will fail because agent image is not available for aarch64/arm64 architecture.

It is important to clarify that many tools are built to use non-arm64 binaries, so it's not as straightforward as one would think, but in the future will be easier.

**Comment by krswin** [comment]
Any progress on Arm64 support ? Thank you.
